.travis.yml
CMakeLists.txt
examples/hello/bpWriter/CMakeLists.txt
examples/hello/timeBP/CMakeLists.txt
source/core/Engine.cpp
source/format/BP1Aggregator.cpp

@williamfgc please see changes in  87340691ec103148968563919a12155a7760299e and 79a13e77b71030b732d0775ca2af2b40a0f40332
@pnorbert Is this sufficient: af109d714e332bad5d0c932bdab8086d851d8e7d

Fix dashboard errors

---

cmake/FindDataMan.cmake

@pnorbert Does this help with DataMan?

Let DataMan_ROOT_DIR be specified by either a CMake or Env variable

---

CMakeLists.txt
examples/hello/bpWriter/helloBPWriter.cpp
examples/hello/timeBP/timeBPWriter.cpp

@pnorbert this should fix your OpenMPI linker issues with the other examples

Fix OpenMPi C++ binding issue for the whole project

---

.clang-tidy
source/format/BP1Writer.cpp

@JasonRuonanWang this should fix your mac build problems

Reinstate the use of reinterpret_cast

---

include/ADIOS.h
source/ADIOS.cpp
source/ADIOS.tcc
source/ADIOSMacros.h

Move the specializations for the ADIOS class members to thier own file

---

scripts/developer/git/setup-aliases
scripts/developer/git/setup-remotes

@guj This should fix your setup-script issue

Fix setup scripts to work with older git versions

---

Contributing.md
scripts/developer/git/setup-remotes

Update setup script and contributors guide to start from main repo instead of fork.

Tinker with setup script

---

source/utilities/format/bp1/BP1Aggregator.cpp
source/utilities/format/bp1/BP1Writer.cpp

Now meets the python dictionary format

Fixing aggregation formatting in .bp/profiling.log

---

examples/hello/datamanReader/helloDataManReader.cpp
examples/hello/datamanReader/helloDataManReader_nompi.cpp
include/engine/dataman/DataManReader.h
include/engine/dataman/DataManWriter.h
include/functions/adiosTemplates.h
include/utilities/format/bp1/BP1Writer.h
source/engine/dataman/DataManReader.cpp
source/engine/dataman/DataManWriter.cpp
source/utilities/format/bp1/BP1Writer.cpp

Dataman bugs

---

Contributing.md
include/ADIOS.h
include/ADIOS.inl
source/ADIOS.cpp
source/ADIOS.tcc
source/CMakeLists.txt

Also added docs to contributor guide for how to separate templates

Seperate templete impl from public and private for ADIOS class

---

source/adios2/capsule/heap/STLVector.cpp
source/adios2/capsule/heap/STLVector.h
source/adios2/capsule/shmem/ShmSystemV.cpp
source/adios2/capsule/shmem/ShmSystemV.h
source/adios2/core/Capsule.cpp
source/adios2/core/Capsule.h
source/adios2/engine/bp/BPFileReader.cpp
source/adios2/engine/bp/BPFileReader.h
source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/engine/bp/BPFileWriter.h
source/adios2/engine/dataman/DataManReader.cpp
source/adios2/engine/dataman/DataManReader.h
source/adios2/engine/dataman/DataManWriter.cpp
source/adios2/engine/dataman/DataManWriter.h

Removed elements that are not used

Changed Capsule constructors and members

---

testing/adios2/engine/adios1/TestADIOS1WriteRead.cpp
testing/adios2/engine/bp/TestBPWriteRead.cpp
testing/adios2/engine/hdf5/TestHDF5WriteRead.cpp

This will ensure that even if they are run they will fail

Add asserts to disabled tests.

---

source/adios2/engine/dataman/DataManWriter.tcc
source/dataman/CMakeLists.txt
source/dataman/CacheMan.cpp
source/dataman/CacheMan.h
source/dataman/DataManBase.cpp
source/dataman/DataManBase.h
source/dataman/ZmqMan.cpp

fixed a few DataMan problems caused by recent merges

---

examples/experimental/multistep/reader_allsteps.cpp

Fixed multistep example for no-mpi by adding extra ifdef's

---

examples/heatTransfer/write/IO_adios1.cpp
source/adios2/CMakeLists.txt
source/adios2/engine/adios1/ADIOS1Writer.cpp

ADIOS1: Enable compatibility with 1.10.0 adios_declare_group signature

---

source/adios2/core/IO.h
source/adios2/core/VariableBase.cpp
source/adios2/toolkit/format/bp1/BP1Writer.cpp
source/adios2/toolkit/format/bp1/BP1Writer.h
source/adios2/toolkit/format/bp1/BP1Writer.tcc
source/adios2/toolkit/interop/adios1/ADIOS1Common.h

BP file output now compatible with bpdump

---

source/adios2/toolkit/transportman/TransportMan.cpp
source/adios2/toolkit/transportman/TransportMan.h

Removed noexcept in CloseFiles

Fixed noexcept function throwing exception

---

source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/toolkit/format/bp1/BP1Aggregator.cpp
source/adios2/toolkit/format/bp1/BP1Writer.cpp
source/adios2/toolkit/format/bp1/BP1Writer.h

To do:
Memory buffer reallocation strategy

Implementing profiling.log as default

---

source/adios2/core/Engine.h

m_Name must be a string object not a const reference.

Fixes issue #130

---

source/adios2/toolkit/format/bp1/BP1Base.cpp

Adding intermediate int verbosity for string conversion stoi

Correcting a warning on Mac

---

source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/toolkit/format/bp1/BP1Base.cpp
source/adios2/toolkit/format/bp1/BP1Base.h

Tested with time aggregation and hello_bpWriter

Back to bp1 name.bp.dir/name.bp.rank format

---

examples/heatTransfer/write/IO_ph5_adios2.cpp
examples/hello/datamanReader/helloDataManReader.cpp
examples/hello/datamanReader/helloDataManReader_nompi.cpp
examples/hello/datamanWriter/helloDataManWriter.cpp
examples/hello/datamanWriter/helloDataManWriter_nompi.cpp
source/adios2/core/IO.cpp
source/adios2/core/IO.h

Keep only std::map<std::string, std::string> initializer list.
Corrected examples.

Solve Issue #171 in IO SetParameters and AddTransport

---

cmake/FindBZip2.cmake
cmake/upstream/FindBZip2.cmake

Use a newer upstream version of FindBZip2

---

examples/experimental/runtimeconfig/hello/helloBPWriter.xml
source/adios2/CMakeLists.txt
source/adios2/core/ADIOS.cpp
source/adios2/core/ADIOS.h
source/adios2/core/IO.cpp
source/adios2/core/IO.h
source/adios2/helper/adiosXML.cpp
source/adios2/helper/adiosXML.h
testing/adios2/xml/CMakeLists.txt
testing/adios2/xml/TestXMLConfig.cpp
testing/adios2/xml/config1.xml

This was intended to get pushed back until after the alpha release but it was a fairly minor effort and since the XML processing is already in the release branch now then this should make it more reliable.

Switch to pugixml

---

source/adios2/CMakeLists.txt
source/dataman/CMakeLists.txt

Setup library versioning.

---

cmake/upstream/FindBZip2.cmake
cmake/upstream/GoogleTest.cmake

Fix compatibility issues with CMake v3.5

---

source/adios2/toolkit/format/bp1/BP1Aggregator.cpp

const_cast added to MPI_Isend due to void* signature

---

bindings/python/CMakeLists.txt

Always check for python dev libs when ADIOS2_HAVE_PYTHON is TRUE

---

ReadMe.md
examples/heatTransfer/ReadMe.md
examples/hello/README.md
examples/hello/hdf5Writer/helloHDF5Writer.cpp
examples/hello/hdf5Writer/helloHDF5Writer_nompi.cpp
source/adios2/transform/compression/BZip2.h
source/dataman/MdtmMan.cpp

Warning triggered when -DCMAKE_BUILD_TYPE=Release on Mdtman

Updating some documentation, removed a warning and h5 file name

---

source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/engine/bp/BPFileWriter.h
source/adios2/toolkit/format/bp1/BP1Aggregator.cpp
source/adios2/toolkit/format/bp1/BP1Aggregator.h
source/adios2/toolkit/format/bp1/BP1Writer.cpp
source/adios2/toolkit/format/bp1/BP1Writer.h
testing/adios2/engine/CMakeLists.txt
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPWriteProfilingJSON.cpp

Added test for generating profiling.json
Fixed inclusion for NLohmannJson json.hpp in Test
Tested resulting profiling.json on R (jsonlite), Python (json)
and C++ (json for modern C++)

Moved profiling.log to profiling.json format

---

source/adios2/ADIOSMacros.h
source/adios2/CMakeLists.txt
source/adios2/core/Attribute.cpp
source/adios2/core/Attribute.h
source/adios2/core/Attribute.tcc
source/adios2/core/AttributeBase.cpp
source/adios2/core/AttributeBase.h
source/adios2/core/IO.cpp
source/adios2/core/IO.h
source/adios2/core/IO.inl
source/adios2/core/IO.tcc
source/adios2/core/Variable.h
source/adios2/core/Variable.tcc
source/adios2/core/VariableBase.cpp
source/adios2/core/VariableBase.h
source/adios2/helper/adiosType.inl
testing/adios2/interface/CMakeLists.txt
testing/adios2/interface/TestADIOSDefineAttribute.cpp

Added support for Attributes in ADIOS2 API including testing. It basically follows the Variable design.
To do (on a separate branch):
Write Attributes in BP buffer format

Attribute template core class implementation

---

source/adios2/ADIOSTypes.h
source/adios2/toolkit/format/bp1/BP1Base.cpp

Added portable PathSeparator
Fixed format for bp file name

Fixing issue #230 a bug for path in file name

---

cmake/upstream/GoogleTest.cmake
testing/adios2/engine/SmallTestData.h
testing/adios2/engine/adios1/CMakeLists.txt
testing/adios2/engine/adios1/TestADIOS1WriteRead.cpp

TO achieve this goal, GoogleTest.cmake is extended to allow
exec_wrapper and SmallTestData.h now would generate data based on
step&world_rank&world_size.

Testing: Make ADIOS1WriteRead test run in parallel

---

testing/adios2/engine/adios1/TestADIOS1WriteRead.cpp

Close #246 .
Partially address #147 . I would fix it totally this week.

Fix global array definitions in ADIOS1 test for 2D Arrays

---

bindings/python/EnginePy.cpp
bindings/python/EnginePy.h
bindings/python/IOPy.cpp
bindings/python/gluePyBind11.cpp
bindings/python/typesPy.h
examples/hello/bpTimeWriter/helloBPTimeWriter.cpp
examples/hello/bpWriter/helloBPWriter.cpp
source/adios2/ADIOSMacros.h
source/adios2/ADIOSTypes.h
source/adios2/core/IO.tcc
source/adios2/core/Variable.tcc
source/adios2/core/VariableBase.cpp
source/adios2/engine/dataman/DataManWriter.cpp
source/adios2/helper/adiosMemory.h
source/adios2/toolkit/format/bp3/BP3Base.cpp
source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/format/bp3/BP3Base.tcc
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
source/adios2/toolkit/format/bp3/BP3Serializer.cpp
source/adios2/toolkit/format/bp3/BP3Serializer.h
source/adios2/toolkit/format/bp3/BP3Serializer.tcc
source/adios2/toolkit/interop/adios1/ADIOS1Common.tcc
source/adios2/toolkit/interop/hdf5/HDF5Common.tcc
testing/adios2/engine/SmallTestData.h
testing/adios2/engine/bp/TestBPWriteRead.cpp
testing/adios2/interface/TestADIOSDefineVariable.cpp

Now Variable<std::string> has support as a local variable

Variable string type support

---

examples/heatTransfer/write/IO_ph5_adios2.cpp
examples/hello/callback/helloCallback1.cpp
examples/hello/callback/helloCallback2.cpp
source/adios2/helper/adiosMPIFunctions.inl
source/adios2/operator/compress/CompressBZip2.cpp
source/adios2/operator/compress/CompressZfp.cpp
source/adios2/toolkit/format/bp3/BP3Base.tcc
source/adios2/toolkit/format/bp3/BP3Serializer.cpp
source/adios2/toolkit/format/bp3/BP3Serializer.tcc
testing/adios2/engine/hdf5/TestHDF5WriteRead.cpp
testing/adios2/interface/TestADIOSDefineVariable.cpp

Attempting to solve HDF5 failed tests on summitdev

Reducing more warnings from cdash issue #300

---

bindings/C/adios2/adios2_c_variable.cpp
bindings/C/adios2/adios2_c_variable.h

Warnings from cdash

---

examples/hello/bpAttributeWriter/helloBPAttributeWriter.cpp
source/adios2/ADIOSMacros.h
source/adios2/core/IO.cpp
source/adios2/core/IO.h
source/adios2/engine/bp/BPFileReader.cpp
source/adios2/engine/bp/BPFileWriter.tcc
source/adios2/helper/adiosType.cpp
source/adios2/helper/adiosType.h
source/adios2/helper/adiosType.inl
source/adios2/toolkit/format/bp3/BP3Base.tcc
source/adios2/toolkit/format/bp3/BP3Deserializer.cpp
source/adios2/toolkit/format/bp3/BP3Deserializer.h
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
source/utils/bpls2/BPLS2.cpp
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPWriteReadAttributesADIOS2.cpp
testing/adios2/xml/TestXMLConfig.cpp

I64 and U64 tests might fail in Windows (long != long long).

WIP: Attribute read and write

---

source/adios2/helper/adiosType.h
source/adios2/toolkit/format/bp3/BP3Base.tcc
source/adios2/toolkit/format/bp3/BP3Deserializer.cpp
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
source/adios2/toolkit/format/bp3/BP3Serializer.cpp
testing/adios2/engine/bp/TestBPWriteReadAttributesADIOS2.cpp

Resolving long ambiguity
Correcting APPLE MACROS

Issue #313 Long integer ambiguity on Mac, Windows and Linux

---

source/adios2/engine/bp/BPFileReader.cpp
source/adios2/engine/bp/BPFileReader.h
testing/adios2/engine/SmallTestData.h
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPWriteReadAsStreamADIOS2.cpp

@pnorbert added reading through a file using stepping. See tests to adapt this to the heat transfer example reader.

Reading bp files using stepping mode BeginStep EndStep

---

source/adios2/core/ADIOS.cpp
source/adios2/core/IO.cpp
source/adios2/core/IO.h
source/adios2/helper/adiosXML.cpp
source/adios2/helper/adiosXML.h
testing/adios2/xml/TestXMLConfig.cpp

If IO object to be used.
InquireIO returns nullptr if DeclareIO not called.
Two calls to DeclareIO with the same name will throw an exception

Solving issue #320 DeclareIO must be called at least once

---

source/adios2/core/IO.cpp
source/adios2/core/IO.h
testing/adios2/interface/TestADIOSDefineAttribute.cpp
testing/adios2/interface/TestADIOSDefineVariable.cpp

Remove Single variable or attribute
Remove all variables or attributes
Note: these are dangerous functions that can result in dangling pointers and references

Issue #324 add remove variables and attributes functions in IO

---

source/adios2/core/ADIOS.h
source/adios2/core/Engine.tcc
source/adios2/engine/bp/BPFileReader.cpp
source/adios2/engine/bp/BPFileReader.tcc
source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/toolkit/format/bp3/BP3Deserializer.h
testing/adios2/engine/bp/TestBPWriteReadADIOS2.cpp

Moved to sync functions
Added exception in EndStep if Perform Puts/Gets is missing

Issue #330 put get deferred for single values not working

---

bindings/python/EnginePy.cpp
bindings/python/EnginePy.h
bindings/python/IOPy.cpp
bindings/python/IOPy.h
bindings/python/gluePyBind11.cpp
examples/hello/bpReader/helloBPReaderHeatMap2D.py
examples/hello/bpReader/helloBPReaderHeatMap3D.f90
testing/adios2/bindings/python/TestBPWriteTypes.py
testing/adios2/bindings/python/TestBPWriteTypes_nompi.py

Now passing numpy array in DefineVariable

Working example for Write and Read with Python

---

source/adios2/engine/bp/BPFileReader.cpp
source/adios2/engine/bp/BPFileReader.h
source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/toolkit/format/bp3/BP3.h
source/adios2/toolkit/format/bp3/BP3Base.cpp
source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/format/bp3/BP3Base.tcc
source/adios2/toolkit/format/bp3/BP3Deserializer.cpp
source/adios2/toolkit/format/bp3/BP3Deserializer.h
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
testing/adios2/engine/bp/TestBPWriteReadADIOS2.cpp
testing/adios2/engine/bp/TestBPWriteReadAsStreamADIOS2.cpp

Modified tests for allowing stepping read mode
Made PerformPuts and PerformGets optional

Issue #332 Enable status return from BeginStep

---

source/adios2/core/ADIOS.cpp
source/adios2/core/ADIOS.h
testing/adios2/xml/TestXMLConfig.cpp

AtIO returns a reference to IO or throws an exception since IO must
exists
Similar to C++ STL containers at function

Issue #341 AtIO replaces InquireIO

---

source/adios2/toolkit/format/bp3/BP3Serializer.cpp

Issue #327 ADIOS bp 28 minifooter tag

---

appveyor.yml

I am not sure if this will turn it off or not.

turn off VS 2017 build in appveyor

---

source/adios2/helper/adiosMath.cpp

fix IntersectionBox() check

---

examples/heatTransfer/heat_sst.xml
source/adios2/engine/sst/SstReader.cpp
source/adios2/engine/sst/SstReader.h
source/adios2/engine/sst/SstWriter.cpp
source/adios2/engine/sst/SstWriter.h
source/adios2/engine/sst/SstWriter.tcc
source/adios2/toolkit/sst/CMakeLists.txt
source/adios2/toolkit/sst/cp/cp.c
source/adios2/toolkit/sst/cp/cp_common.c
source/adios2/toolkit/sst/cp/cp_internal.h
source/adios2/toolkit/sst/cp/ffs_marshal.c
source/adios2/toolkit/sst/dp/dummy_dp.c
source/adios2/toolkit/sst/dp_interface.h
source/adios2/toolkit/sst/sst.h
source/adios2/toolkit/sst/sst_data.h
testing/adios2/engine/sst/TestSstWrite.cpp

Preliminary FFS-based MxN data transfer for global arrays

---

source/adios2/toolkit/sst/cp/cp_common.c

Don't use MPI_COMM_WORLD, but use the saved MPI communicator.

Need to use saved MPI communicator, not MPI_COMM_WORLD

---

examples/heatTransfer/heat_adios1.xml
examples/heatTransfer/heat_bpfile.xml
examples/heatTransfer/heat_dataman.xml
examples/heatTransfer/heat_hdf5.xml
examples/heatTransfer/heat_insitumpi.xml
examples/heatTransfer/read/ReadSettings.cpp
examples/heatTransfer/read/ReadSettings.h
examples/heatTransfer/read/heatRead.cpp
examples/heatTransfer/write/IO_adios2.cpp
source/adios2/engine/hdf5/HDF5ReaderP.cpp

Read now calculates dT and writes ADIOS output, T and dT. 
Need to update dataman and hdf5 configs and test those engines before merging.

[WIP] Redo heat reader

---

bindings/C/adios2/adios2_c_variable.cpp
bindings/fortran/f2c/adios2_f2c_variable.cpp
bindings/fortran/f2c/adios2_f2c_variable.h
bindings/fortran/modules/adios2_io_define_attribute_mod.f90
bindings/fortran/modules/adios2_io_define_variable_mod.f90
bindings/fortran/modules/adios2_parameters_mod.f90
bindings/fortran/modules/adios2_variable_mod.f90
testing/adios2/bindings/fortran/TestBPWriteTypes.f90

Added 1D tests, need to add more for higher dimensions

Enabling variable shape inspection #368

---

examples/heatTransfer/write/IO.h
examples/heatTransfer/write/IO_ph5.cpp
source/adios2/engine/hdf5/HDF5ReaderP.cpp
source/adios2/toolkit/interop/hdf5/HDF5Common.cpp
source/adios2/toolkit/interop/hdf5/HDF5Common.h
testing/adios2/engine/hdf5/TestHDF5WriteRead.cpp

plus resolved a bug in IO.h naming function

changed TimeStep to Step

---

source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/format/bp3/BP3Base.tcc
source/adios2/toolkit/format/bp3/BP3Deserializer.cpp
testing/adios2/engine/adios1/CMakeLists.txt
testing/adios2/engine/adios1/TestADIOS1WriteADIOS2Read.cpp

Support for bitmap and stats characteristics
Fix for Issue #414 and #409

Read Adios1 generated files

---

source/adios2/core/Engine.cpp
source/adios2/core/Engine.h
source/adios2/engine/bp/BPFileReader.cpp
source/adios2/engine/bp/BPFileReader.h
source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/engine/bp/BPFileWriter.h
source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/format/bp3/BP3Deserializer.cpp
source/adios2/toolkit/format/bp3/BP3Serializer.cpp
testing/adios2/engine/bp/TestBPWriteReadAsStreamADIOS2.cpp

BPFileReader implementation and tests
Need to add to other engines

Enhancement #415 Added CurrentStep Engine function

---

source/adios2/toolkit/format/bp3/BP3Serializer.cpp
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPWriteReadAsStreamADIOS2.cpp
testing/adios2/engine/bp/TestBPWriteReadAsStreamADIOS2_Threads.cpp

When sorting and merging metadata per variable

Threads fix

---

CMakeLists.txt
cmake/DetectOptions.cmake
cmake/FindSZ.cmake
examples/hello/CMakeLists.txt
examples/hello/bpSZWrapper/CMakeLists.txt
examples/hello/bpSZWrapper/helloBPSZWrapper.cpp
source/adios2/CMakeLists.txt
source/adios2/core/ADIOS.cpp
source/adios2/operator/compress/CompressSZ.cpp
source/adios2/operator/compress/CompressSZ.h

I finished adding SZ compression as an operator in Adios2. This includes
- SZ cmake find module
- SZ operator
- An example

SZ compression

---

source/adios2/toolkit/sst/cp/cp.c

Fix for an issue that Norbert identified.

SST previous formats fix

---

bindings/C/adios2/adios2_c_types.h
bindings/fortran/modules/adios2_adios_mod.f90
bindings/fortran/modules/adios2_engine_get_deferred_mod.f90
bindings/fortran/modules/adios2_engine_get_sync_mod.f90
bindings/fortran/modules/adios2_engine_put_deferred_mod.f90
bindings/fortran/modules/adios2_engine_put_sync_mod.f90
bindings/fortran/modules/adios2_parameters_mod.f90
bindings/fortran/modules/adios2_variable_mod.f90

Added space to include (was preventing summit-dev XL compilation)
Changing Variable handler intent from out to in
Increased variable and attribute allowed length for reading
Added formatting with fprettify

Fix for Issue #458

---

bindings/C/adios2/adios2_c_io.cpp
bindings/C/adios2/adios2_c_io.h
bindings/fortran/f2c/adios2_f2c_io.cpp
bindings/fortran/f2c/adios2_f2c_io.h
bindings/fortran/modules/adios2_io_mod.f90
testing/adios2/bindings/fortran/CMakeLists.txt
testing/adios2/bindings/fortran/TestRemove.f90
testing/adios2/bindings/fortran/TestRemove_nompi.f90

Remove one variable/attribute or all variables/attributes
Added test for variables

Issue #460 remove functions in C and Fortran bindings

---

source/adios2/core/IO.cpp
source/adios2/engine/mixer/HDFMixer.cpp
source/adios2/engine/mixer/HDFMixer.h
source/adios2/engine/mixer/HDFMixerWriter.cpp
source/adios2/toolkit/interop/hdf5/HDF5Common.cpp

added H5Type map options when reading from H5

necessary changes to update hdfmixer

---

source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/engine/bp/BPFileWriter.h
source/adios2/toolkit/format/bp3/BP3Base.cpp
source/adios2/toolkit/format/bp3/BP3Base.tcc
source/adios2/toolkit/format/bp3/BP3Serializer.cpp
testing/adios2/engine/bp/TestBPWriteProfilingJSON.cpp

Added more coverage for buffering profiling
and metadata merge sort 
Added metadata file profiling info in profiling.json
Fixed bug for turning off profiling

Issue #465 and profiling improvements

---

source/adios2/engine/hdf5/HDF5ReaderP.cpp
source/adios2/toolkit/interop/hdf5/HDF5Common.cpp

instead of (unsigned) long long (cori)  or long (mac 64bit)

let H5T_STD_U/I64 map to u/int64_t

---

examples/heatTransfer/read/heatRead.cpp
examples/heatTransfer/read_fileonly/heatRead_adios1.cpp
examples/heatTransfer/read_fileonly/heatRead_adios2.cpp
examples/heatTransfer/write/main.cpp
source/utils/CMakeLists.txt
source/utils/adios2_reorganize/Reorganize.cpp
source/utils/adios2_reorganize/Reorganize.h
source/utils/adios2_reorganize/main.cpp

adios2_reorganize works like stage_write in adios1. It works with the heat transfer example using bpfile or sst engines.

Stage write

---

thirdparty/GTest/CMakeLists.txt

See here: https://github.com/google/googletest/issues/292

Try to get around unresolved symbol on Windows

---

examples/hello/bpWriter/CMakeLists.txt
examples/hello/bpWriter/helloBPSubStreams.cpp
source/adios2/CMakeLists.txt
source/adios2/core/Engine.cpp
source/adios2/core/Engine.h
source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/engine/bp/BPFileWriter.h
source/adios2/engine/bp/BPFileWriter.tcc
source/adios2/engine/plugin/PluginEngine.h
source/adios2/helper/adiosMPIFunctions.h
source/adios2/helper/adiosMPIFunctions.inl
source/adios2/helper/adiosMPIFunctions.tcc
source/adios2/toolkit/aggregator/mpi/MPIAggregator.cpp
source/adios2/toolkit/aggregator/mpi/MPIAggregator.h
source/adios2/toolkit/aggregator/mpi/MPIChain.cpp
source/adios2/toolkit/aggregator/mpi/MPIChain.h
source/adios2/toolkit/format/bp3/BP3Base.cpp
source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/format/bp3/BP3Deserializer.h
source/adios2/toolkit/format/bp3/BP3Serializer.cpp
source/adios2/toolkit/format/bp3/BP3Serializer.h
source/adios2/toolkit/format/bp3/BP3Serializer.tcc
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPWriteAggregateRead.cpp

Refactor aggregation into classes
Current MPIChain using one extra buffer per process
Refactored BPFileWriter for reusability
Added Engine Flush function
Tests for write and read with 2 substreams

Initial MPI aggregation on BP3Serializer using chain method

---

source/adios2/engine/bp/BPFileWriter.tcc
source/adios2/engine/dataman/DataManWriter.tcc
source/adios2/engine/insitumpi/InSituMPIWriter.tcc
source/adios2/toolkit/format/bp3/BP3Base.cpp
source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/format/bp3/BP3Serializer.cpp
source/adios2/toolkit/format/bp3/BP3Serializer.h
source/adios2/toolkit/format/bp3/BP3Serializer.tcc
testing/adios2/engine/bp/TestBPWriteReadAttributesADIOS2.cpp

Adding resize functions when writing attributes
Enhacement #400 only rank 0 writes attributes in data

Issue #554 position > buffer size

---

bindings/C/c/adios2_c_io.cpp
bindings/C/c/adios2_c_io.h
bindings/Fortran/f2c/adios2_f2c_io.cpp
bindings/Fortran/f2c/adios2_f2c_io.h
bindings/Fortran/modules/adios2_io_mod.f90
bindings/Fortran/modules/adios2_variable_mod.f90
bindings/Fortran/modules/mpi/adios2_adios_init_mod.f90
bindings/Fortran/modules/nompi/adios2_adios_init_mod.f90
source/adios2/core/IO.cpp
source/adios2/core/IO.h
testing/adios2/bindings/fortran/TestBPWriteTypesLocal.f90

single adios2_init subroutine with multiple signatures
adios2_io_engine_type subroutine to get current engine type

F90 requests

---

bindings/Python/py11File.cpp
bindings/Python/py11File.h
bindings/Python/py11glue.cpp
examples/highLevelAPI/BPWriteTypesConfig.py
examples/highLevelAPI/TestBPWriteTypesHighLevelAPIConfig.py
examples/highLevelAPI/adios2NPTypes.py
examples/highLevelAPI/config1.xml
source/adios2/core/IO.cpp
testing/adios2/bindings/python/TestBPWriteTypesHighLevelAPI.py

1) Added available_variables() function that returns a dict[var_name,
dict[key_meta,value_meta] ]
2) Default selection is current shape for global variables
3) Added open functions that takes config file and ioNameInConfigFile to
reuse xml config files
Omitting mix/max for single values in IO::GetAvailableVariables

#560 adding Python features in high-level API

---

source/adios2/engine/sst/SstReader.cpp
source/adios2/engine/sst/SstReader.h
source/adios2/engine/sst/SstWriter.cpp
source/adios2/engine/sst/SstWriter.h
source/adios2/toolkit/sst/cp/cp_common.c
source/adios2/toolkit/sst/cp/cp_internal.h
source/adios2/toolkit/sst/cp/cp_reader.c
source/adios2/toolkit/sst/cp/cp_writer.c
source/adios2/toolkit/sst/cp/ffs_marshal.c
source/adios2/toolkit/sst/dp/evpath_dp.c
source/adios2/toolkit/sst/dp/rdma_dp.c
source/adios2/toolkit/sst/dp_interface.h
source/adios2/toolkit/sst/sst.h
thirdparty/EVPath/EVPath/cm.c

This is a resubmit of https://github.com/ornladios/ADIOS2/pull/523...

Sst dynamic mem

---

source/adios2/core/Engine.cpp
source/adios2/core/Engine.h
source/adios2/core/IO.cpp
testing/adios2/engine/bp/TestBPWriteReadADIOS2.cpp

Added operator bool for Engine object so check if it's active.
IO would check if Engine is active at Open, if not removes it.
Added tests.

#550 Enable reopening Engine after Close

---

bindings/Python/py11File.cpp
source/adios2/engine/bp/BPFileReader.cpp
source/adios2/engine/bp/BPFileReader.h
source/adios2/engine/bp/BPFileReader.tcc
source/adios2/toolkit/format/bp3/BP3Deserializer.cpp
source/adios2/toolkit/format/bp3/BP3Deserializer.h
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
testing/adios2/bindings/python/TestBPWriteTypesHighLevelAPI.py
testing/adios2/engine/bp/TestBPWriteReadADIOS2.cpp

Fix C++11 library bug when reading multiple steps
Fix Python binding numpy array allocation by shape.

Pyread bug when reading multiple steps

---

source/adios2/engine/insitumpi/InSituMPIReader.tcc
source/adios2/engine/insitumpi/InSituMPIWriter.tcc
source/adios2/toolkit/format/bp3/BP3Base.cpp
source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/format/bp3/BP3Serializer.tcc

Support single values in InSituMPI engine

Insitumpi singlevalue

---

source/adios2/engine/bp/BPFileReader.cpp
testing/adios2/engine/bp/TestBPWriteReadADIOS2.cpp

Patch for issue #590, need to address issue #573

Readbug patch

---

source/adios2/toolkit/sst/cp/cp_common.c
source/adios2/toolkit/sst/cp/cp_reader.c
source/adios2/toolkit/sst/cp/cp_writer.c
source/adios2/toolkit/sst/cp/ffs_marshal.c
source/adios2/toolkit/sst/dp/evpath_dp.c

Codacy fixes

---

source/adios2/toolkit/sst/cp/ffs_marshal.c
source/adios2/toolkit/sst/sst.h
thirdparty/dill/dill/arm6.c

Fix some integer types that were in compatible and hadn't been cleaned up.

Int types cleanup

---

thirdparty/EVPath/EVPath/cm.c

Testing a possible fix to the heisen-bug affecting some platforms during SST shutdown.

Tweak for EVPath shutdown that impact SST heisen-bug.

---

source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/helper/adiosMPIFunctions.cpp
source/adios2/helper/adiosMPIFunctions.h
source/adios2/mpidummy.h
source/adios2/toolkit/aggregator/mpi/MPIAggregator.cpp
source/adios2/toolkit/aggregator/mpi/MPIAggregator.h
source/adios2/toolkit/aggregator/mpi/MPIChain.cpp
source/adios2/toolkit/aggregator/mpi/MPIChain.h
source/adios2/toolkit/format/bp3/BP3Serializer.cpp
source/adios2/toolkit/format/bp3/BP3Serializer.h

Added Checks to MPI return values to help debugging XGC on Titan
Capturing Isend and Irecv requests with Wait

Reformulated MPI Aggregation

---

source/adios2/toolkit/sst/cp/cp_reader.c
source/adios2/toolkit/sst/cp/ffs_marshal.c
thirdparty/EVPath/EVPath/cmib.c

Fix warnings and an FFS-marshaling bug on the Pi.  Pull in latest EVPath for some of fix.

Raspberry Pi bugfix

---

source/adios2/engine/sst/SstReader.cpp
source/adios2/engine/sst/SstReader.h
source/adios2/engine/sst/SstWriter.h
source/adios2/toolkit/sst/cp/cp_internal.h
source/adios2/toolkit/sst/cp/cp_writer.c
source/adios2/toolkit/sst/sst.h

Tweaks to compile and kill some warnings on the PGI compiler on SummitDev.

Summit dev fixes

---

source/adios2/toolkit/format/bp3/BP3Serializer.cpp

Reducing the number of reallocations

#625 addressing slow metadata for large number of variables

---

source/utils/bpls/bpls.cpp

fixed type warning in bpls

---

cmake/DetectOptions.cmake
cmake/FindZeroMQ.cmake

Add version checking to FindZeroMQ

---

bindings/C/c/adios2_c_io.cpp
bindings/C/c/adios2_c_io.h
bindings/Fortran/f2c/adios2_f2c_io.cpp
bindings/Fortran/f2c/adios2_f2c_io.h
bindings/Fortran/modules/adios2_adios_mod.f90
bindings/Fortran/modules/adios2_engine_mod.f90
bindings/Fortran/modules/adios2_file_mod.f90
bindings/Fortran/modules/adios2_io_define_attribute_mod.f90
bindings/Fortran/modules/adios2_io_define_variable_mod.f90
bindings/Fortran/modules/adios2_io_mod.f90
bindings/Fortran/modules/adios2_parameters_mod.f90
bindings/Fortran/modules/mpi/adios2_adios_init_mod.f90
bindings/Fortran/modules/mpi/adios2_fopen_mod.f90
bindings/Fortran/modules/mpi/adios2_io_open_mod.f90
bindings/Fortran/modules/nompi/adios2_adios_init_mod.f90
bindings/Fortran/modules/nompi/adios2_fopen_mod.f90
bindings/Fortran/modules/nompi/adios2_io_open_mod.f90
testing/adios2/bindings/fortran/TestBPWriteAttributes.f90
testing/adios2/bindings/fortran/TestBPWriteTypes.f90

Implemented logical handler%valid field

Enable Fortran type checks

---

bindings/CXX11/CMakeLists.txt
bindings/CXX11/cxx11/ADIOS.inl

Removed ADIOS.h from ADIOS.inl
Install ADIOS.inl

Fixed external compilation issue #670

---

bindings/CXX11/CMakeLists.txt

fstream/ADIOS2fstream.h not found

Related to #670 make install issue

---

source/adios2/toolkit/sst/cp/cp_writer.c
testing/adios2/engine/sst/CMakeLists.txt
testing/adios2/engine/sst/TestSstRead.cpp
testing/adios2/engine/sst/TestSstWrite.cpp
testing/adios2/engine/sst/TestSstWriteF.f90
testing/adios2/engine/sst/run_staging_test.in

This is the default behaviour if a queue limit is specified and DiscardOnQueueFull isn't explicitly set.  Also add tests that cover a reader arriving late when RendezvousReader=1, and when RendezvousReader=1,QueueLimit=3 and the default blocking behaviour.

Implement BlockOnQueueFull functionality in Sst.  

---

docs/user_guide/source/api/engine.rst
docs/user_guide/source/api/io.rst
docs/user_guide/source/api/variable.rst
docs/user_guide/source/engines/hdf5.rst
docs/user_guide/source/engines/sst.rst

Fixing the documentation. Making compatible with changes in API and some grammar checking.

Documentation

---

source/adios2/toolkit/format/bp3/BP3Serializer.cpp
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPWriteReadAttributesMultirank.cpp

#712 enable attributes in all ranks

---

testing/adios2/engine/dataman/TestDataMan.cpp

disable dataman test when ZMQ is not available

---

examples/useCases/CMakeLists.txt
examples/useCases/insituGlobalArrays/CMakeLists.txt
examples/useCases/insituGlobalArrays/insituGlobalArraysReaderNxN.cpp
examples/useCases/insituGlobalArrays/insituGlobalArraysWriter.cpp
source/adios2/engine/insitumpi/InSituMPIReader.cpp
source/adios2/engine/insitumpi/InSituMPIReader.h
source/adios2/engine/insitumpi/InSituMPIWriter.cpp
source/adios2/engine/sst/SstReader.cpp
source/adios2/engine/sst/SstReader.h
source/adios2/engine/sst/SstWriter.cpp
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc

An example for retrieving arrays per write block (using selections), targeting the insitu viz folks' use case.

Insitu use case

---

source/adios2/engine/bp/BPFileWriter.cpp
source/adios2/toolkit/format/bp3/BP3Base.cpp
source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/format/bp3/BP3Serializer.cpp
source/adios2/toolkit/transport/Transport.cpp
source/adios2/toolkit/transport/file/FileFStream.cpp
source/adios2/toolkit/transport/file/FilePOSIX.cpp
source/adios2/toolkit/transport/file/FileStdio.cpp
source/adios2/toolkit/transportman/TransportMan.cpp
source/adios2/toolkit/transportman/TransportMan.h

mkdir only called from rank 0 and sync with a barrier to minimize file system calls at open

Mkdir prof fix

---

source/adios2/engine/bp/BPFileReader.tcc
source/adios2/helper/adiosMemory.h
source/adios2/helper/adiosMemory.inl
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
testing/adios2/engine/bp/operations/TestBPWriteReadSZ.cpp
testing/adios2/engine/bp/operations/TestBPWriteReadZfp.cpp

#768 fixed bug selection with operations

---

source/adios2/engine/bp/BPFileReader.tcc
source/adios2/helper/adiosType.h
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
testing/adios2/engine/bp/TestBPWriteMultiblockRead.cpp

This was showing when reading XGC files

#779 Added support for null block Write and Read

---

source/adios2/engine/sst/SstReader.h
source/adios2/engine/sst/SstReader.tcc

trying to optimize SST BP so that there is no more blocking reads.

removed all blocking transfers in SST BP

---

testing/adios2/engine/dataman/TestDataManCallback1D.cpp
testing/adios2/engine/dataman/TestDataManP2P1D.cpp
testing/adios2/engine/dataman/TestDataManP2PBzip2D.cpp
testing/adios2/engine/dataman/TestDataManP2PSz2D.cpp
testing/adios2/engine/dataman/TestDataManP2PZfp2D.cpp
testing/adios2/engine/dataman/TestDataManSubscribe1D.cpp

made dataman tests check MPI-thread avalability before running

---

source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
testing/adios2/bindings/fortran/CMakeLists.txt
testing/adios2/bindings/fortran/TestF2C_BPReadFBlocks.cpp

From Fortran (column-major writer) to C (row-major reader)
Added tests

#832 reverse block dimensions in Block info

---

source/adios2/core/Engine.cpp
source/adios2/engine/bp3/BP3Writer.cpp

Freeing aggregator comm before engine comm

---

testing/adios2/bindings/fortran/TestBPWriteReadHeatMap2D.f90
testing/adios2/bindings/fortran/TestBPWriteReadHeatMap3D.f90

Bug is fixed in recent master
Added tests for irregular 2D and 3D arrays to be written/read in Fortran
and read in C++

#855 added tests

---

source/adios2/engine/dataman/DataManReader.cpp
source/adios2/engine/dataman/DataManReader.h

added StepMode manipulating in DataMan

---

bindings/C/c/adios2_c_io.cpp
bindings/Fortran/f2c/adios2_f2c_io.cpp
testing/adios2/bindings/C/TestBPWriteTypes.cpp

added attributes in C bindings
verified with bpls2

#895 fixes C and Fortran string arrays

---

bindings/C/c/adios2_c_io.cpp
bindings/C/c/adios2_c_io.h
bindings/CXX11/cxx11/Engine.cpp
bindings/CXX11/cxx11/Engine.h
bindings/CXX11/cxx11/IO.cpp
bindings/CXX11/cxx11/IO.h
bindings/Fortran/f2c/adios2_f2c_io.cpp
bindings/Fortran/modules/adios2_io_mod.f90
bindings/Python/py11IO.cpp
bindings/Python/py11IO.h
examples/heatTransfer/read/heatRead.cpp
examples/heatTransfer/write/IO_adios2.cpp
source/adios2/core/Engine.cpp
source/adios2/core/Engine.h
source/adios2/core/IO.cpp
source/adios2/core/IO.h
source/adios2/engine/insitumpi/InSituMPIReader.cpp
source/adios2/engine/insitumpi/InSituMPIReader.h
source/adios2/engine/insitumpi/InSituMPIReader.tcc
source/adios2/engine/insitumpi/InSituMPIWriter.cpp
source/adios2/engine/insitumpi/InSituMPIWriter.h
source/adios2/engine/insitumpi/InSituMPIWriter.tcc

WIP: Move Engine::FixedSchedule() to IO::LockDefinitions()

---

source/adios2/toolkit/sst/cp/cp_common.c
source/adios2/toolkit/sst/cp/cp_reader.c
source/adios2/toolkit/sst/cp/cp_writer.c

Try a strategic delay between messages for queued timesteps

Try something that might impact the rare stuck reader problem

---

bindings/C/c/adios2_c_attribute.cpp
bindings/C/c/adios2_c_attribute.h
bindings/C/c/adios2_c_io.cpp
bindings/C/c/adios2_c_io.h
bindings/C/c/adios2_c_types.h
bindings/Fortran/f2c/adios2_f2c_io.cpp
bindings/Fortran/modules/adios2_io_define_attribute_mod.f90
bindings/Fortran/modules/adios2_parameters_mod.f90
docs/api_doxygen/C/Doxyfile
source/adios2/ADIOSMacros.h
source/adios2/core/Attribute.cpp
source/adios2/core/AttributeBase.cpp
source/adios2/core/AttributeBase.h
testing/adios2/bindings/C/TestBPWriteTypes.cpp
testing/adios2/engine/SmallTestData.h
testing/adios2/engine/bp/TestBPWriteReadAttributesADIOS2.cpp
testing/utils/TestUtilsCWriter.c

Enable attribute string value and array in C bindings

---

source/adios2/toolkit/aggregator/mpi/MPIAggregator.cpp
source/adios2/toolkit/aggregator/mpi/MPIChain.cpp
testing/adios2/engine/bp/TestBPWriteAggregateRead.cpp

Turn aggregation into parameterized tests

Handling single proc aggregation 

---

source/adios2/core/VariableBase.cpp
source/adios2/core/VariableBase.h
source/adios2/engine/bp3/BP3Writer.tcc
source/adios2/engine/sst/SstWriter.tcc
source/adios2/helper/adiosMemory.h
source/adios2/helper/adiosMemory.inl
source/adios2/toolkit/format/bp3/BP3Serializer.tcc
testing/adios2/engine/bp/TestBPLargeMetadata.cpp

Fixes a bug in reallocation
Payload moved as a helper function

#934 buffer not reallocating for large strings

---

source/utils/adios_reorganize/Reorganize.cpp

@pnorbert Found this bug while experimenting with adios_reorganize.

Fix issue where adios_reorganize hangs with MPMD launch

---

source/adios2/helper/adiosSystem.cpp
source/adios2/helper/adiosSystem.h

added a helper function for getting all available IP addresses. This could be useful for all socket based engines and transports.

added AvailableIpAddresses in helper

---

examples/hello/bpReader/helloBPReader.cpp

If the writer is run with mpirun -n 3, the reader needs
to handle it with a selection.

helloBPReader - add selection so mpirun -n 2 works.

---

docs/user_guide/source/engines/sst.rst
source/adios2/engine/sst/SstReader.cpp
source/adios2/toolkit/sst/cp/cp_internal.h
source/adios2/toolkit/sst/cp/cp_reader.c
source/adios2/toolkit/sst/cp/cp_writer.c
source/adios2/toolkit/sst/sst.h

Docs for NetworkInterface Param; Sst-internal enum for step mode; Better verbosity for SstStreamStatus

Docs, verbosity and code clarity changes

---

scripts/circle/el7-gnu7-ohpc/Dockerfile
scripts/circle/el7-gnu7-openmpi-ohpc/Dockerfile
scripts/circle/el7-intel18-ohpc/Dockerfile
scripts/circle/el7-intel18-openmpi-ohpc/Dockerfile
scripts/circle/el7/Dockerfile
scripts/circle/fedora-openmpi-ubsan/Dockerfile
scripts/circle/fedora-ubsan/Dockerfile
scripts/circle/suse-pgi-openmpi/Dockerfile
scripts/circle/suse-pgi/Dockerfile

@williamfgc once this is merged into master then the CI images will get automatically rebuilt by dockerhub (typically takes anywhere from an hour to a day for the new images to be available).  At that point we can update the circle scripts to use lfs, but not until then.

Add git-lfs to CI docker images

---

examples/heatTransfer/TestBPFileMx1.cmake
examples/heatTransfer/TestBPFileMx1_zfp.cmake
examples/heatTransfer/TestBPFileMxM.cmake
examples/heatTransfer/TestBPFileMxN.cmake
examples/heatTransfer/TestInsituMPIMx1.cmake
examples/heatTransfer/TestInsituMPIMxM.cmake
examples/heatTransfer/TestInsituMPIMxN.cmake
examples/heatTransfer/TestSSTBPMx1.cmake
examples/heatTransfer/TestSSTBPMxM.cmake
examples/heatTransfer/TestSSTBPMxN.cmake
examples/heatTransfer/TestSSTFFSMx1.cmake
examples/heatTransfer/TestSSTFFSMxM.cmake
examples/heatTransfer/TestSSTFFSMxN.cmake
source/adios2/engine/insitumpi/InSituMPISchedules.cpp
source/utils/CMakeLists.txt
source/utils/adios_iotest/CMakeLists.txt
source/utils/adios_iotest/processConfig.cpp
testing/adios2/performance/manyvars/manyVars.c
testing/utils/CMakeLists.txt
testing/utils/iotest/CMakeLists.txt

Address a number of MSVC build issues

---

cmake/FindLIBFABRIC.cmake
docs/user_guide/source/installation/cmake.rst

Change user-facing flag from LIBFABRIC_PREFIX to LIBFABRIC_ROOT

Standardized and documented LibFabric root variable for build

---

source/adios2/engine/insitumpi/InSituMPIFunctions.cpp
source/adios2/engine/insitumpi/InSituMPIFunctions.h
source/adios2/engine/insitumpi/InSituMPIReader.cpp
source/adios2/engine/insitumpi/InSituMPIWriter.cpp
source/adios2/engine/insitumpi/InSituMPIWriter.h
source/utils/adios_iotest/adiosStream.cpp
source/utils/adios_iotest/iotest-config/pipe2_04_nonblocking.txt
source/utils/adios_iotest/processConfig.cpp
source/utils/adios_iotest/processConfig.h
testing/adios2/engine/staging-common/CMakeLists.txt
testing/adios2/engine/staging-common/TestStagingMPMD.cpp

Implement timeout in InSituMPI Reader

Insitumpi timeout

---

source/adios2/operator/compress/CompressMGARD.cpp

Simple changes for initial 3D MGARD compression using L2

Added 3d MGARD support

---

bindings/C/c/adios2_c_engine.cpp
bindings/Fortran/modules/adios2_engine_get_mod.f90
bindings/Fortran/modules/adios2_engine_put_mod.f90
bindings/Fortran/modules/contains/adios2_engine_get.f90
bindings/Fortran/modules/contains/adios2_engine_get_by_name.f90
bindings/Fortran/modules/contains/adios2_engine_get_deferred.f90
bindings/Fortran/modules/contains/adios2_engine_get_deferred_by_name.f90
bindings/Fortran/modules/contains/adios2_engine_put.f90
bindings/Fortran/modules/contains/adios2_engine_put_by_name.f90
bindings/Fortran/modules/contains/adios2_engine_put_deferred.f90
bindings/Fortran/modules/contains/adios2_engine_put_deferred_by_name.f90
testing/adios2/bindings/C/SmallTestData_c.h
testing/adios2/bindings/C/TestBPWriteTypes.cpp
testing/adios2/bindings/fortran/SmallTestData_mod.f90
testing/adios2/bindings/fortran/TestBPWriteTypes.f90
testing/adios2/engine/bp/TestBPWriteAggregateRead.cpp

C and Fortran string variable values

---

source/adios2/engine/bp3/BP3Writer.cpp
source/adios2/toolkit/format/bp3/BP3Base.cpp
source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/transportman/TransportMan.cpp
source/adios2/toolkit/transportman/TransportMan.h

Adding a parameter in BP engine
All ranks will make a directory if node-local is on

#1124 addressing node-local NVMe

---

testing/adios2/engine/staging-common/CMakeLists.txt

Don't run SST tests if ADIOS2_USE_SST is off

---

scripts/developer/git/git-clang-format

inl and tcc to git-clang-format extensions

---

source/adios2/toolkit/interop/hdf5/HDF5Common.cpp
testing/adios2/bindings/python/CMakeLists.txt
testing/adios2/engine/hdf5/CMakeLists.txt
testing/adios2/engine/hdf5/TestHDF5WriteReadAttributesADIOS2.cpp
testing/adios2/engine/hdf5/TestNativeHDF5WriteRead.cpp

Added test more HDF5 attributes

---

testing/adios2/engine/bp/TestBPWriteReadBlockInfo.cpp

testing BlockSelection in GlobalArrays

---

examples/basics/localArray/localArray_write.cpp
source/adios2/core/Variable.tcc
source/utils/bpls/bpls.cpp
source/utils/bpls/bpls.h
testing/utils/TestUtilsCWriter.bplsldDav.expected.txt
testing/utils/TestUtilsCWriter.bplsldDavvv.expected.txt

This will bring release and master into sync in the git tree so that bug fixes can be easily branched off release and merged into both release and master.

Sync release into master

---

source/adios2/core/VariableBase.cpp
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc

Enable SetSelection in GlobalArrays from LocalValues

---

source/adios2/engine/sst/SstReader.cpp

@chuckatkins One more little patch before the release...

Kill error

---

source/adios2/toolkit/sst/cp/cp_reader.c

Fix a race condition that occurs when closing a stream that is reading with a BeginStep(timeout)

Fix a race condition 

---

thirdparty/KWSys/adios2sys/SystemTools.cxx

Double free seen on Ubuntu 16 with mpich when running bpls
#1259

Safe delete pointers in KWSys ClassFinalize

---

source/adios2/engine/bp3/BP3Reader.cpp
source/adios2/helper/adiosMath.cpp
source/adios2/helper/adiosMath.h
source/adios2/toolkit/format/bp3/BP3Deserializer.cpp
source/adios2/toolkit/format/bp3/BP3Deserializer.h

Addressing #1275 . Testing a large file on Titan.

Only metadata index is loaded in single bp file at Open

---

source/adios2/core/IO.tcc
testing/adios2/interface/TestADIOSDefineAttribute.cpp
testing/adios2/interface/TestADIOSDefineVariable.cpp

Remove variable and attribute bug

---

bindings/C/c/adios2_c_adios.h
bindings/C/c/adios2_c_engine.h
bindings/C/c/adios2_c_io.h
bindings/CXX11/cxx11/ADIOS.h
bindings/CXX11/cxx11/Engine.h
bindings/CXX11/cxx11/IO.h
docs/user_guide/source/introduction/nutshell.rst

MPI collectives in C++ and C bindings
What ADIOS2 is and isn't in rtd
Addressing #1268  in Doxygen API documentation in readthedocs

Added docs

---

source/adios2/toolkit/profiling/taustubs/README.md

Adding a README.md file to explain how to use the taustubs library.

Adding a README.md for the taustubs library

---

bindings/CXX11/cxx11/Engine.cpp
bindings/CXX11/cxx11/Engine.h
bindings/CXX11/cxx11/Engine.tcc
source/adios2/core/Engine.cpp
source/adios2/core/Engine.h
source/adios2/core/Engine.tcc
source/adios2/core/Variable.h
source/adios2/engine/bp3/BP3Writer.cpp
source/adios2/engine/bp3/BP3Writer.h
source/adios2/engine/bp3/BP3Writer.tcc
source/adios2/toolkit/format/bp3/BP3Serializer.tcc
testing/adios2/engine/bp/TestBPWriteReadVariableSpan.cpp

Allows filling span with a value at Put

Span value

---

source/adios2/engine/bp3/BP3Writer.cpp

Fixing Bug when mixing deferred and sync mode

---

source/adios2/helper/mpidummy.cpp
source/adios2/helper/mpidummy.h

added MPI_Allreduce in mpidummy

---

bindings/Python/py11glue.cpp
source/adios2/core/Stream.tcc
testing/adios2/bindings/python/TestBPWriteTypesHighLevelAPI.py

Added local value in Python high-level bindings

---

source/adios2/engine/bp3/BP3Reader.tcc
testing/adios2/interface/TestADIOSInterface.cpp

Test added
Addresses #1308 . Similar bug as in #1292 but on the read side.

Fixing bug in Get sync combined with Put deferred

---

source/adios2/engine/sst/SstWriter.tcc
source/adios2/toolkit/sst/cp/cp_reader.c

Problems remain on the reader side, left for next PR.

Fix a problem on the writer side with local vars.  

---

testing/adios2/interface/TestADIOSInterface.cpp

This adds a sync version of the 2 file (read -> write) test. (for completeness, that was never broken.) It then also consolidates the various tests in that file to be typed tests (see gtest).

testing: add some more multiblock / span tests

---

source/adios2/toolkit/profiling/taustubs/tautimer.cpp

Disabling sanity-check assertions that aren't true under Matlab.

---

source/adios2/engine/sst/SstWriter.cpp

Refer to issue #1320 .  Thanks @germasch !

Fix size of marshalled BP buffer

---

bindings/C/c/adios2_c_types.h
bindings/Fortran/f2c/adios2_f2c_io.cpp
bindings/Fortran/modules/adios2_parameters_mod.f90
testing/adios2/bindings/fortran/TestBPWriteTypes.f90

Local value support in Fortran bindings

---

bindings/CXX11/cxx11/fstream/ADIOS2fstream.cpp
bindings/CXX11/cxx11/fstream/ADIOS2fstream.h
bindings/CXX11/cxx11/fstream/ADIOS2fstream.tcc
bindings/Python/py11File.cpp
bindings/Python/py11File.h
bindings/Python/py11glue.cpp
source/adios2/ADIOSTypes.h
source/adios2/core/Stream.cpp
source/adios2/core/Stream.h
source/adios2/core/Stream.tcc
testing/adios2/bindings/python/CMakeLists.txt
testing/adios2/bindings/python/TestBPZfpHighLevelAPI.py
testing/adios2/engine/bp/operations/CMakeLists.txt
testing/adios2/engine/bp/operations/TestBPWriteReadZfpHighLevelAPI.cpp

Addresses #1342 
Tested with ZFP

Enable write operations in high-level Python and C++ APIs

---

bindings/CXX11/cxx11/Variable.h
docs/user_guide/source/advice/advice.rst
docs/user_guide/source/api_full/fortran.rst
docs/user_guide/source/components/components.rst
docs/user_guide/source/faq/faq.rst

Fix an error with advice file not found in components.rst
Addresses #1417

Reduce warnings in sphinx build for readthedocs

---

.readthedocs.yml
readthedocs.yml

readthedocs build currently broken
addressing #1417

updating readthedocs.yml

---

source/adios2/CMakeLists.txt
source/adios2/helper/adiosMemory.cpp
source/adios2/helper/adiosMemory.inl
source/adios2/helper/adiosMemory.tcc
source/utils/bpls/bpls.cpp

Addressing #1414 
Related to #1255 
Patch in bpls to avoid seg fault

Endian reverse bug

---

readthedocs.yml

Fix readthedocs.yml

---

source/adios2/engine/sst/SstReader.tcc

Just removing the two couts from last night's PR

remove extra printfs from SST reader code

---

bindings/C/c/adios2_c_engine.cpp
bindings/C/c/adios2_c_engine.h
bindings/CXX11/cxx11/Engine.cpp
bindings/CXX11/cxx11/Engine.h
bindings/CXX11/cxx11/fstream/ADIOS2fstream.cpp
bindings/CXX11/cxx11/fstream/ADIOS2fstream.h
bindings/Fortran/f2c/adios2_f2c_engine.cpp
bindings/Fortran/modules/adios2_engine_mod.f90
bindings/Python/py11Engine.cpp
bindings/Python/py11Engine.h
bindings/Python/py11File.cpp
bindings/Python/py11File.h
bindings/Python/py11glue.cpp
docs/user_guide/source/api_full/fortran.rst
source/adios2/core/Engine.cpp
source/adios2/core/Engine.h
source/adios2/core/Stream.cpp
source/adios2/core/Stream.h
source/adios2/engine/bp3/BP3Reader.cpp
source/adios2/engine/bp3/BP3Reader.h
source/adios2/engine/bp4/BP4Reader.cpp
source/adios2/engine/bp4/BP4Reader.h
testing/adios2/bindings/C/TestBPWriteReadMultiblock.cpp
testing/adios2/bindings/C/TestBPWriteTypes.cpp
testing/adios2/bindings/fortran/TestBPWriteTypes.f90
testing/adios2/bindings/python/TestBPWriteReadTypes.py
testing/adios2/bindings/python/TestBPWriteTypesHighLevelAPI.py
testing/adios2/engine/bp/TestBPWriteReadADIOS2.cpp
testing/adios2/engine/bp/TestStreamWriteReadHighLevelAPI.cpp

Added Steps function to inspect the available number of steps in bp file sets. Required for visualization on a step basis.

Engine steps

---

bindings/C/c/adios2_c_io.cpp
bindings/C/c/adios2_c_io.h
bindings/Fortran/f2c/adios2_f2c_io.cpp
bindings/Fortran/modules/adios2_io_mod.f90
testing/adios2/bindings/C/TestBPWriteTypes.cpp
testing/adios2/bindings/fortran/TestBPWriteTypes.f90

Get parameter in Fortran and C bindings

---

source/adios2/engine/dataman/DataManWriter.cpp

fixed an unnecessary check in dataman

---

Contributing.md
ReadMe.md
bindings/Python/py11glue.cpp
docs/user_guide/source/conf.py
docs/user_guide/source/engines/inline.rst
docs/user_guide/source/engines/sst.rst
docs/user_guide/source/installation/cmake.rst

Modified Contributing and ReadMe

Resolving readthedocs warnings

---

bindings/Fortran/f2c/adios2_f2c_io.cpp
bindings/Fortran/modules/adios2_io_mod.f90
testing/adios2/bindings/fortran/TestBPWriteTypes.f90

Check io in config file in Fortran

---

examples/heatTransfer/TestBPFileMx1.cmake
examples/heatTransfer/TestBPFileMx1_zfp.cmake
examples/heatTransfer/TestBPFileMxM.cmake
examples/heatTransfer/TestBPFileMxN.cmake
source/adios2/engine/bp4/BP4Writer.cpp
source/adios2/engine/bp4/BP4Writer.h
source/adios2/toolkit/format/bp4/BP4Base.h
source/adios2/toolkit/format/bp4/BP4Deserializer.cpp
source/adios2/toolkit/format/bp4/BP4Serializer.cpp
source/adios2/toolkit/format/bp4/BP4Serializer.tcc
source/adios2/toolkit/transport/Transport.cpp
source/adios2/toolkit/transport/Transport.h
source/adios2/toolkit/transport/file/FileFStream.cpp
source/adios2/toolkit/transport/file/FileFStream.h
source/adios2/toolkit/transport/file/FilePOSIX.cpp
source/adios2/toolkit/transport/file/FilePOSIX.h
source/adios2/toolkit/transport/file/FileStdio.cpp
source/adios2/toolkit/transport/file/FileStdio.h
source/adios2/toolkit/transport/shm/ShmSystemV.cpp
source/adios2/toolkit/transport/shm/ShmSystemV.h
source/adios2/toolkit/transportman/TransportMan.cpp
source/adios2/toolkit/transportman/TransportMan.h
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPWriteAppendReadADIOS2.cpp

Bp4 append

---

source/adios2/common/ADIOSTypes.h
testing/adios2/bindings/python/TestBPPNGHighLevelAPI.py
testing/adios2/engine/bp/operations/TestBPWriteReadBZIP2.cpp
testing/adios2/engine/bp/operations/TestBPWriteReadMGARD.cpp
testing/adios2/engine/bp/operations/TestBPWriteReadPNG.cpp
testing/adios2/engine/bp/operations/TestBPWriteReadSZ.cpp
testing/adios2/engine/bp/operations/TestBPWriteReadZfp.cpp

Fixed PNG HighLevel Python test

Replace CAPS for compression parameters

---

source/adios2/toolkit/sst/dp/rdma_dp.c

SST RDMA data plane fixes

---

source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
source/adios2/toolkit/format/bp4/BP4Deserializer.tcc
testing/adios2/engine/bp/TestBPWriteReadLocalVariables.cpp

Updating count in BP3 and BP4 deserializer
Added test

Local array read block bug

---

source/utils/bpls/bpls.cpp

Resubmit #1564 from my account

Germasch bpls warnings

---

docs/environment.yml
readthedocs.yml

Trying to pull Python module for API docs in readthedocs
[ci skip]

Conda environment in rtd

---

source/utils/adios_iotest/adios_iotest.cpp

fix #1541 Iotest return fix 

---

CMakeLists.txt
docs/user_guide/source/engines/sst.rst
docs/user_guide/source/setting_up/linking.rst

Bump version to 2.4.0

---

ReadMe.md

Add a badge about the latest version in Spack :)
https://twitter.com/axccl/status/1137414129038319622

Readme: Spack Badge

---

ReadMe.md

Update license and travis badges and remove codacy badge

---

ReadMe.md

License and docs badges

---

source/adios2/toolkit/format/bp4/BP4Serializer.cpp
source/adios2/toolkit/format/bp4/BP4Serializer.h

so that the XL compiler works with it. The generated code of the previous source segfaulted

Rewrite BP4Serializer::DeserializeIndicesPerRankThreads 

---

docs/user_guide/source/introduction/nutshell.rst

This was not recognized as a proper link by sphinx.

Stray backquote in nutshell.rst

---

source/adios2/engine/bp3/BP3Writer.cpp
source/adios2/engine/bp3/BP3Writer.h
source/adios2/engine/bp4/BP4Writer.cpp
source/adios2/engine/bp4/BP4Writer.h
source/adios2/toolkit/format/bp3/BP3Base.cpp
source/adios2/toolkit/format/bp3/BP3Base.h
source/adios2/toolkit/format/bp4/BP4Base.cpp
source/adios2/toolkit/format/bp4/BP4Base.h
source/adios2/toolkit/transportman/TransportMan.cpp
source/adios2/toolkit/transportman/TransportMan.h
testing/adios2/engine/bp/TestBPWriteReadADIOS2.cpp

Open won't block until first Write
Slow Open have been seen on Summit

Added async Open at the Transport Manager level

---

source/adios2/engine/bp4/BP4Reader.cpp
source/adios2/engine/bp4/BP4Reader.h
source/adios2/toolkit/format/bp4/BP4Base.cpp
source/adios2/toolkit/format/bp4/BP4Base.h
source/utils/adios_reorganize/Reorganize.cpp

Handle timeout in BP4 reader using the OpenTimeoutSecs parameter (as in SST). 
Use errno to distinguish between file not found error and other IO errors

Bp4 opentimeout

---

source/adios2/engine/sst/SstWriter.cpp
testing/adios2/engine/staging-common/TestCommonReadAttrs.cpp
testing/adios2/engine/staging-common/TestCommonReadR64.cpp
testing/adios2/engine/staging-common/TestCommonReadShared.cpp
testing/adios2/engine/staging-common/TestCommonServer.cpp
testing/adios2/engine/staging-common/TestCommonWrite.cpp
testing/adios2/engine/staging-common/TestCommonWriteAttrs.cpp
testing/adios2/engine/staging-common/TestCommonWriteLocal.cpp
testing/adios2/engine/staging-common/TestCommonWriteModes.cpp
testing/adios2/engine/staging-common/TestCommonWriteShared.cpp

Address issue #1633, as well as various other things.

Staging sanitize

---

scripts/circle/runOnCircle.sh

    circle: Enable oversubscribe in OpenMPI

---

testing/adios2/engine/staging-common/CMakeLists.txt
testing/adios2/engine/staging-common/ParseArgs.h
testing/adios2/engine/staging-common/TestCommonClient.cpp
testing/adios2/engine/staging-common/TestCommonRead.cpp
testing/adios2/engine/staging-common/TestCommonReadAttrs.cpp
testing/adios2/engine/staging-common/TestCommonReadF.F90
testing/adios2/engine/staging-common/TestCommonReadLocal.cpp
testing/adios2/engine/staging-common/TestCommonReadR64.cpp
testing/adios2/engine/staging-common/TestCommonServer.cpp
testing/adios2/engine/staging-common/TestCommonWrite.cpp
testing/adios2/engine/staging-common/TestCommonWriteAttrs.cpp
testing/adios2/engine/staging-common/TestCommonWriteF.F90
testing/adios2/engine/staging-common/TestCommonWriteLocal.cpp
testing/adios2/engine/staging-common/TestCommonWriteModes.cpp
testing/adios2/engine/staging-common/TestStagingMPMD.cpp
testing/adios2/engine/staging-common/TestSupp.cmake

Cleanup various things in staging-common.

Staging common cleanup

---

source/adios2/engine/sst/SstReader.cpp
source/adios2/toolkit/sst/cp/cp_internal.h
source/adios2/toolkit/sst/cp/cp_writer.c
source/adios2/toolkit/sst/cp/ffs_marshal.c
source/adios2/toolkit/sst/sst.h
testing/adios2/engine/staging-common/TestCommonRead.cpp

Test to follow SST BP marshaling fix.

Support for BlocksInfo in SST: fix for BP, implementation for FFS, add to test

---

bindings/CXX11/adios2/cxx11/Engine.tcc
bindings/CXX11/adios2/cxx11/Variable.h
bindings/CXX11/adios2/cxx11/Variable.tcc
source/adios2/core/Variable.h
source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
source/adios2/toolkit/format/bp4/BP4Deserializer.tcc
testing/adios2/engine/bp/TestBPWriteReadBlockInfo.cpp
testing/adios2/engine/bp/TestBPWriteReadMultiblock.cpp

Addressing #1679 
Add WriterID field in Variable<T>::BlockInfo

Blockinfo rank

---

examples/basics/localArray/CMakeLists.txt
examples/basics/localArray/localArray_read.cpp
examples/basics/localArray/localArray_write.cpp

Add a reading example to the localArray example - Take 3

---

bindings/CXX11/adios2/cxx11/Query.cpp
bindings/CXX11/adios2/cxx11/Query.h
examples/query/CMakeLists.txt
examples/query/READ.ME
examples/query/configs/bp4io.xml
examples/query/configs/bp4io_composite.xml
examples/query/configs/q1.json
examples/query/configs/q2.json
examples/query/test.cpp
source/adios2/CMakeLists.txt
source/adios2/core/Variable.h
source/adios2/toolkit/format/bp4/BP4Deserializer.tcc
source/adios2/toolkit/query/BlockIndex.cpp
source/adios2/toolkit/query/BlockIndex.h
source/adios2/toolkit/query/JsonWorker.cpp
source/adios2/toolkit/query/Query.cpp
source/adios2/toolkit/query/Query.h
source/adios2/toolkit/query/Query.tcc
source/adios2/toolkit/query/Worker.cpp
source/adios2/toolkit/query/Worker.h
source/adios2/toolkit/query/XmlWorker.cpp

This PR includes:
1. Adding BP4 minmax based query processing
2. Improving xml tags
3. Adding JSON interface
4. Cleaning up query bindings.

Improvements for Query API 

---

source/adios2/engine/sst/SstParamParser.cpp
testing/adios2/engine/sst/TestSstParamFails.cpp
testing/adios2/engine/staging-common/TestSupp.cmake

Add case folding to SST Boolean Param parsing.  Test this.

---

testing/adios2/bindings/C/TestBPWriteTypes.cpp
testing/examples/heatTransfer/TestBPFileMx1_zfp.cmake

Fix bad cmake include

---

source/adios2/engine/bp3/BP3Writer.cpp
source/adios2/engine/bp4/BP4Writer.cpp

Adding async open to BP4 engine

---

docs/user_guide/source/engines/dataman.rst
source/adios2/engine/dataman/DataManCommon.cpp
source/adios2/engine/dataman/DataManCommon.h
source/adios2/engine/dataman/DataManReader.cpp
source/adios2/engine/dataman/DataManWriter.cpp

This is to address the latest requirement of the KSTAR application

Added explicit one-to-one mode in DataMan

---

source/adios2/core/IO.cpp

Value is not updated in streaming mode
Fixes #973

Remove Value parameter

---

source/adios2/engine/bp4/BP4Reader.cpp
source/adios2/engine/bp4/BP4Reader.h

Re-targeting #1773 to the release branch

Bp4 fix streaming

---

source/adios2/toolkit/sst/cp/cp_common.c

Until performance concerns with JAXA are sorted.

Change ControlModule default to "select"

---

CMakeLists.txt

Don't merge until the release is ready to be tagged.

Bump version to 2.5.0

---

source/adios2/operator/compress/CompressMGARD.cpp
source/utils/CMakeLists.txt

integration with mgard 0.0.0.2

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Bug report and Feature Request Templates to help the community

Update issues templates

---

bindings/C/adios2/c/adios2_c_variable.cpp
bindings/Fortran/f2c/adios2_f2c_variable.cpp
testing/adios2/bindings/fortran/TestBPWriteTypesLocal.F90

Fortran 90 and C adios2_set_selection on local array variables

---

source/adios2/toolkit/interop/hdf5/HDF5Common.tcc
testing/adios2/engine/hdf5/CMakeLists.txt
testing/adios2/engine/hdf5/TestHDF5WriteMemorySelectionRead.cpp

Added support for storing contents specified by variable's SetMemorySelection

Mem selection support in HDF5 writer

---

source/adios2/helper/adiosXML.cpp

Parse IO transport parameters in XML config

---

thirdparty/dill/dill/CMakeLists.txt
thirdparty/dill/dill/LICENSE
thirdparty/dill/dill/arm6.c
thirdparty/dill/dill/arm6_rt.c
thirdparty/dill/dill/arm8.c
thirdparty/dill/dill/arm8_rt.c
thirdparty/dill/dill/config.h.cmake

Dill upstream

---

source/adios2/toolkit/sst/cp/cp_common.c
source/adios2/toolkit/sst/cp/cp_internal.h
source/adios2/toolkit/sst/cp/cp_reader.c
source/adios2/toolkit/sst/cp/cp_writer.c
source/adios2/toolkit/sst/dp/evpath_dp.c
testing/adios2/engine/staging-common/run_test.py.gen.in

(Not moving to ENET into production, but getting some fixes into place.)

Upstream EVPath.  ENET changes.  Verbosity.

---

source/adios2/engine/ssc/SscReader.cpp
source/adios2/engine/ssc/SscReader.h
source/adios2/engine/ssc/SscWriter.cpp
source/adios2/engine/ssc/SscWriter.h

Need the ssc engine to run multiple applications (>2). However, the original program can only communicate between the intra communicators of two applications. I add some codes to allow the commnunication among the intra communicators of multiple applications.

enable multi-apps for SSC

---

source/adios2/engine/sst/SstWriter.cpp

Reverts ornladios/ADIOS2#1934
This will be covered in a different way by a pending PR.

Revert "Fix Uninit Memory in Write Warning"

---

source/adios2/core/IO.cpp
source/adios2/engine/bp3/BP3Writer.cpp
source/adios2/engine/bp3/BP3Writer.tcc
source/adios2/engine/bp4/BP4Writer.cpp
source/adios2/engine/bp4/BP4Writer.tcc
source/adios2/toolkit/format/bp/BPBase.cpp
source/adios2/toolkit/format/bp/BPBase.h
source/adios2/toolkit/format/bp/bp3/BP3Serializer.tcc
source/adios2/toolkit/format/bp/bp4/BP4Serializer.cpp
source/adios2/toolkit/format/bp/bp4/BP4Serializer.tcc
source/adios2/toolkit/format/buffer/Buffer.cpp
source/adios2/toolkit/format/buffer/Buffer.h
source/adios2/toolkit/format/buffer/heap/BufferSTL.cpp
source/adios2/toolkit/format/buffer/heap/BufferSTL.h
testing/adios2/bindings/C/TestBPWriteTypes.cpp
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPTimeAggregation.cpp

Change BP4 memory resize function
Reset Engine smart pointer at Close
Deallocate explicitly at Close (might not be needed)
Might be related to #1891

Changes to BP memory management

---

docs/user_guide/source/api_high/python.rst

Fixed typos in python high-level api doc

---

.gitignore

Ignore files generated by readthedocs.

---

docs/user_guide/source/setting_up/source/cmake.rst

docs: clarify documentation for dependency searching

---

source/adios2/core/ADIOS.cpp
source/adios2/core/Engine.tcc
source/adios2/core/Variable.tcc

These changes fall into three categories:
- "if (m_DebugMode) throw" -> "throw"
- "if (m_DebugMode && fatal-condition) throw" -> "if (fatal-condition) throw"
- "if (m_DebugMode && cheap-check) throw" -> "if (cheap-check) throw"

Debug Mode Tweaks in core

---

bindings/Matlab/adiosopen.m

Fix Matlab bindings to support BP4 data: don't throw error if file is a

---

source/adios2/helper/adiosMath.cpp
source/adios2/helper/adiosMemory.inl
source/adios2/helper/adiosString.cpp
source/adios2/helper/adiosString.tcc
source/adios2/helper/adiosType.cpp
source/adios2/helper/adiosXML.cpp
source/adios2/helper/adiosYAML.cpp

Like #2065, these changes fall into three categories:
- "if (debugMode) throw" -> "throw"
- "if (debugMode && fatal-condition) throw" -> "if (fatal-condition) throw"
- "if (debugMode && cheap-check) throw" -> "if (cheap-check) throw"
Plus, a new category:
"if (debugMode) { do something inside a try-catch for specialized exception handling } else { do the same thing outside try-catch }" -> "do something inside a try-catch for specialized exception handling"

Debug Mode tweaks in helper

---

source/adios2/engine/bp3/BP3Reader.cpp
source/adios2/engine/bp3/BP3Writer.tcc
source/adios2/engine/bp4/BP4Reader.cpp
source/adios2/engine/bp4/BP4Writer.tcc
source/adios2/engine/inline/InlineReader.cpp
source/adios2/engine/inline/InlineReader.tcc
source/adios2/engine/inline/InlineWriter.cpp
source/adios2/engine/insitumpi/InSituMPIReader.cpp
source/adios2/engine/insitumpi/InSituMPIWriter.cpp
source/adios2/engine/skeleton/SkeletonReader.cpp
source/adios2/engine/skeleton/SkeletonWriter.cpp
source/adios2/operator/compress/CompressBZIP2.cpp
source/adios2/operator/compress/CompressBlosc.cpp
source/adios2/operator/compress/CompressMGARD.cpp
source/adios2/operator/compress/CompressPNG.cpp
source/adios2/operator/compress/CompressSZ.cpp
source/adios2/operator/compress/CompressZFP.cpp

These changes are of the form:
- "if (debugMode) throw" -> "throw"
- "if (debugMode && cheap-check) throw" -> "if (cheap-check) throw"

Debug Mode Tweaks in engine

---

source/adios2/toolkit/sst/cp/cp_writer.c
source/adios2/toolkit/sst/dp/evpath_dp.c

This eliminates the need for the TSAN suppression "race:*EvpathReadRequestHandler*".

Manage writer-side EVPath DP races.

---

source/adios2/core/VariableBase.cpp
source/adios2/toolkit/format/bp/BPBase.cpp
source/adios2/toolkit/format/bp/BPSerializer.cpp
source/adios2/toolkit/format/bp/bp3/BP3Deserializer.cpp
source/adios2/toolkit/format/bp/bp3/BP3Deserializer.tcc
source/adios2/toolkit/format/bp/bp4/BP4Deserializer.cpp
source/adios2/toolkit/format/bp/bp4/BP4Deserializer.tcc
source/adios2/toolkit/format/bp/bp4/BP4Serializer.cpp
source/adios2/toolkit/interop/hdf5/HDF5Common.cpp
source/adios2/toolkit/interop/hdf5/HDF5Common.tcc
source/adios2/toolkit/profiling/iochrono/Timer.cpp
source/adios2/toolkit/transport/Transport.cpp
source/adios2/toolkit/transport/shm/ShmSystemV.cpp
source/adios2/toolkit/transportman/TransportMan.cpp

All of these changes are of the form:
- "if (debugMode) throw" -> "throw"
- "if (debugMode && cheap-check) throw" -> "if (cheap-check) throw"

Debug Mode Tweaks in toolkit (mostly)

---

source/adios2/toolkit/sst/cp/cp_common.c
source/adios2/toolkit/sst/cp/cp_internal.h
source/adios2/toolkit/sst/cp/cp_reader.c
source/adios2/toolkit/sst/cp/cp_writer.c
source/adios2/toolkit/sst/cp/ffs_marshal.c

Warnings fixes

---

cmake/DetectOptions.cmake
scripts/ci/gh-actions/macos-setup.sh

This fixes some path calculation for python on mac

cmake: Cleanup python install dir

---

source/adios2/core/Engine.tcc
source/adios2/core/IO.cpp
source/adios2/engine/bp3/BP3Reader.cpp
source/adios2/helper/adiosMath.cpp
source/adios2/helper/adiosMath.h
source/adios2/helper/adiosMemory.h
source/adios2/helper/adiosMemory.inl
source/adios2/helper/adiosString.cpp
source/adios2/helper/adiosString.h
source/adios2/helper/adiosString.tcc
source/adios2/helper/adiosType.cpp
source/adios2/helper/adiosType.h
source/adios2/helper/adiosXML.cpp
source/adios2/helper/adiosYAML.cpp
source/adios2/operator/compress/CompressBZIP2.cpp
source/adios2/operator/compress/CompressBlosc.cpp
source/adios2/operator/compress/CompressPNG.cpp
source/adios2/operator/compress/CompressZFP.cpp
source/adios2/toolkit/format/bp/BPBase.cpp
source/adios2/toolkit/format/bp/bp3/BP3Deserializer.cpp
source/adios2/toolkit/format/bp/bpOperation/compress/BPBZIP2.cpp
source/adios2/toolkit/format/bp/bpOperation/compress/BPBlosc.cpp
source/adios2/toolkit/format/bp/bpOperation/compress/BPPNG.cpp
source/adios2/toolkit/transportman/TransportMan.cpp
source/utils/adios_reorganize/Reorganize.cpp
testing/adios2/helper/TestHelperStrings.cpp

DebugMode Cleanup in helper

---

source/adios2/engine/ssc/SscHelper.cpp
source/adios2/engine/ssc/SscReader.cpp
source/adios2/engine/ssc/SscReader.h
source/adios2/engine/ssc/SscReader.tcc
source/adios2/engine/ssc/SscWriter.tcc
testing/adios2/engine/ssc/TestSscBase.cpp

@pnorbert This should work with your application now. Let me know if there is any other problems.

added string support in SSC

---

source/adios2/engine/hdf5/HDF5WriterP.cpp
source/adios2/engine/mixer/HDFMixer.tcc
source/adios2/toolkit/interop/hdf5/HDF5Common.cpp
source/adios2/toolkit/interop/hdf5/HDF5Common.h
source/adios2/toolkit/interop/hdf5/HDF5Common.tcc
testing/adios2/engine/staging-common/CMakeLists.txt
testing/adios2/engine/staging-common/TestCommonWrite.cpp

Allow NoData for staging common for HDF (HalfNoData not applicable)

staging. common NoData for HDF5

---

source/adios2/toolkit/sst/cp/ffs_marshal.c

The FFS-encoded data buffer is created and destroyed at the control plane level, moderated by CP stream locking.  But between times it is passed to the data plane for servicing incoming read requests, where it is managed by DP-level locking.  DP only reads it, and only has access between creation and destruction, but TSAN sees fault with this because the buffer is accessed and written (freed) under different locking strategies.  To suppress these TSAN errors, we're telling TSAN to ignore the free.

TSAN exclusion in SST writer - FFS marshalling

---

source/adios2/helper/adiosComm.h
source/adios2/helper/adiosComm.inl
source/adios2/toolkit/format/bp/bp3/BP3Serializer.cpp
source/adios2/toolkit/format/bp/bp4/BP4Serializer.cpp

This makes GathervVector a bit more of a conventional gatherv.  Preparation for allowing BP to take advantage of existing SST gather functionality in EndStep.

Refactor GathervVector slightly to move the extraSpace outside

---

bindings/C/adios2/c/adios2_c_adios.cpp
source/adios2/toolkit/burstbuffer/FileDrainer.cpp
source/adios2/toolkit/interop/hdf5/HDF5Common.tcc

These have crept into `master` since PGI has no `-Werror`.

Fix CI warnings on PGI

---

source/adios2/core/Stream.tcc
source/adios2/core/VariableBase.cpp

Address #2137 
@ax3l does this work?

Cast to size_t due to error in aarch64 gcc 7.3.1

---

source/utils/adios_reorganize/Reorganize.cpp

Fix OOB access.

---

bindings/Python/py11Engine.cpp
bindings/Python/py11Engine.h
bindings/Python/py11glue.cpp
testing/adios2/bindings/python/CMakeLists.txt
testing/adios2/bindings/python/TestBPBlocksInfo.py

Added Engine::BlocksInfo call to Python bindings

---

testing/adios2/engine/staging-common/TestCommonClient.cpp
testing/adios2/engine/staging-common/TestCommonReadAttrs.cpp
testing/adios2/engine/staging-common/TestCommonReadLocal.cpp

@pnorbert Hoping to make the BP4streaming issue clearer.

Tweak write_times test in staging_common to delay failures

---

testing/adios2/engine/dataman/TestDataMan1D.cpp
testing/adios2/engine/dataman/TestDataMan2DMemSelect.cpp
testing/adios2/engine/dataman/TestDataMan3DMemSelect.cpp
testing/adios2/engine/dataman/TestDataManReaderDirectReceive.cpp
testing/adios2/engine/dataman/TestDataManWriterDoubleBuffer.cpp

changed port numbers in dataman tests

---

.travis.yml
source/adios2/toolkit/sst/dp/evpath_dp.c

Forbid transition from speculative to learned preload

---

docs/environment.yml
docs/requirements.txt

Trying to address #2243 
Might be related to michaeljones/breathe#451

Updating breathe requirements for read the docs

---

source/adios2/toolkit/interop/hdf5/HDF5Common.cpp
source/adios2/toolkit/interop/hdf5/HDF5Common.h

basically I removed the line that closes existing  group before opening a new one. Added it back

fixed error introduced from last pull request

---

testing/adios2/engine/sst/CMakeLists.txt
testing/adios2/engine/staging-common/CMakeLists.txt

Take advantage of the infrastructure from #2200 to simplify test definitions.

testing: Convert more tests to gtest_add_tests_helper

---

docs/environment.yml
docs/requirements.txt
source/adios2/toolkit/sst/dp/rdma_dp.c

Get pip explicitly from conda-forge
Trying to address #2243

Install a recent breathe from conda-forge

---

cmake/install/post/adios2-config.post.sh.in

Fix config help

---

source/adios2/CMakeLists.txt
source/adios2/engine/dataman/DataManMonitor.cpp
source/adios2/engine/dataman/DataManMonitor.h
source/adios2/engine/dataman/DataManReader.cpp
source/adios2/engine/dataman/DataManReader.h
source/adios2/engine/dataman/DataManReader.tcc
source/adios2/engine/dataman/DataManWriter.cpp
source/adios2/engine/dataman/DataManWriter.h
source/adios2/engine/dataman/DataManWriter.tcc

A lot of near-real-time decision making features that we proposed in the HBPS project will need this.

Added performance monitor in DataMan

---

source/adios2/common/ADIOSMacros.h
source/utils/bpls/bpls.cpp
source/utils/bpls/bpls.h

bpls: Minor cleanup of variable and attribute lookup

---

source/utils/adios_iotest/adios_iotest.cpp

Looks like now: 
ADIOS IOTEST App 2 total time 0.807262 seconds

Print App ID in the summary line at the end

---

examples/hello/bpTimeWriter/helloBPTimeWriter.py
source/utils/bp4dbg/adios2/bp4dbg/data.py
source/utils/bp4dbg/adios2/bp4dbg/idxtable.py
source/utils/bp4dbg/adios2/bp4dbg/metadata.py
source/utils/bp4dbg/adios2/bp4dbg/utils.py
source/utils/bp4dbg/bp4dbg.py

New PR for python3 files clean-up instead of #2227

cleaned python3 files

---

source/adios2/toolkit/sst/cp/cp_reader.c

Don't emit a warning for a failed send if we know the peer is already in shutdown, closed or failed.

Sometimes suppress warnings on failed messages

---

bindings/CXX11/adios2/cxx11/Group.h
source/adios2/core/Attribute.cpp
source/adios2/toolkit/format/bp/bp4/BP4Deserializer.cpp
source/adios2/toolkit/query/JsonWorker.cpp
source/adios2/toolkit/query/Query.tcc
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPSelectSteps.cpp

Pre-select steps for reading

---

scripts/ci/azure/macos-setup.sh

@chuckatkins Maybe not the right fix, but gets us building again.

Fix brew mac build python install problem

---

testing/adios2/bindings/python/TestBPWriteReadString.py
testing/adios2/engine/bp/TestBPSelectSteps.cpp

Python tests

---

source/adios2/toolkit/sst/dp/rdma_dp.c

Rearrange order of fabric finalize operations to avoid cleanup race condition in verbs.
Starting a new PR to replace #2522, which has a polluted commit history.

RDMA error checking and finalize reordering

---

testing/adios2/bindings/python/TestBPWriteReadString.py

Changed read function for read_string that returns a string object

Modified python test to read strings

---

source/adios2/engine/ssc/SscReader.h
source/adios2/engine/ssc/SscReader.tcc
testing/adios2/engine/ssc/CMakeLists.txt
testing/adios2/engine/ssc/TestSscString.cpp

fixed a bug in ssc for string variables

---

thirdparty/ffs/ffs/cod/cod.y
thirdparty/ffs/ffs/cod/pregen_source/Linux/cod.tab.c
thirdparty/ffs/ffs/cod/pregen_source/Linux/cod.tab.h

Fix static variable issues from #2576

FFS upstream

---

source/adios2/core/Group.cpp
testing/adios2/hierarchy/TestHierarchicalReading.cpp

DIsable some tests just to fix broken merge an get CI running

Fix for CI to get it running

---

CMakeLists.txt
cmake/DetectOptions.cmake
cmake/FindDAOS.cmake
source/adios2/CMakeLists.txt
source/adios2/toolkit/sst/CMakeLists.txt
source/adios2/toolkit/sst/dp/daos_dp.c
source/adios2/toolkit/sst/dp/dp.c
source/adios2/toolkit/transport/file/FileDaos.cpp
source/adios2/toolkit/transport/file/FileDaos.h
source/adios2/toolkit/transportman/TransportMan.cpp

This PR does the CMake mods to compile and link DAOS elements in ADIOS.  It also contains a dummy transport and a dummy data plane.  None of it is functional, but it's a starting point doesn't get compiled if DAOS isn't found, and doesn't break things if it is.

Skeletal Daos support

---

source/adios2/helper/adiosMemory.cpp

Add right type in comparison.
Fix #2700

Fix Broken Endian Reverse Compile

---

source/adios2/toolkit/zmq/zmqpubsub/ZmqPubSub.h

Closes https://github.com/ornladios/ADIOS2/issues/2709

Add missing #include <memory>

---

bindings/C/adios2/c/adios2_c_io.cpp

Closes https://github.com/ornladios/ADIOS2/issues/2727.

adios2_inquire_group_variables: Don't return early

---

bindings/C/adios2/c/adios2_c_internal.h

Closes https://github.com/ornladios/ADIOS2/issues/2734 .

Add complex types to ADIOS2_FOREACH_C_ATTRIBUTE_TYPE_1ARG

---

source/adios2/core/Operator.h
source/adios2/core/VariableBase.cpp
source/adios2/operator/callback/Signature1.cpp
source/adios2/operator/callback/Signature1.h
source/adios2/operator/callback/Signature2.cpp
source/adios2/operator/callback/Signature2.h
source/adios2/operator/compress/CompressBZIP2.cpp
source/adios2/operator/compress/CompressBZIP2.h
source/adios2/operator/compress/CompressBlosc.cpp
source/adios2/operator/compress/CompressBlosc.h
source/adios2/operator/compress/CompressLibPressio.cpp
source/adios2/operator/compress/CompressLibPressio.h
source/adios2/operator/compress/CompressMGARD.cpp
source/adios2/operator/compress/CompressMGARD.h
source/adios2/operator/compress/CompressPNG.cpp
source/adios2/operator/compress/CompressPNG.h
source/adios2/operator/compress/CompressSZ.cpp
source/adios2/operator/compress/CompressSZ.h
source/adios2/operator/compress/CompressZFP.cpp
source/adios2/operator/compress/CompressZFP.h

Fix operator bug which silently messes up BP files when it's added with an unsupported data type 

---

bindings/C/adios2/c/adios2_c_adios.cpp

Closes https://github.com/ornladios/ADIOS2/issues/2808.

Correct adios2_init_config_serial

---

source/adios2/core/Operator.cpp
source/adios2/core/Operator.h
source/adios2/operator/OperatorFactory.cpp
source/adios2/operator/OperatorFactory.h
source/adios2/operator/callback/Signature1.cpp
source/adios2/operator/callback/Signature2.cpp
source/adios2/operator/compress/CompressBZIP2.cpp
source/adios2/operator/compress/CompressBlosc.cpp
source/adios2/operator/compress/CompressLibPressio.cpp
source/adios2/operator/compress/CompressMGARD.cpp
source/adios2/operator/compress/CompressNull.cpp
source/adios2/operator/compress/CompressPNG.cpp
source/adios2/operator/compress/CompressSZ.cpp
source/adios2/operator/compress/CompressSirius.cpp
source/adios2/operator/compress/CompressZFP.cpp
source/adios2/toolkit/format/bp/bp4/BP4Deserializer.tcc

Allow nthreads parameter for blosc decompression

---

source/adios2/operator/compress/CompressMGARD.cpp

This is to ensure the compressed buffer is not larger than the original data. In some extreme cases, lossy compression algorithms may increase the data size, which causes buffer overflow problems.
If the compressed buffer is larger than the original data, it now uses CompressNull to copy the original data into the serializer buffer. This operation is transparent to engines and serializers, so it doesn't need any changes from the engine / serializer side.

check compressed buffer size for mgard

---

source/adios2/engine/bp5/BP5Reader.cpp

fix: call the SetupForStep() with the correct step value

---

examples/cuda/cudaWriteRead.cu
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPWriteReadCuda.cpp

Using continuous buffers, testing the sync and deferred modes.

Testing for BP5 using GPU buffers for read and write

---

source/adios2/core/Engine.h
source/adios2/core/Group.h
source/adios2/core/IO.h
source/adios2/core/Stream.h
source/adios2/core/VariableCompound.h
source/adios2/engine/inline/InlineReader.h
source/adios2/toolkit/format/bp/BPBase.h
source/adios2/toolkit/format/bp/bp3/BP3Deserializer.h
source/adios2/toolkit/format/bp/bp3/BP3Serializer.h
source/adios2/toolkit/format/bp/bp4/BP4Deserializer.h
source/adios2/toolkit/format/bp/bp4/BP4Serializer.h
source/adios2/toolkit/format/buffer/heap/BufferSTL.h
source/adios2/toolkit/interop/hdf5/HDF5Common.h

These declarations do not seem to do anything at all.

clean up extern template declarations

---

docs/user_guide/source/api_full/fortran.rst

Updated the Fortran documentation to include missing subroutines and other small fixes.
@MichaelLaufer Could you review this PR? Thanks.

Fortran documentation

---

.github/actions/save-context-artifacts/action.yml
.github/workflows/everything.yml
scripts/ci/gh-actions/check-branch-name.sh
scripts/ci/gh-actions/get-changed-files.sh
scripts/ci/gh-actions/run.sh

Implements the following CI features:
- Create a custom action for debugging CI workflows
- Concurrency groups for auto-cancellation
- Ensure topic branches are used for PRs
- Skip build-and-test jobs for doc-only changes
- Use CI scripts from the merged PR but build-and-test the un-merged PR

ci: New GitHub Actions CI features

---

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp

BP5Deserializer GenerateReadRequests fix rank fix

---

source/adios2/engine/ssc/SscReader.cpp
source/adios2/engine/ssc/SscReader.tcc
source/adios2/helper/adiosCommDummy.cpp
source/adios2/helper/adiosLog.cpp
source/adios2/helper/adiosLog.h
source/adios2/helper/adiosSystem.cpp
source/adios2/operator/compress/CompressBZIP2.cpp
source/adios2/operator/compress/CompressBlosc.cpp
source/adios2/toolkit/burstbuffer/FileDrainerSingleThread.cpp
source/adios2/toolkit/query/JsonWorker.cpp
source/adios2/toolkit/query/Query.cpp
source/adios2/toolkit/query/Worker.cpp
source/adios2/toolkit/query/XmlWorker.cpp
source/utils/adios_reorganize/Reorganize.cpp

fix type warning and enum conflict

---

cmake/DetectOptions.cmake
source/adios2/toolkit/format/dataman/DataManSerializer.cpp
source/adios2/toolkit/format/dataman/DataManSerializer.h

Since @chuckatkins never replies. I am going to manually try this to prevent conflicts. This was merged into release_28 in PR  #3155. It needs to be in master too as soon as possible.

Fix a template instantiation issue with GCC 10 in dataman serializer

---

docs/user_guide/source/engines/engines.rst
docs/user_guide/source/engines/plugin.rst
docs/user_guide/source/index.rst
docs/user_guide/source/operators/ZFPCompressor.rst
docs/user_guide/source/operators/encryption.rst
docs/user_guide/source/operators/operators.rst
docs/user_guide/source/operators/plugin.rst

This is based on Vicente's branch in #3161 (so it shows his commit in addition to mine). 
@chuckatkins

Add encryption operator to docs

---

bindings/C/adios2/c/adios2_c_engine.cpp
bindings/C/adios2/c/adios2_c_io.h
bindings/C/adios2/c/adios2_c_io.tcc
bindings/C/adios2/c/adios2_c_types.h

added missing open modes in C API

---

source/adios2/engine/bp5/BP5Engine.h
source/adios2/engine/bp5/BP5Reader.cpp
source/adios2/engine/bp5/BP5Reader.h
source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
source/adios2/toolkit/format/bp5/BP5Deserializer.h
testing/adios2/engine/bp/CMakeLists.txt
testing/adios2/engine/bp/TestBPReadMultithreaded.cpp

Parameter "Thread" is used to run multiple threads to serve read in PerformGets()

Bp5 read multithreaded

---

source/adios2/helper/adiosMemory.inl

closes https://github.com/ornladios/ADIOS2/issues/3244

Fix cuda build

---

cmake/FindLIBFABRIC.cmake

Fix a typo.

---

bindings/C/adios2/c/adios2_c_engine.cpp
bindings/CXX11/adios2/cxx11/Variable.tcc
examples/basics/localArray/localArray_read.cpp
examples/basics/localArray/localArray_write.cpp
examples/basics/values/values_write.cpp
source/adios2/common/ADIOSTypes.h
source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
source/utils/bpls/bpls.cpp

merge PRs #3289 and #3288 into the 2.8 release patch to fix bpls issues with local arrays

Fix bpls 28

---

source/adios2/engine/dataspaces/DataSpacesWriter.cpp

This error was introduced in #3278

fix compile error in dataspace engine

---

cmake/install/post/generate-adios2-config.sh.in

https://github.com/ornladios/ADIOS2/issues/3348

install: post install test checks for jail root builds

---

source/adios2/operator/compress/CompressMGARD.cpp

Removed the host-side memory copy in the MGARD operator as input/output buffer may resides on the GPU device

Fix MGARD operator

---

docs/user_guide/source/advanced/gpu_aware.rst

Adding info about the Kokkos backend and on how to send Kokkos::Views directly with Put/Get

Update the documentation for the GPU backend

---

docs/requirements.txt

Dependbot backports

---

cmake/install/post/generate-adios2-config.sh.in

Related https://github.com/ornladios/ADIOS2/issues/3348

test,install: paramaterize adios2_DIR

---

source/adios2/core/Engine.tcc

Allow Span in files opened for Append

---

scripts/ci/images/Dockerfile.ci-spack-ubuntu20.04-base

ci: add libcurl4 to all ubuntu images

---

thirdparty/ffs/ffs/CMakeLists.txt
thirdparty/ffs/ffs/cod/cod.l
thirdparty/ffs/ffs/cod/pregen_source/Linux/lex.yy.c

Mod CMakeLists.txt to kill warning (update min version) and modify cod.l to eliminate old code and possibly address #3742.

Upstream ffs

---

cmake/DetectOptions.cmake

cmake: correct ADIOS2_Blosc2_PREFER_SHARED behavior

---

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp

Fix local values block reading

---

source/adios2/core/Variable.tcc
source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
testing/adios2/engine/bp/TestBPWriteReadLocalVariables.cpp

Includes the master branch version of #3782 and closes #3780.

Fixup local var reading by block with test, master branch

---

cmake/install/post/generate-adios2-config.sh.in

Fix destdir install test

---

examples/simulations/gray-scott-struct/CMakeLists.txt
examples/simulations/gray-scott/CMakeLists.txt
examples/simulations/gray-scott/ReadMe.md

Change install directory of Gray scott files

Change install directory of Gray scott files

---

examples/simulations/gray-scott-struct/CMakeLists.txt
examples/simulations/gray-scott/CMakeLists.txt
examples/simulations/gray-scott/ReadMe.md

Change install directory of Gray scott files again
The directory should be in share

Change install directory of Gray scott files again

---

docs/user_guide/source/components/anatomy.rst
docs/user_guide/source/components/components.rst
docs/user_guide/source/components/variable.rst

Move useful docs from ADIOS2-examples to ADIOS2
Closes https://github.com/ornladios/ADIOS2/issues/3894.

Move useful docs from ADIOS2-examples to ADIOS2

---

docs/user_guide/source/tutorials/overview.rst

Update the tutorial with links to external tutorials

---

examples/basics/globalArray1D/decomp.c
examples/basics/globalArray1D/decomp.h
examples/basics/globalArray1D/globalArray1DRead.c
examples/basics/globalArray1D/globalArray1DWrite.F90
examples/basics/globalArray1D/globalArray1DWrite.c
examples/basics/values/values.F90
examples/basics/values/valuesWrite.cpp
source/utils/bpls/bpls.cpp

Backport  to master prs #3994 and #3980 that fixes examples and bpls.

Backport master 3980 3994

---

docs/environment.yml

Address vulnerability at: https://github.com/readthedocs/readthedocs-sphinx-search/security/advisories/GHSA-xgfm-fjx6-62mj

update readthedocs deps

---

source/adios2/engine/campaign/CampaignManager.cpp
source/utils/adios_campaign_manager/adios2_campaign_manager.py

Fixed reported issue for create/update action

Fixed campaign python script.

---

source/adios2/core/IO.cpp
source/adios2/engine/campaign/CampaignReader.cpp
source/adios2/engine/campaign/CampaignReader.h

Campaign confrig parameters can be located in the file ~/.config/adios2 in the form 
cachepath /tmp/campaign
verbose 0

Reading of campaign configuration parameters from ~/.config/adios2

---

source/adios2/engine/bp5/BP5Reader.cpp
source/adios2/toolkit/transport/file/FileHTTP.cpp
source/adios2/toolkit/transport/file/FileHTTP.h

fixes to still be able to build with gcc 4.8.2. 

---

source/adios2/engine/campaign/CampaignManager.cpp

Do not create adios-campaign/ unless there is something to record

---

.github/workflows/everything.yml

Just a simple and nice addition.

ci: add ccache job summary

---

testing/adios2/derived/CMakeLists.txt

Don't run derived test in MPI mode, it's not written for that

---

docs/user_guide/source/advanced/campaign_management.rst
docs/user_guide/source/index.rst
source/adios2/core/ADIOS.cpp
source/adios2/core/ADIOS.h
source/adios2/engine/campaign/CampaignData.cpp
source/adios2/engine/campaign/CampaignReader.cpp
source/adios2/helper/adiosString.cpp
source/adios2/helper/adiosString.h
source/adios2/helper/adiosYAML.cpp
source/utils/adios_campaign_manager/adios2_campaign_manager.py

- set ACA version to  0.1
- remove debug prints
- add doc on Campaign Management in Advanced section
- change static struct of UserOptions to class member of ADIOS class to make it work with gcc 4.8

Updates to campaign management

---

thirdparty/EVPath/EVPath/gen_interface.pl

@vicentebolea 's fixes for windows, plus untabify on gen_interface.pl.

EVPath Upstream

---

thirdparty/dill/dill/CMakeLists.txt
thirdparty/dill/dill/vm.c

Dill Upstream in release_210

---

source/adios2/engine/bp5/BP5Reader.cpp

Do Basename for storing reader profiling

---

examples/hello/bpFWriteCRead/CppReader.cpp
examples/hello/bpFWriteCRead/FReader.f90

As outlined in issue https://github.com/ornladios/ADIOS2/issues/4232, some of the examples aren't working properly and this PR is designed to fix those issues.

Fixing C++ and Fortran example to correctly read in files (not master branch this time)

---

testing/install/CMakeLists.txt

Fixes: https://github.com/ornladios/ADIOS2/issues/3775

cmake: only remove werror|wall install test

---

ReadMe.md

HERE is the rendered addition:
| Platform            | Package                                                                                                                                                    |
|---------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Summary             | [![latest packaged version(s)](https://repology.org/badge/latest-versions/adios2.svg)](https://repology.org/project/adios2/versions)                       |
| Conda               | [![Conda Version](https://img.shields.io/conda/vn/conda-forge/adios2)](https://anaconda.org/conda-forge/adios2)                                            |
| Spack               | [![Spack …

Add package matrix to readme

---

source/adios2/CMakeLists.txt

Fixes: https://github.com/ornladios/ADIOS2/issues/4284

cmake: dont set version/soversion in interface lib

---

bindings/C/adios2/c/adios2_c_io.cpp
bindings/CXX11/adios2/cxx11/IO.h
bindings/Python/py11IO.h
bindings/Python/py11glue.cpp
docs/user_guide/source/advanced/derived_variables.rst
examples/hello/CMakeLists.txt
examples/hello/bpStepsWriteReadDerived/CMakeLists.txt
examples/hello/bpStepsWriteReadDerived/bpStepsWriteReadDerived.cpp
python/adios2/io.py
source/adios2/common/ADIOSTypes.cpp
source/adios2/common/ADIOSTypes.h
source/adios2/core/IO.h
source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
testing/adios2/derived/TestBPDerivedCorrectness.cpp
testing/adios2/python/TestDerivedVariable.py

Documentation for API, build, supported operations
Example for writing and reading two derived variables, one storing the data and one storing just stats

Documentation and fixing the API for derived variables

---

docs/user_guide/source/index.rst

This was supposed to be added in #4301 
Since this PR doesn't introduce a change to the source code, the CI will not run so the requirements for this PR will not be passed (I am not able to merge skipping the requirements so someone else will have to do this)

Adding the derived variables documentation to the advance section

---

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp

This looks like a lot, but it's just adding "try {" at the beginning and this at the end:
```
catch (...)
{
std::exception_ptr ex = std::current_exception();
// if something in GenerateReadRequests threw an exception, clear the PendingGetRequests so
// it doesn't happen again (I.E. if this happened in PerformGets(), then EndStep() should
// then happen cleanly.)
PendingGetRequests.clear();
std::rethrow_exception(ex);
}
```

If there's an exception in GenerateReadRequests, clear state and rethrow

---

source/adios2/engine/campaign/CampaignData.h

Fix missing int64_t definition

---

source/adios2/toolkit/sst/cp/cp_writer.c

Hopefully address issue #4371 .

Possibly fix leak when an ondemand request comes in just before close

---

source/adios2/common/ADIOSTypes.h
source/adios2/core/ADIOS.cpp
source/adios2/core/ADIOS.h
source/adios2/core/Engine.cpp
source/adios2/core/Engine.h
source/adios2/engine/bp5/BP5Writer.cpp
source/adios2/engine/bp5/BP5Writer.h
source/adios2/engine/campaign/CampaignReader.cpp
source/adios2/helper/adiosYAML.cpp
source/adios2/helper/adiosYAML.h
source/adios2/toolkit/transport/file/FileAWSSDK.cpp
source/adios2/toolkit/transport/file/FileAWSSDK.h
source/utils/adios_campaign_manager/adios2_campaign_manager.py

We need to remove this changes for the time being to keep this release branch API/ABI compatible.
- #4189
- #4341

Prepare release branch

---

source/adios2/engine/bp5/BP5Writer.cpp

Adding more details in the json profiling output
1. type of aggregation
2. async or not
3. num of aggregators when metadata is gathered

added more details in profiling collection

---

docs/user_guide/source/components/engine.rst

Document that BP5's PerformDataWrite is collective

Added note to PerformDataWrite (it is collective)

---

source/adios2/core/Variable.h
source/adios2/toolkit/query/BlockIndex.h
source/adios2/toolkit/shm/TokenChain.h

same changes for master branch as #4415 was for 2.10

Fix for cxx23

---

readthedocs.yml

docs: update readthedocs.yml to new requirements

---

thirdparty/EVPath/EVPath/CMakeLists.txt
thirdparty/EVPath/EVPath/cm.c
thirdparty/EVPath/EVPath/cm_pbio.c
thirdparty/EVPath/EVPath/cm_transport.h
thirdparty/EVPath/EVPath/cmfabric.c
thirdparty/EVPath/EVPath/cmsockets.c
thirdparty/atl/atl/CMakeLists.txt
thirdparty/dill/dill/CMakeLists.txt
thirdparty/dill/dill/virtual.c
thirdparty/ffs/ffs/CMakeLists.txt

This includes support for very long messages.

GTKorvo Upstream

---

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp

Change approach to take the *last* shape found, rather than the first.

Fixup Shape for FlattenSteps

---

source/adios2/core/AttributeBase.cpp

Kill Modifiable info item for Attributes

---

python/adios2/stream.py
testing/adios2/python/TestStream.py

This simplify the usage of Streams with numpy arrays.

python: stream.write accept np array w/o extra args

---

source/adios2/helper/adiosNetwork.cpp
source/adios2/toolkit/sst/cp/cp_reader.c
source/adios2/toolkit/sst/cp/cp_writer.c

This addresses the security warnings listed here: https://github.com/ornladios/ADIOS2/security/code-scanning

ci: fix codeql warnings

---

bindings/Fortran/CMakeLists.txt
cmake/DetectOptions.cmake

Suppress warnings as per 2022 comment on issue #2411 
Closes @2411

Suppress persistent fortran warnings

---

source/adios2/CMakeLists.txt
source/adios2/core/IO.cpp
source/adios2/engine/timeseries/TimeSeriesReader.cpp
source/adios2/engine/timeseries/TimeSeriesReader.h
source/adios2/engine/timeseries/TimeSeriesReader.tcc
testing/adios2/engine/CMakeLists.txt
testing/adios2/engine/time-series/CMakeLists.txt
testing/adios2/engine/time-series/TestTimeSeries.cpp

… listing a series of BP/H5 files.
- Both Read and ReadRandomAccess modes are supported.
- Full paths and relative paths to other directories are allowed in each line.
- Mix of BP4, BP5 and HDF5 files are allowed.
- Stream mode only returns `end of stream` when a line starting with `--end` encountered. `--end` is not required for ReadRandomAccess mode.
- Empty lines and comments starting with `#` are ignored.
Format of the ATS file:
```
gs100.bp
gs300.bp
gs500.bp
--end--
```

New reading engine "TimeSeries" that can read .ats text file ... 

---

thirdparty/CMakeLists.txt
thirdparty/EVPath/EVPath/CMakeLists.txt
thirdparty/ffs/ffs/CMakeLists.txt

@anagainaru Please give this a shot to see if it helps building on Apple Silicon without libffi.

Dill tweaks
