source/CMakeLists.txt
This was leftover from a previous branch and has been moved into
includes.
=> Remove ADIOS.tcc from the CMakeLists.txt

cmake/FindDataMan.cmake
FindPackageHandleStandardArgs needs to be included in every find module
that the find_package_handle_standard_args is used.  I was getting
transitively included by othger find modules before but when all other
options are turned off except DataMan, it's missing.  This ensures it's
always included before calling find_package_handle_standard_args.
=> Fix FindDataMan.cmake missing include.

include/ADIOSTypes.h
This will allow for generic template functions that can deal with
complex types using thier underlying value types.  So rather than have to split definitions like:
```
template<T> T foo(const T&);
template<T> T foo(const std::complex<T>&);
```
to handle the case where an std::complex<float> should use a float
return value, you can now use a single signature:
```
template<T> TypeInfo<T>::ValueType foo(const T&);
```
=> Added a ValueType trait to TypeInfo.

CMakeLists.txt, cmake/FindADIOS1.cmake, examples/heatTransfer/read/CMakeLists.txt, examples/heatTransfer/write/CMakeLists.txt, examples/heatTransfer/write/main.cpp, examples/hello/CMakeLists.txt, examples/hello/adios1Writer/CMakeLists.txt, examples/hello/adios1Writer/helloADIOS1Writer.cpp, examples/hello/bpWriter/CMakeLists.txt, examples/hello/datamanReader/CMakeLists.txt, examples/hello/datamanWriter/CMakeLists.txt, examples/hello/hdf5Writer/CMakeLists.txt, examples/hello/hdf5Writer/helloHDF5Writer_nompi.cpp, examples/hello/timeBP/CMakeLists.txt, include/engine/adios1/ADIOS1Writer.h, source/ADIOS.cpp, source/CMakeLists.txt, source/engine/hdf5/HDF5WriterP.cpp
This creates a single ADIOS target instead of both an MPI and serial target in the same build.  This is primarily motivated by the various incompatibilities that arise when both serial and parallel versions of dependencies exist in the runtime environment at the same time.  Most HPC module environments actually explicitly prohibit this.  With this change, the MPI and serial library versions will need to be done in two separate builds.  Similarly, all the dependencies (HDF5, NetCDF, etc.) that have both a parallel and serial version available will need to use their serial version for the serial build and their parallel version for the MPI build.
=> Creat single adios target

source/adios2/ADIOS.cpp, source/adios2/ADIOS.h, source/adios2/ADIOSMPI.h, source/adios2/ADIOSMPICommOnly.h, source/adios2/CMakeLists.txt, source/adios2/core/Engine.cpp, source/adios2/core/Engine.h, source/adios2/core/Transport.cpp, source/adios2/core/Transport.h, source/adios2/core/adiosFunctions.cpp, source/adios2/core/adiosFunctions.h, source/adios2/engine/adios1/ADIOS1Reader.h, source/adios2/engine/adios1/ADIOS1Writer.h, source/adios2/engine/dataman/DataManWriter.cpp, source/adios2/engine/dataman/DataManWriter.h, source/adios2/engine/dataman/DataManWriter.tcc, source/adios2/engine/hdf5/HDF5WriterP.cpp, source/adios2/engine/hdf5/HDF5WriterP.h, source/adios2/transport/file/MPI_File.h, source/adios2/utilities/format/bp1/BP1Aggregator.cpp, source/adios2/utilities/format/bp1/BP1Aggregator.h, source/adios2/utilities/format/bp1/BP1Base.cpp, source/adios2/utilities/format/bp1/BP1Base.h
@pnorbert @williamfgc This should let us kill off mpidummy.h from public interface and restrict it to internal use only.
=> Stop mpidummy contamination

source/dataman/json.hpp
There are a few issues with this that prevent it from being accepted upstream but it's fine for how we use it.
=> Allow json.hpp to be used with gcc 4.8.5

testing/adios2/engine/bp/TestBPWriteRead.cpp
Added correct file format to look for.
Works for non-MPI and ADIOS1 compilation
=> Fix for Issue #160 TestBPWriterRead

source/adios2/helper/adiosString.cpp, source/adios2/helper/adiosString.h, source/adios2/helper/adiosXML.cpp
If file doesn't exist, continue with run
Fixed bug if space before and after "=" in: \<tag attribute1= "value1" \>"
To do: need to discuss policy for config files, xml config files still experimental
=> Makes missing xml file permissive

examples/hello/bpFlushWriter/helloBPFlushWriter.cpp, source/adios2/helper/adiosMath.inl, source/adios2/helper/adiosMemory.inl, source/adios2/toolkit/format/bp1/BP1Base.cpp, source/adios2/toolkit/format/bp1/BP1Base.h, source/adios2/toolkit/format/bp1/BP1Writer.cpp
Replace std::copy with std::memcpy in std::thread
Added threads to profiling.log
Limiting the use of threads
TO DO: 
large scale runs to enforce threads policy
adding example with SetParameters (needs to be fixed)
=> Solve Issue #171, bug when using threaded operations

examples/experimental/multistep/reader_allsteps.cpp, examples/experimental/multistep/writer_multistep.cpp, examples/hello/bpWriter/helloBPWriter_nompi.cpp, source/adios2/ADIOSTypes.h, source/adios2/core/IO.cpp, source/adios2/core/IO.h, source/adios2/toolkit/format/bp1/BP1Base.cpp, source/adios2/toolkit/profiling/iochrono/IOChrono.h, source/adios2/toolkit/transport/Transport.cpp, source/adios2/toolkit/transport/file/FileDescriptor.cpp, source/adios2/toolkit/transport/file/FilePointer.cpp, source/adios2/toolkit/transport/file/FilePointer.h, source/adios2/toolkit/transport/file/FileStream.cpp, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPWriteReadfstream.cpp, testing/adios2/engine/bp/TestBPWriteReadstdio.cpp
Checking std::ios_base::failure exceptions
IOChrono is off by default, each owner turns it on explicitly
Modified FileDescriptor and FilePointer destructors
Added Tests BPWriteRead for stdio and fstream
Removed IO AddTransport with vector (shoud have been there?) to enable
AddTransport in Tests
=> Solve Issue #180 Modified file transports to enable write loop in size > 2Gb

examples/heatTransfer/write/CMakeLists.txt, examples/heatTransfer/write/Settings.cpp, examples/heatTransfer/write/Settings.h, examples/heatTransfer/write/main.cpp
Added an extra argument to the heat transfer example to make I/O truly asynchronous using C++11 std::future and std::async. 
I can see some overlap:
sync: ./heatTransfer_write_adios2 ht2 1 1 2500 2500 500 10  --> 136 s
async : ./heatTransfer_write_adios2 ht2 1 1 2500 2500 500 10 on ---> 96 s
=> Async I/O implementation of adios Write in heat transfer examples

CMakeLists.txt, bindings/python/CMakeLists.txt, cmake/ADIOS2ConfigCommon.cmake.in, cmake/ADIOSFunctions.cmake, cmake/adios2-config.in
This adds an adios2-config shell script that will generate the necessary build flags for a non-cmake project to use ADIOS2.
Also Fixes #154
=> Add non cmake pacakge config

source/adios2/toolkit/format/bp1/BP1Writer.tcc
Missing file_index characteristic in BP1Writer metadata
=> Solves Issue #205

examples/hello/bpWriter/helloBPWriter_nompi.cpp, source/adios2/ADIOSTypes.h, source/adios2/CMakeLists.txt, source/adios2/core/ADIOS.h, source/adios2/helper/adiosFunctions.h, source/adios2/helper/adiosMPIFunctions.cpp, source/adios2/helper/adiosMPIFunctions.h, source/adios2/helper/adiosMemory.h, source/adios2/helper/adiosMemory.inl, source/adios2/helper/adiosSystem.cpp, source/adios2/helper/adiosSystem.h, source/adios2/helper/adiosXML.cpp, source/adios2/mpidummy.cpp, source/adios2/mpidummy.h, source/adios2/toolkit/capsule/Capsule.h, source/adios2/toolkit/capsule/heap/STLVector.cpp, source/adios2/toolkit/capsule/shmem/ShmSystemV.cpp, source/adios2/toolkit/capsule/shmem/ShmSystemV.h, source/adios2/toolkit/format/bp1/BP1Base.cpp, source/adios2/toolkit/format/bp1/BP1Writer.cpp, source/adios2/toolkit/format/bp1/BP1Writer.h, source/adios2/toolkit/format/bp1/BP1Writer.tcc, source/adios2/toolkit/transport/file/FilePointer.cpp, source/adios2/toolkit/transport/file/FilePointer.h, source/adios2/toolkit/transport/file/FileStream.cpp, testing/adios2/xml/TestXMLConfig.cpp, testing/adios2/xml/config2.xml
Bugs: 1) Missing binary mode in FilePointer fopen and FStream ofstream
transports was adding characters to bp files becoming corrupted.
2) Replacing reinterpret_cast of size_t to uint_64, not the same size
on Windows 64-bit
Removed some warnings generated by Visual Studio
Added static_cast for type conversions
Refactor XML reader to restore original check on single engine
conditions and eliminate warnings. Test added.
Allow ctime and fopen "not secure" warnings: now using binary fstream as
default file IO library on Windows
=> Solve Issue #211 and made changes due to Windows warnings and bugs

bindings/python/ADIOSPy.cpp, bindings/python/ADIOSPy.h, bindings/python/gluePyBind11.cpp, testing/adios2/bindings/python/CMakeLists.txt, testing/adios2/bindings/python/TestBPWriteTypes_nompi.py
Copy constructor was implicitly removed for ADIOSPy due to m_ADIOS.
PyBind11 needed the copy constructor.
m_ADIOS is now a shared pointer to avoid copy constructor removal
Separated MPI nonMPI test as ctest failed for MPI
=> Fixing Issue #216 Python bindings

source/adios2/core/ADIOS.h
Let sophisticated users turn off the debugMode flag off. This change causes that examples/basics/value and examples/basics/globalArray to throw an exception. The examples are correct. The library needs to be fixed to handle the dimension definition API correctly to make the examples work again.
=> Set debugMode to true by default.

testing/adios2/engine/adios1/TestADIOS1WriteRead.cpp, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPWriteProfilingJSON.cpp, testing/adios2/engine/bp/TestBPWriteRead.cpp, testing/adios2/engine/bp/TestBPWriteReadAttributes.cpp, testing/adios2/engine/bp/TestBPWriteReadfstream.cpp, testing/adios2/engine/bp/TestBPWriteReadstdio.cpp
Now BPWriteProfilingJSON would use a BP filename with path. Close #230 
BPWriteReadAttribute: Since collective meta generation has not landed yet, I have to use
same attribute for all processes. Ideally attribute per process
should be unique to each other for testing purpose.
=> Make all Bp engine tests able to run in parallel

testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/hdf5/CMakeLists.txt, testing/adios2/engine/hdf5/TestHDF5WriteRead.cpp
In this PR, I extend HDF5 native reader so that now hdf5 tests can read data
by selection(so called hyperslab selection in hdf5).
Close #262
=> Testing: Make hdf5 test able to run in parallel and guard BP engine tests

bindings/fortran/f2c/adios2_f2c_adios.cpp
Missing cmake FCInterface macro FC_GLOBAL for non-MPI function
=> Fix for issue #295

source/adios2/helper/adiosMPIFunctions.tcc
Older MPI version don't take const as first argument of certain functions.
=> Removing const in MPI functions first argument. Fix for Issue #309

bindings/python/ADIOSPy.cpp, bindings/python/ADIOSPy.h, bindings/python/EnginePy.h, bindings/python/IOPy.h, bindings/python/gluePyBind11.cpp
Due to some squireliness of how python headers work, we need to include
any python binding headers first, before any C library headers.  This is
contrary to the projects coding and style guidelines but necessary
since python.h will otherwise re-define core system feature macros.
=> Fix warnings from python and GNU headers.

source/adios2/engine/bp/BPFileReader.cpp, testing/adios2/engine/bp/TestBPWriteReadAsStreamADIOS2.cpp
BeginStep shouldn't return EndOfStream status after reading last step.
Heat transfer example working as expected.
Tests modified.
=> Issue #363 BPFileReader BeginStep return

source/adios2/engine/insitumpi/InSituMPIReader.cpp, source/adios2/engine/insitumpi/InSituMPISchedules.cpp, source/adios2/engine/insitumpi/InSituMPIWriter.cpp
Using Isend() was not safe, as it showed up on Titan. Now we wait to make sure the local variables don't disappear before the Isends complete. Also some counting variable was not initialized to zero at the beginning.
=> Fix insitumpi

CMakeLists.txt, CTestCustom.cmake.in
HDF5 and GoogleTest generate warning spam when built with static glibc (i.e. Cray)
=> Suppress warnings from third party dependencies

source/adios2/engine/bp/BPFileWriter.cpp, source/adios2/toolkit/format/bp3/BP3Serializer.cpp, source/adios2/toolkit/format/bp3/BP3Serializer.h
Buffer wasn't being reset so size kept increasing
Using CloseStream to avoid increasing absolute data, this was causing a
false offset.
Verified that data wasn't missing in the heat transfer example.
=> Fix for #401 missing data in BP File

source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstReader.h, source/adios2/toolkit/sst/cp/cp.c, testing/adios2/engine/sst/run_staging_test.in
Support CurrentStep(), modify array shape to match global, remove getopt in run_staging_test, patch possible race condition in Control Plane, remove contact information for writer immediately to avoid a race in testing (must change for multiple readers).
=> Various fixes and tweaks for SST

source/adios2/toolkit/format/bp3/BP3Deserializer.cpp, source/adios2/toolkit/format/bp3/BP3Deserializer.tcc
Count the number of available steps rather than assume it's equal to
the largest available step number.  This addresses issues where the step
numbers are non-consecutive and do not start at 0 (i.e. in the file
series written by XGC).
=> Fix step count in BP3 deserializer.

bindings/fortran/f2c/adios2_f2c_io.cpp, bindings/fortran/modules/adios2_parameters_mod.f90, testing/adios2/bindings/fortran/TestBPWriteTypesLocal.f90
Added adios2_null_dims parameter for shape and start of local variables in adios2_define_variable
=> Support for Fortran local variables

source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstWriter.cpp, source/adios2/toolkit/sst/CMakeLists.txt, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/dp/dp.c, source/adios2/toolkit/sst/dp/evpath_dp.c, source/adios2/toolkit/sst/sst.h, testing/adios2/engine/sst/CMakeLists.txt, testing/adios2/engine/sst/TestSstRead.cpp, testing/adios2/engine/sst/TestSstWrite.cpp
Add a better "simple evpath" dataplane than the old "dummy" dataplane.  The latter remains as an example, but the former uses sockets (rather than RUDP) for data connections, making it more useful for the WAN situation.  Create a DataTransport parameter so that we can specify the dataplane to load from the ADIOS2 level.  Add a preliminary reader-close protocol so that the writer doesn't hang forever if the reader doesn't read all the data.  Fix a race condition in writer-close that caused the reader to mess that event sometimes.
=> Sst rollup branch

cmake/FindPythonFull.cmake
The FindPythonLibNew module in pybind11 is lacking any validation of
actually finding the component's it's looking for.
Fixes #306
=> Use CMake's builtin FindPythonLibs instead of pybind11's

source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstWriter.cpp, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/sst.h
This parameter controls how the contact information is communicated between writers and readers.  Current options are File (which is how things have worked before with the Name parameter being interpreted as a filename into which to write contact information) and Screen (where contact information is written to and read from stdout and stdin respectively).
=> Add a RegistrationMethod parameter to Sst engines.  

source/adios2/engine/plugin/PluginEngine.h
I have seen this warning for long on Mac and I am now trying to fix it.
In file included from /Users/w4g/dropbox/adios2/source/adios2/core/IO.cpp:20:
/Users/w4g/dropbox/adios2/source/adios2/engine/plugin/PluginEngine.h:89:10: warning: 'DoClose' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
void DoClose(const int transportIndex = -1);
^
/Users/w4g/dropbox/adios2/source/adios2/core/Engine.h:266:18: note: overridden virtual function is here
virtual void DoClose(const int transportIndex) = 0;
^
1 warning generated.
=> fixed a compiler warning in PluginEngine

source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstReader.h, source/adios2/engine/sst/SstWriter.cpp, source/adios2/engine/sst/SstWriter.h, source/adios2/engine/sst/SstWriter.tcc, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/cp/ffs_marshal.c, source/adios2/toolkit/sst/sst.h, source/adios2/toolkit/sst/sst_data.h
by dropping code into indicated places.    This PR does not include any new functionality _per se_, but it cleans up some detritus, pushes marshaling configuration information up to the SstReader object and includes indications where code should be added to implement BP-based marshaling in SST.
=> Modify SST components to make it easy to implement BP marshalling 

source/adios2/engine/bp/BPFileWriter.cpp, source/adios2/toolkit/format/BufferSTL.cpp, testing/adios2/performance/manyvars/manyVars.c
Caused when reallocating metadata in data.
Capacity was sufficient, while size was not. 
Enforcing capacity change with reserve (expensive) before a resize
(cheap).
Also, skipping PerformPuts if there is zero deferred variables. this was
resizing the buffer before EndStep.
=> Fixed bug #478 to correctly reallocate buffer

testing/adios2/bindings/fortran/CMakeLists.txt
Place SmallTestData_mod.f90 into an object library to avoid multiple copies of
small_test_data.mod from overwriting one another in parallel builds.  CMake
should be able to handle this on it's own a bit more inteligently but at the
moment it does not so the object library approach used here is really just a
workaround but should be sufficient for what we need.
=> Fix Fortran module race condition in build of tests

bindings/C/adios2/adios2_c_FILE.cpp, source/adios2/helper/adiosType.inl, testing/adios2/engine/bp/TestBPWriteAggregateRead.cpp
Bug in CheckForNull function, missing throw
Substreams to 1 for failed tests
=> Issue #548 check for null pointer in C Fortran bindings

bindings/C/adios2/adios2_c_variable.h, bindings/fortran/f2c/adios2_f2c_variable.cpp, bindings/fortran/f2c/adios2_f2c_variable.h, bindings/fortran/modules/adios2_variable_mod.f90, source/adios2/core/VariableBase.h, testing/adios2/bindings/fortran/TestBPWriteStep.f90, testing/adios2/bindings/fortran/TestBPWriteTypesLocal.f90
Added tests
VariableBase StepsStart is 0 by default
=> Added steps inspection subroutines in Fortran

testing/adios2/performance/manyvars/manyVars.cpp
Asking for a review because I needed to completely erase the whole build directory and rebuild from scratch, otherwise the recompiled ManyVars test aborted. But built from scratch, the test (and all tests) ran fine. 
Something in Google Test gets confused otherwise. But this PR only replaces a char * with an std::string string in the test code.
=> fix an error reported by static analysis

source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstWriter.cpp, source/adios2/engine/sst/SstWriter.tcc, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/sst.h
Change SST marshaling (FFS or BP) from being controlled by two booleans to being one enumeration value.   (Jason, just cleaning this up in preparation for enabling tests.)
=> Change SST marshaling (FFS or BP) specification method

testing/adios2/engine/staging-common/CMakeLists.txt
Add test for BP marshalling by specifying engine parameters on the command line
=> Add test for BP marshalling 

examples/hello/bpWriter/helloBPSubStreams.cpp, source/adios2/engine/bp/BPFileWriter.cpp, source/adios2/engine/insitumpi/InSituMPIWriter.cpp, source/adios2/engine/sst/SstWriter.cpp, source/adios2/toolkit/aggregator/mpi/MPIAggregator.cpp, source/adios2/toolkit/aggregator/mpi/MPIAggregator.h, source/adios2/toolkit/format/bp3/BP3Base.cpp, source/adios2/toolkit/format/bp3/BP3Base.h, source/adios2/toolkit/format/bp3/BP3Serializer.cpp, source/adios2/toolkit/format/bp3/BP3Serializer.h
Refactored metadata functions for reusability (global collective and aggregator levels).
Reformulated exchange of absolute positions for updated metadata on aggregation: changed AllGather to Isend, Irecv
Removed Aggregator functions in BP3Serializer, using public member m_Aggregator functions directly in Engine.
=> Added Aggregator metadata footer for each subfile

source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/dp/evpath_dp.c, source/adios2/toolkit/sst/dp/rdma_dp.c, source/adios2/toolkit/sst/dp_interface.h, source/adios2/toolkit/sst/sst.h, source/adios2/toolkit/sst/sst_data.h
Modifications to make SST Engine parameters available to the Data Plane layer on Reader/Writer Init.  This also moves the declarations of the SST parameters to sst_data.h.
=> Modifications to make SST Engine parameters available to DP

source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstReader.h, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/sst.h, source/adios2/toolkit/sst/sst_data.h, testing/adios2/engine/sst/CMakeLists.txt, testing/adios2/engine/sst/run_staging_test.in
Cleanup of marshal method handling on the reader side to guarantee use of the writer-specified method.  Mod away from two booleans towards an enumeration of marshaling methods.  Change run_staging_test to allow argument specifications.  Add new tests specifying BP marshaling to CMakeLists.txt
=> Changes to support regression testing for BP marshalling.

source/adios2/CMakeLists.txt, source/adios2/engine/sst/SstParamParser.cpp, source/adios2/engine/sst/SstParamParser.h, source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstWriter.cpp, source/adios2/engine/sst/SstWriter.h, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/sst.h, source/adios2/toolkit/sst/sst_data.h, testing/adios2/engine/sst/CMakeLists.txt
Refactor parameter parsing in SST Engine so we're not duplicating code.  Change queue full behaviour to an enum.  Add timeouts to SST tests.
=> Refactor parameter parsing in SST Engine

source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_writer.c, testing/adios2/engine/sst/TestSstRead.cpp, testing/adios2/engine/sst/TestSstWrite.cpp, testing/adios2/engine/sst/TestSstWriteF.f90, thirdparty/EVPath/EVPath/cm.c, thirdparty/EVPath/EVPath/cm_transport.h, thirdparty/EVPath/EVPath/cmenet.c
Tweaks to SST writer side to properly deal with connection failures and timeout on reader close even in the case of abnormal reader termination.  This depends upon tweaks to the underlying enet transport to detect and report keepalive failures to evpath.
=> Sst failure handling

source/adios2/toolkit/format/bp3/BP3Serializer.cpp, source/adios2/toolkit/format/bp3/BP3Serializer.h
Only save one attribute entity in metadata from any rank.
=> #712 Reduce redundant attributes in metadata

source/adios2/engine/sst/SstReader.cpp, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/ffs_marshal.c, source/adios2/toolkit/sst/dp/evpath_dp.c, source/adios2/toolkit/sst/dp/rdma_dp.c, source/adios2/toolkit/sst/dp_interface.h, source/adios2/toolkit/sst/sst.h
Try to actually handle reader-side notification of writer failures appropriately.  No tests for this yet, but capability (actual capability for evpath_dp, placeholders for rdma_dp).   Philip, you can fill this in based on what is in the evpath_dp.c, but these mods make rdma_dp.c continue to compile without warnings.
=> Sst failure check on reader side

source/adios2/engine/sst/SstReader.cpp, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/dp/evpath_dp.c, testing/adios2/engine/sst/CMakeLists.txt, testing/adios2/engine/sst/TestSstClient.cpp, testing/adios2/engine/sst/TestSstServer.cpp, testing/adios2/engine/sst/run_multi_test.in, testing/adios2/engine/sst/run_staging_test.in
This PR adds a 60-second SST test of a "server" which periodically produces data and "clients" which join to read data for a while and are sometimes killed (to test write-side response to reader-side failures).  RNG is a factor here, so test results aren't purely deterministic.
=> Sst fix multi-connection bug

testing/adios2/engine/sst/CMakeLists.txt, testing/adios2/engine/sst/TestSstRead.cpp, testing/adios2/engine/sst/TestSstWrite.cpp
@eisenhauer I have added tests for ZFP and SZ. ZFP test worked. But the SZ test requires a larger dataset to work on, otherwise it will cause a segfault. This is a known bug of SZ library. 
I tried to add a dedicated variable for the SZ test but unfortunately I broke many other SST tests. So I had to roll back and leave this to you. You can look at the reader source code where I put a TODO label (Line 120).
=> added sst bp compression tests

examples/heatTransfer/read/heatRead.cpp, source/adios2/engine/insitumpi/InSituMPIReader.cpp, source/adios2/engine/insitumpi/InSituMPIReader.tcc
If the schedule is fixed in In-situ MPI engine, the metadata buffer received at the first timestep is kept around over the subsequent timesteps. However, `InSituMPIReader` parses the metadata buffer at every timestep.
We can reuse the parsed metadata and reduce expensive calls to: `BP3Deserializer::PerformGetsVariablesSubFileInfo()` and `BP3Deserializer::GetSubFileInfo()` .
=> Improve FixedSchedule optimization for In-situ MPI engine

source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/ffs_marshal.c, testing/adios2/engine/sst/TestData.h, testing/adios2/engine/sst/TestData_mod.f90, testing/adios2/engine/sst/TestSSTMxN.cmake, testing/adios2/engine/sst/TestSstClient.cpp, testing/adios2/engine/sst/TestSstRead.cpp, testing/adios2/engine/sst/TestSstReadF.f90, testing/adios2/engine/sst/TestSstReadF_nompi.f90, testing/adios2/engine/sst/TestSstServer.cpp, testing/adios2/engine/sst/TestSstWrite.cpp, testing/adios2/engine/sst/TestSstWriteF.f90, testing/adios2/engine/sst/TestSstWriteF_nompi.f90
This fixes a number of issues, but doesn't test as many as it should yet.  Principally, it fixes an oversight where a bit of code that is used to adjust the types of scalar variables in FFS marshaling wasn't updated to include complex types.  It turns out that this code also wasn't correctly handling doubles in some circumstances, resulting in the problems of issue 856. @tneuroth
Currently only testing scalar doubles written by rank 0.  Should extend to other types, other ranks writing, etc.
=> Sst complex2

source/adios2/toolkit/transport/file/FilePOSIX.cpp
=> Treat short reads and writes in FilePOSIX

.travis.yml, source/adios2/toolkit/sst/dp/rdma_dp.c
This conditionally provides a positive priority to the DP, if a 'valid' provider is detected by LibFabric. Valid is currently verbs, gni, and psm2. We are excluding non-RDMA transports by default because this need is covered by the EVPath DP.
=> Assign conditional priority value to RDMA DP

source/utils/adios_reorganize/Reorganize.cpp
Fixes the following error when using SST as a write method in adios_reorganize:
```
ERROR: When using the SST engine in ADIOS2, Put() calls must appear between BeginStep/EndStep pairs
```
=> Support SST as a write method in adios_reorganize

source/utils/adios_reorganize/Reorganize.cpp, source/utils/adios_reorganize/Reorganize.h
adios_reorganize --help says read/write method parameters can be specified through command line argument, but it's not implemented.
```
Usage: adios_reorganize input output rmethod "params" wmethod "params" <decomposition>
input   Input stream path
output  Output file path
rmethod ADIOS method to read with
Supported read methods: BPFile, HDF5, SST, DataMan, InSituMPI
params  Read method parameters (in quotes; comma-separated list)
wmethod ADIOS method to write with
params  Write method parameters (in quotes; comma-separated list)
<decomposition>    list of numbers e.g. 32 8 4
Decomposition values in each dimension of an array
The product of these number must be less then the number
of processes. Processes whose rank is higher than the
product, will not write anything.
Arrays with less …
```
=> Allow specifying read/write method parameters in adios_reorganize

examples/heatTransfer/TestSSTBPRDMAMxN.cmake, examples/heatTransfer/TestSSTFFSRDMAMxN.cmake, source/adios2/toolkit/sst/dp/rdma_dp.c, source/adios2/toolkit/sst/sstmpidummy.h
Use the mpi dummy functions in the RDMA DP if we don't have real MPI available.
=> Add support for no MPI build for RDMA DP

testing/adios2/engine/sst/TestSstReadF.f90
Fixes the following error:
```
"/ccs/home/keichi/ADIOS2/testing/adios2/engine/sst/TestSstReadF.f90", 
line 50.27: 1513-041 (S) Arguments of the wrong type were specified for the
INTRINSIC procedure "modulo".
```
=> Fix type error when compiling with IBM XL compiler on Summit

CTestCustom.cmake.in
@eisenhauer @philip-davis These tests will still run on the command line via `ctest -R` but by adding then to CTestCustom exclusion then they will be ignored by the automated CI scripts.  When they are able to be reliably enabled again, please remove them from this list.
=> Disable the currently flaky tests from running in CI dashboards

thirdparty/EVPath/EVPath/CMakeLists.txt
This should eliminate the configure warning on the PGI builds
=> Bump evpath

source/adios2/toolkit/format/bp3/BP3Serializer.cpp
This is a performance bug. Before being fixed, the complexity of generating the collective metadata indices is n^2, where n is the number of writers. Now the complexity is n.
=> fixed the bp3 serializer bug in AggregateCollectiveMetadataIndices function

bindings/CXX11/cxx11/ADIOS.h
This commit consistently disallows copy construction and assignment, but
allows move construction and move assignment in adios2's cxx11 interface.
adios2's cxx11 interfaces deletes the copy constructor to guard against
accidentally creating a copy of the ADIOS object. Unfortunately that also
disallows the syntax
```cxx
auto ad = adios2::ADIOS(comm, ...);
```
which is otherwise equivalent to 
```cxx
adios2::ADIOS ad(comm, ...);
```
While admittedly minor, it's a bit inconvenient for someone used to the former way. It's also inconsistent that the copy constructor is deleted, but copy assignment is allowed, so copies can be generated after all:
```cxx
adios2::ADIOS ad;
adios2::ADIOS ad2 = ad;
```
will give an error, but
```cxx
adios2::ADIOS ad;
adios2::ADIOS ad2;
ad2 = ad;
```
will succeed. …
=> adios2: consistent copy/move constructors and assignment

source/adios2/toolkit/sst/dp/rdma_dp.c
For the RDMA data transport in SST, do not automatically choose an interface using the IB Verbs provider if it has no source address.
=> Verbs Interface Validation

bindings/C/c/adios2_c_attribute.cpp, bindings/C/c/adios2_c_engine.cpp, bindings/C/c/adios2_c_internal.h, bindings/C/c/adios2_c_internal.inl, bindings/C/c/adios2_c_io.cpp, bindings/C/c/adios2_c_types.h, bindings/C/c/adios2_c_variable.cpp, bindings/Matlab/adiosopenc.c, bindings/Matlab/adiosreadc.c, source/adios2/ADIOSMacros.h, testing/utils/TestUtilsCWriter.bplsla.expected.txt, testing/utils/TestUtilsCWriter.bplsldDav.expected.txt, testing/utils/TestUtilsCWriter.bplsldDavvv.expected.txt, testing/utils/TestUtilsCWriter.c
Originally, this work had meant to do the same kind of type mapping as the cxx11 interface, that is,
map, e.g., `adios2_type_unsigned_long_long` and `adios2_type_unsigned_long` (on Mac/Linux-64) to the same underlying `uint64_t` for core adios2.
That part is actually not needed anymore, since in master those primitive variable based types are mostly gone. So this is mostly some cleanup and consistency improvements.
* fix the Matlab interface which got broken by changes in master that removed the primitive adios2_types (untested, though, and it looks like the CI doesn't build it, either.)
* remove 'adios2_type_{un,}signed_char`, since all the other primitive types are already gone
* get rid of the type-string to adios_type maps, which were at least slightly broken because of a hardcoded …
=> C bindings fixes / updates

CMakeLists.txt, cmake/install/CMakeLists.txt, cmake/install/generate-adios2-config.sh.in
=> Make generation of adios2-config work without Fortran enabled

docs/user_guide/source/engines/sst.rst, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/dp/dp.c
Tweak SST Data transport so that if a transport is unavailable, we don't use it even if preferred.  Set SST Control transport to default to sockets.  Establish nicer aliases for Control transports.  Document control transport specification.
=> SST transport specification changes.

CMakeLists.txt
This will help ensure that installed package configs are backwards compatible with older CMake versions that what we were build with.
=> Always use language specific features for gcc, intel, and clang

source/adios2/toolkit/format/bp3/BP3Base.h, source/adios2/toolkit/format/bp3/BP3Base.inl, source/adios2/toolkit/format/bp3/BP3Base.tcc, source/adios2/toolkit/format/bp3/BP3Deserializer.cpp, source/adios2/toolkit/format/bp3/BP3Deserializer.tcc, source/adios2/toolkit/format/bp3/BP3Serializer.cpp, source/adios2/toolkit/format/bp3/BP3Serializer.tcc, source/adios2/toolkit/format/bp4/BP4Base.h, source/adios2/toolkit/format/bp4/BP4Base.inl, source/adios2/toolkit/format/bp4/BP4Base.tcc, source/adios2/toolkit/format/bp4/BP4Deserializer.cpp, source/adios2/toolkit/format/bp4/BP4Deserializer.tcc, source/adios2/toolkit/format/bp4/BP4Serializer.cpp, source/adios2/toolkit/format/bp4/BP4Serializer.tcc, source/adios2/toolkit/interop/hdf5/HDF5Common.cpp, source/adios2/toolkit/interop/hdf5/HDF5Common.tcc
I'm continuing my quest to explicitly use only stdint-based types in core and below.
This series updates format/bp3, format/bp4 and interop/hdf5 correspondingly, while also avoiding
a good amount of repetitiveness by using ADIOS2_FOREACH_....
diffstat speaks for itself: `16 files changed, 321 insertions(+), 1412 deletions(-)`  ;)
=> More stdint-type updates

source/adios2/core/IO.cpp
That originated as copy&paste error, I presume.
=> fix a bug in RemoveAttribute that accidentally uses GetVariableMap

source/adios2/toolkit/interop/hdf5/HDF5Common.cpp, source/utils/bpls/bpls.cpp, testing/adios2/engine/hdf5/TestNativeHDF5WriteRead.cpp
In an unrelated PR, I had to use clang's address sanitize, and when running the test suite, a whole bunch of other tests then failed. Fortunately, there were actually relatively few bugs underlying the many failures.
I'd consider adding an address sanitizer to the list of automated builds/checks -- looks like you already have some ubsan, so should be similar.
All of these triggered in the existing test suite, and are shown to be gone by the existing test suites, so new tests are added.
=> fix bugs exposed by address sanitizer

source/adios2/toolkit/format/bp3/BP3Base.tcc, source/utils/bpls/bpls.cpp
enable reading statistic_cnt from adios1 generated files
bpls to catch exceptions
tested outside CI with external file
=> Enable reading adios1 files with statistics_cnt

source/adios2/core/ADIOS.cpp, source/adios2/core/ADIOS.h, source/adios2/helper/mpidummy.cpp, source/adios2/helper/mpidummy.h, testing/adios2/interface/CMakeLists.txt, testing/adios2/interface/TestADIOSInterface.cpp
Also came from an unrelated discussion. ADIOS2 MPI_Comm_dup()s its communicators, but potentially too late to protect from the user doing stupid things.
The first commit adds a test that triggers it. The 2nd commit is the simple fix.
=> mpi_comm_dup from the beginning

examples/hello/bpWriter/helloBPWriter.py, examples/hello/bpWriter/helloBPWriter_nompi.py
This addresses the immediate problem in #1233, but not the fact that
even with wrong arguments, the python interface shouldn't crash
completely.
=> fix helloBPWriter Python example

bindings/Python/py11IO.cpp, bindings/Python/py11IO.h, bindings/Python/py11glue.cpp, examples/hello/bpReader/helloBPReaderHeatMap2D.py, testing/adios2/bindings/python/CMakeLists.txt, testing/adios2/bindings/python/TestBPWriteRead2D.py
This fixes the issues from #1246.
* fix arg order in helloBPReaderHeatMap2D.py
* fix the `IO::Open(..., MPI_Comm)` to actually use the passed comm (it was just using the comm from m_IO)
* add that function to the interface and correctly translate the communicator
I don't think this is the prettiest possible way of doing things, but it works for now (for me, anyway)
=> WIP: Python fixes

bandit.yml
This is subject to the outcome of the discussion in #1248 -- me being curious to see whether this actually works to make the otherwise failing `master` branch pass checks.
=> tell codacy / bandit to accept assert in python

source/adios2/helper/adiosMemory.cpp
CopyPayloadStride was using ADIOS2_FOREACH_PRIMITIVE_TYPE_1ARG, which
includes non-stdint types like char, for which GetType<> isn't
specialized anymore.
Fixing that to use ADIOS2_FOREACH_PRIMITIVE_STDTYPE then kinda exposes
another bug, ie., ~~some functions in adiosMemory.inl aren't actually
declared inline and relied on being instantiated through their use
in CopyPayloadStride~~. I added an explicit instantiation for
CopyEndianReverse which makes everything work for me, but that's not
really a clean fix.
=> Fixes #1253 (master broken with Endian_Reverse)

bindings/Python/py11ADIOS.cpp, bindings/Python/py11ADIOS.h, bindings/Python/py11IO.cpp, bindings/Python/py11IO.h, bindings/Python/py11glue.cpp, bindings/Python/py11types.h
Since I'm at it, let's dump on more PR here. This one is on top of #1247, so shouldn't be considered before that one has been worked out.
This PR adds a pybind11 caster to make passing MPI4PY communicators much simpler. It also converts
`ADIOS` back into an actual Python object, rather than a fake-constructor that returns a `py11_ADIOS` object.
=> Python cleanup

bindings/Fortran/CMakeLists.txt, bindings/Fortran/f2c/adios2_f2c_attribute.cpp, bindings/Fortran/f2c/adios2_f2c_io.cpp, bindings/Fortran/f2c/adios2_f2c_operator.cpp, bindings/Fortran/f2c/adios2_f2c_variable.cpp, bindings/Fortran/modules/adios2_adios_mod.f90, bindings/Fortran/modules/adios2_attribute_mod.f90, bindings/Fortran/modules/adios2_functions_mod.f90, bindings/Fortran/modules/adios2_io_mod.f90, bindings/Fortran/modules/adios2_operator_mod.f90, bindings/Fortran/modules/adios2_variable_mod.f90, testing/adios2/bindings/fortran/TestBPWriteReadAttributes.f90, testing/adios2/bindings/fortran/TestBPWriteTypes.f90
This PR demonstrates how strings can now be safely passed through to the Fortran API. (Though the implementation is not exactly pretty. But it's that's at least not visible on the interface side.)
There are right now 6 function in the C API that "return" strings (ie, copy them into preallocated buffers).
* `adios2_variable_name`
* `adios2_attribute_name`
* `adios2_engine_type`
* `adios2_operator_type`
* `adios2_variable_type_string`
* `adios2_attribute_type_string`
Only the very first one is actually interfaced into Fortran right now, but wasn't tested. 
For the next 3, part of the Fortran API implementation exist, but it is not complete.
For the final 2, there is no trace of them in the Fortran API binding.
[Off-topic here, but I think the last 2 functions should be deleted from the C …
=> pass strings safely to Fortran bindings

testing/adios2/bindings/C/TestBPWriteTypes.cpp, testing/adios2/interface/TestADIOSInterface.cpp
This tests IO::Open, Engine::Name, Engine::Type, IO::EngineType, using both CXX11 and C bindings.
The C bindings tests are somewhat incomplete, as two CXX11 functions are missing, so I left those out.
In the last two commits (so they can be dropped if needed), I added CXX11 and C API functions for `core::IO::GetEngine`, which allows to get a handle to an existing Engine by name. There's no chance anything gets broken because these are additions, but there is of course a valid question as to whether those are needed. I'm generally not much of a fan for recovering handles by name where one could have just saved the handle, but ADIOS2 generally allows to replace the name for a handle in many places, I suppose a a convenience in particular for people using the Fortran interface. If this gets …
=> add some tests for C/CXX11 bindings for IO/Engine

bindings/C/c/adios2_c_internal.h, source/adios2/ADIOSTypes.inl, source/adios2/core/IO.cpp
Doesn't change any actual code, just comments
=> three small comment fixes

bindings/C/c/adios2_c_attribute.cpp, bindings/C/c/adios2_c_engine.cpp, bindings/Python/py11Attribute.cpp, bindings/Python/py11File.cpp, examples/hello/datamanReader/DataManCallbackReceiver.cpp, source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstWriter.cpp, source/adios2/toolkit/interop/hdf5/HDF5Common.cpp
Sometimes we use `GetType<std::string>`, sometimes just `"string"`. The code generally uses `GetType<T>()` instead of hardcoded strings for the other types, so this patch consistently does the same for strings.
Also fixes one external use from `helper::GetType` to `GetType`.
=> use GetType<std::string> consistently

bindings/C/c/adios2_c_engine.cpp, bindings/C/c/adios2_c_engine.h, bindings/Fortran/modules/adios2_attribute_mod.f90, bindings/Fortran/modules/adios2_io_mod.f90, bindings/Fortran/modules/adios2_operator_mod.f90, bindings/Fortran/modules/adios2_variable_mod.f90, testing/adios2/bindings/C/TestBPWriteTypes.cpp, testing/adios2/bindings/fortran/CMakeLists.txt, testing/adios2/bindings/fortran/TestAdios2BindingsFortranIO.f90, testing/adios2/interface/TestADIOSInterface.cpp
This still covers only a small piece of Engine-related IO functionality, though it was enough to find a bug in the Fortran bindings: When returning strings of 0 length from C to Fortran, the old code
would leave the Fortran string in deallocated state, which leads to a crash when checking its content. Fortunately, Fortran allows for 0-size allocated arrays/strings, so the fix is to return just that.
This PR also adds `adios2_engine_name()` to the C and Fortran APIs, as the same functionality exists in the CXX11 API.
=> more testing of IO/Engine functionality and a fix for the Fortran bindings

bindings/C/c/adios2_c_engine.cpp, bindings/CXX11/cxx11/Engine.cpp, bindings/CXX11/cxx11/Engine.h, bindings/CXX11/cxx11/Engine.tcc, bindings/CXX11/cxx11/Variable.cpp, bindings/CXX11/cxx11/Variable.h, bindings/Python/py11Engine.cpp, source/adios2/ADIOSMacros.h, source/adios2/core/Engine.cpp, source/adios2/core/Engine.h, source/adios2/core/Engine.tcc, source/adios2/core/Variable.cpp, source/adios2/core/Variable.h, source/adios2/core/Variable.tcc, source/adios2/engine/bp3/BP3Reader.h, source/adios2/engine/bp3/BP3Writer.cpp, source/adios2/engine/bp3/BP3Writer.h, source/adios2/engine/bp3/BP3Writer.tcc, source/adios2/toolkit/format/bp3/BP3Serializer.cpp, source/adios2/toolkit/format/bp3/BP3Serializer.h, source/adios2/toolkit/format/bp3/BP3Serializer.tcc, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPWriteReadVariableSpan.cpp
This PR exposes pre-allocated buffer memory to the app so it can be filled out.
Addresses several issues for write use-cases:
1. Avoid buffer duplication if application is memory-bound
2. Reduce the number of sub-block metadata by pre-allocating larger block memory in adios2 which is exposed to the app as in #1165
3. Allow for non-contiguous data to populate the contiguous buffer data directly (e.g. MFEM nodes in element) without the need of temporaries
Will explore Read use-cases (single buffer for streaming engines) in future PRs.
=> adios2::Variable<T>::Span to access internal BP3 buffer memory 

testing/adios2/interface/TestADIOSInterface.cpp
I put this here not because I want it merged, but because it shows a bug. 
This isn't a proper automated test, as it requrires manual bpls afterwards
to see the issue.
See #1292 .
=> testing: expose a bug

source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/cp_writer.c
Modify SST writer to deal with the ReleaseTimestep race differently, eliminating an MPI_Barrier()
=> Modify SST writer to deal with the ReleaseTimestep race differently

source/adios2/core/IO.cpp, source/adios2/engine/sst/SstWriter.cpp, source/adios2/toolkit/format/bp3/BP3Serializer.cpp, source/adios2/toolkit/format/bp4/BP4Serializer.cpp, source/adios2/toolkit/format/dataman/DataManSerializer.cpp
For background, see #1193 .
I had suggested a fix in PR #1267, which was rejected. @williamfgc then fixed it himself in #1278, except that that fix only fixed part of the issue. (I.e., it made sure that indices would be unique even after the variable is removed from the 2nd level map, but still failed to actually do the removal.)
As I already said before, @williamfgc's fix for the uniqueness issue was clearly better than mine.
I can't help but point out, though, that the I don't agree with the contention that making data types that wrap STL containers is categorically a bad idea. Specifically, if one were to wrap these data types, one could prevent bugs where a data structure is mistakenly copied in its entirety when taking a reference was intended (by deleting the copy constructor). This …
=> fix IO::RemoveVariable/Attribute

CMakeLists.txt
This commit allows installed adios2 executables to find its
dependencies properly on osx.
Close #1220
=> Fix the missing install name dir on osx

bindings/Matlab/adiosopenc.c
I made this WIP, because I can't test it, so it's not even compile-tested.
Other than that, it's very straightforward, getting rid of the hardcoded 4096 character limit for variable/attribute names and instead using buffers sized for the actual length.
=> MATLAB: use adios2_{variable,attribute}_name() safely

source/utils/adios_iotest/adios_iotest.cpp, source/utils/adios_iotest/iotest-config/pipe2_06_busy.txt, source/utils/adios_iotest/processConfig.cpp, source/utils/adios_iotest/processConfig.h
Busy continuously checks the high resolution clock until enough time has elapsed. I think this might be nice to emulate potential CPU interference from the user app on a node.
=> Added busy command for adios_iotest

source/adios2/toolkit/interop/hdf5/HDF5Common.cpp, source/adios2/toolkit/interop/hdf5/HDF5Common.h, source/utils/bpls/bpls.cpp
Added Chunk option. Example:
<parameter key="H5ChunkDim" value="4 4"/> 
<parameter key="H5ChunkVars" value="T"/> 
If you do not specify H5ChunkVars, it applies to all vars.
=> added ChunkSupport for h5

source/adios2/toolkit/sst/dp/rdma_dp.c, source/utils/adios_iotest/settings.cpp
This avoids an occasional crash at user program exit due to pending interface operations.
=> Close domain and fabric when finalizing RDMA dataplane

source/adios2/ADIOSMacros.h
The iterator class is defined via the macro `ADIOS2_CLASS_iterator`.  The define ends with a semicolon.  When the symbol is used in source code,  the developer will add a semicolon after the symbol as is done for most code.  This will result in a warning from some compilers about a double semicolon on that line (one from macro, one from line of code)
=> Remove semicolon from macro define

bindings/CXX11/cxx11/Engine.cpp, bindings/CXX11/cxx11/Engine.h, bindings/CXX11/cxx11/Engine.tcc, testing/adios2/engine/bp/TestBPWriteReadVariableSpan.cpp
Separate Variable<T>::Span Put into two
Add single value Put in Span test
This doesn't break or changes current functionality, just fixes a broken
signature
found in #1322
=> Resolving Put ambiguity

source/utils/bpls/bpls.cpp
This attempts an alternate fix to the issue encountered in #1364.
I think that using new style initialization {} was legal in this context,
but I might be wrong. Let's see whether the compiler is happier with the
alternate style.
This isn't actually tested on the compiler that's giving the trouble, so hopefully @chuckatkins can o that.
=> workaround xl-16 compiler bug(?)

CMakeLists.txt
Inadvertently entered configuration option line twice, which is resulting in some cmake output being duplicated.
=> Fixes duplicate entry of configuration options

source/adios2/toolkit/format/bp3/BP3Serializer.tcc
Crashes with gcc7 in Release Mode
Addresses #1437
=> Replacing std::fill_n with explicit loop

CMakeLists.txt
=> cmake: restrict rpath handling to shared library builds

source/adios2/engine/bp3/BP3Writer.cpp, source/adios2/engine/bp4/BP4Writer.cpp, source/adios2/helper/adiosMPIFunctions.h, source/adios2/helper/adiosMPIFunctions.tcc, source/adios2/toolkit/aggregator/mpi/MPIAggregator.cpp, source/adios2/toolkit/aggregator/mpi/MPIAggregator.h, source/adios2/toolkit/aggregator/mpi/MPIChain.cpp, source/adios2/toolkit/aggregator/mpi/MPIChain.h
Refactor MPI Aggregation
Separate recv from send requests and checks
Addressing #1433
=> Allow Isend Irecv 64-bit data sizes in batches

source/adios2/helper/mpidummy.cpp
Fix maximum buffer size and warning
```
"could not gather data" directive output truncated writing
22 bytes into a region of size 5 [-Wformat-truncation]
```
=> mpidummy: proper size in snprintf

bindings/CXX11/cxx11/Attribute.cpp, bindings/CXX11/cxx11/Attribute.h, bindings/CXX11/cxx11/Engine.cpp, bindings/CXX11/cxx11/Engine.h, bindings/CXX11/cxx11/IO.cpp, bindings/CXX11/cxx11/IO.h, bindings/CXX11/cxx11/Operator.cpp, bindings/CXX11/cxx11/Operator.h, bindings/CXX11/cxx11/Variable.cpp, bindings/CXX11/cxx11/Variable.h, bindings/CXX11/cxx11/Variable.tcc, docs/user_guide/source/api_full/cxx11.rst, source/adios2/ADIOSTypes.cpp, source/adios2/ADIOSTypes.h, source/adios2/ADIOSTypes.inl, source/adios2/CMakeLists.txt, testing/adios2/interface/TestADIOSInterface.cpp
Since I guess #1328 become rather complicated, which I suppose may be why it's been sitting out there, I figured I'll redo just the major part of it. For detailed discussion, #1328 might still provide a useful reference.
I've had this sitting around for a while, and let me start by saying that I don't have strong feelings about it. It adds a somewhat neat feature making it easier to give human-readable output for some enums, but it could also be considered rarely needed bloat.
Essentially, the PR adds `adios::tostring` and overloads for the ostream `operator<<` for enum classes.  It allows you to do, e.g., 
```cxx
std::cout << variable.ShapeID() << std::endl;
```
and get human readable output.
It gets picked up by googletest, so on an (intentionally failing) test, instead of
``` …
```
=> add easy ToString / ostream output for adios2 enums and cxx11 interface classes

bindings/C/c/adios2_c_types.h
It needs to be static to avoid multiple definition of the symbol errors
when including the C interface in multiple source files.
=> fix adios2_local_value_dim

source/adios2/helper/adiosMPIFunctions.tcc, source/adios2/toolkit/aggregator/mpi/MPIChain.cpp
Saturates aggregation bandwidth
Fixing #1433
=> Allow 64-bit count Isend Irecv

source/adios2/helper/mpidummy.cpp
The mpidummy implementation of `MPI_Reduce` didn't do the right thing, and doing the right thing actually makes it simpler.
=> mpidummy: fix MPI_Reduce

bindings/CXX11/cxx11/Variable.cpp, bindings/CXX11/cxx11/Variable.h, bindings/CXX11/cxx11/Variable.tcc, source/adios2/ADIOSMacros.h, source/adios2/core/Variable.cpp, source/adios2/core/Variable.h, source/adios2/core/Variable.tcc
This is basically all cleanup only. The one API change is that `cxx11::Span` and `core::Span` become top-level classes (ie, not nested within `Variable`). That is for two reasons:
* So that `core::Span` can be forward declared and hence directly used in the pimpl-type `cxx11::Span` without resorting to `reinterpret_cast`.
* So that the `Spans` can be defined / instantiated as a whole class, rather than being all specialized by a macro loop for each type. 
There is no user-visible change, except that `Span` is now also available as `adios2::Span<T>` in addition to `adios2::Variable<T>::Span`, which I'd argue makes life a bit easier. But if you want avoid polluting of the `adios2` namespace, it could be moved to `adios2::detail`.
The patch does remove `Span::rbegin` and `Span::rend` because …
=> Some template-related cleanup for Span

bindings/Python/py11ADIOS.cpp, bindings/Python/py11ADIOS.h, bindings/Python/py11glue.cpp
We rely on this trick to work in the type caster:
```
// Import mpi4py if it does not exist.
if (!PyMPIComm_Get)
{
if (import_mpi4py() < 0)
{
throw std::runtime_error(
"ERROR: mpi4py not loaded correctly\n"); /* Python 2.X */
}
}
```
=> Fix python bindings for unified serial and parallel library

source/adios2/toolkit/sst/cp/cp_writer.c
Fixed missing start/stop calls for two timers in the SST metadata code.  When these are mismatched, it causes TAU to abort when profiling/tracing ADIOS.
=> Fixing mismatched instrumentation in SST layer

source/utils/bpls/bpls.cpp, source/utils/bpls/bpls.h
An example where bpls is using data structures directly to do something that is not available in the public API. A refactoring would bring out issues with the public API.
=> Calculate and use absolute step instead of relative step where necessary

bindings/Python/py11glue.cpp
The `__version__` attribute is a standardized and recommended attribute for Python modules ([PEP 396](https://www.python.org/dev/peps/pep-0396)). It also comes in very handy to check if one imported a suitable minimum version. These versions
should be strings.
```python
import adios2
print(adios2.__version__)
```
In case we want to add suffixes, such as release candidate identifiers, please be aware of the specifics in [PEP440](https://www.python.org/dev/peps/pep-0440).
Examples:
```
X.YaN    # Alpha release
X.YbN    # Beta release
X.YrcN   # Release Candidate
X.Y      # Final release
X.Y.devN # Development release
```
=> Python Module: __version__

docs/user_guide/source/api_full/fortran.rst, testing/adios2/bindings/C/TestBPWriteAggregateReadLocal.cpp, testing/adios2/bindings/C/TestNullWriteRead.cpp, testing/adios2/bindings/fortran/TestBPWriteMemorySelectionRead2D.f90, testing/adios2/bindings/fortran/TestBPWriteMemorySelectionRead3D.f90, testing/adios2/bindings/fortran/TestBPWriteTypes.f90, testing/adios2/bindings/fortran/TestBPWriteTypesByName.f90, testing/adios2/bindings/fortran/TestBPWriteTypesLocal.f90, testing/adios2/bindings/fortran/TestNullEngine.f90
At one point, before timeout was implemented anywhere, 0.0 was thought to be a good choice to mean no timeout, or blocking.  Turns out 0.0 more naturally means "poll and return immediately if no data".  So, a negative timeout means "blocking".  By convention we're using -1.0, but anything negative would work.
=> Fix places where 0.0 was used as a timeout in BeginStep

source/adios2/engine/sst/SstReader.tcc
This PR fixes a data corruption bug that happens in SST+BP when streaming across machines with different endianness. SstReader bypasses BP3Deserializer if input and output are contiguous memory, but that won't work if the endianness doesn't match.
I've tested the PR on a VM (qemu-ppc64-user) and Fujitsu FX100.
=> Fix endian reverse in SST+BP

bindings/CXX11/cxx11/Variable.h, source/adios2/toolkit/format/bp3/BP3Deserializer.tcc, testing/adios2/interface/CMakeLists.txt, testing/adios2/interface/TestADIOSSelection.cpp
Currently, `SetMemorySelection` is entirely ignored on Read/Get. This PR adds support into BP3,
so formats based on BP3 gain the ability to use it. This PR, however, does not try to handle the case of mixed endianness, that is, when `m_ReverseDimensions` is set. **ETA:** If one tries to use `SetMemorySelection` with mixed endianness, the code will catch that case and throw an exception.
Other than added tests, there is only one change to core code, ie., to `BP3Deserializer.tcc`. It should be easy to verify that this change does not break existing code, because in the case where the memory selection is empty (the only currently supported case), the code still calls `ClipContiguousMemory` exactly as before. Behavior is only different in the case where a memory selection has been set, in …
=> support SetMemorySelection on read in BP3

source/adios2/toolkit/format/bp3/BP3Serializer.cpp, source/adios2/toolkit/format/bp3/BP3Serializer.tcc
BP3Serializer assumes little-endian and crashes with the following error on big-endian machines when compiled with Endian_Reverse=ON.
```
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
```
=> Fix BP3Serializer crash on big-endian machines if Endian_Reverse is enabled

CMakeLists.txt, cmake/DetectOptions.cmake, docs/user_guide/source/installation/cmake.rst, source/adios2/CMakeLists.txt
Other parts of the code use ADIOS_HAVE_BZip2, and this inconsistency
was causing installation failures. Fix the usage to make it consistent.
=> Consistently use BZip2 in CMake code instead of BZIP2

bindings/Fortran/CMakeLists.txt, docs/user_guide/source/installation/fortran.rst
=> Move Fortran modules from include/fortran to include/adios2/fortran

bindings/CXX11/cxx11/IO.h
I was seeing weird link-time errors because of this. I guess these are remnants from a previous design. Seems to have been accidentally added in #1478.
=> Remove LockWriterDefinitions/LockReaderSelections from IO

source/adios2/toolkit/sst/dp/rdma_dp.c
@eisenhauer @philip-davis This completes the DataInterface parameter support in RDMA DP that was partially implemented in #1516.
=> Make the DataInterface engine parameter work in SST RDMA DP

CMakeLists.txt, cmake/DetectOptions.cmake, cmake/FindBlosc.cmake, docs/user_guide/source/installation/cmake.rst, source/adios2/CMakeLists.txt, source/adios2/common/ADIOSTypes.h, source/adios2/core/ADIOS.cpp, source/adios2/operator/compress/CompressBlosc.cpp, source/adios2/operator/compress/CompressBlosc.h, source/adios2/operator/compress/CompressPNG.h, source/adios2/toolkit/format/bp3/BP3Base.cpp, source/adios2/toolkit/format/bp4/BP4Base.cpp, source/adios2/toolkit/format/bpOperation/compress/BPBlosc.cpp, source/adios2/toolkit/format/bpOperation/compress/BPBlosc.h, testing/adios2/engine/bp/operations/CMakeLists.txt, testing/adios2/engine/bp/operations/TestBPWriteReadBlosc.cpp
Addressing #1486 
Not yet tested:
1. multithread support
2. noshuffling
3. data > 2Gb (seems not supported by blosc as it returns an int for the compressed size), will implement a loop in the future.
=> Initial support for Blosc compression

examples/hello/bpReader/helloBPReader.cpp, examples/hello/bpReader/helloBPReader_nompi.cpp, examples/hello/bpWriter/helloBPWriter.cpp, examples/hello/bpWriter/helloBPWriter_nompi.cpp
The commit gives a more informative error message when the `.bp` file has not been written by the corresponding writer, and uses the `std::vector<Real>` instead of the `Real*` call so that we avoid segfaults.
=> Small quality of life improvements to basic examples.

testing/adios2/engine/ssc/CMakeLists.txt, testing/adios2/engine/ssc/RunTest.cmake, testing/adios2/engine/ssc/Ssc7d.cpp, testing/adios2/engine/ssc/SscBase.cpp, testing/adios2/engine/ssc/SscNoAttributes.cpp, testing/adios2/engine/ssc/SscNoSelection.cpp
@chuckatkins Could you help check the cmake stuff and see if there is any smarter ways of doing this? Basically what I needed here is that I need to delete the .ssc file that is generated from previous test runs before running another time. However, cmake does not allow me to run multiple commands in adding a single test. This is a workaround I found on stackoverflow, but it looks quite ugly. Thanks.
=> fixed a few problems in ssc tests

source/adios2/engine/bp4/BP4Writer.cpp, source/adios2/helper/adiosMemory.cpp, source/adios2/helper/adiosMemory.h, source/adios2/toolkit/format/bp4/BP4Base.cpp, source/adios2/toolkit/format/bp4/BP4Serializer.cpp, source/adios2/toolkit/format/bp4/BP4Serializer.h, source/adios2/toolkit/format/bp4/BP4Serializer.tcc, source/utils/CMakeLists.txt, source/utils/bp4dbg/bp4dbg.py, source/utils/bp4dbg/bp4dbg_data.py, source/utils/bp4dbg/bp4dbg_idxtable.py, source/utils/bp4dbg/bp4dbg_utils.py
Tags are added for adding more error checking possibility when we do recovery of BP4 data.
Padding is added to ensure data arrays always start on aligned memory (in the memory buffering, not in the data file).
bp4dbg.py is a start for making a 'bpdump' tool for BP4
=> Bp4 buffer tags and bp4dbg.py tool

source/adios2/toolkit/sst/cp/cp_reader.c
A spurious printf() crept into PR  #1536.  This removes it.
=> remove spurious printf

source/adios2/engine/bp4/BP4Writer.cpp
fixed the issue that data is flushed twice if deferred variables are not empty when calling DoClose() function and a potential rank 0 early return issue in WriteCollectiveMetadataFile() function
=> Bp4 doclose fix

source/adios2/engine/bp4/BP4Writer.cpp, source/adios2/engine/bp4/BP4Writer.h, source/adios2/toolkit/format/bp4/BP4Base.h, source/adios2/toolkit/format/bp4/BP4Deserializer.cpp, source/adios2/toolkit/format/bp4/BP4Serializer.cpp, source/adios2/toolkit/format/bp4/BP4Serializer.h, source/utils/bp4dbg/bp4dbg_data.py, source/utils/bp4dbg/bp4dbg_idxtable.py, source/utils/bp4dbg/bp4dbg_metadata.py, source/utils/bp4dbg/bp4dbg_utils.py
- Modify header content:
- 32 bytes Tag string e.g. "ADIOS-BP v2.3.1 Index Table     "
- byte 36 endianness
- byte 37 BP version
- byte 38 Active flag (in Index table it indicates active writer)
- bp4dbg print header for all files
=> - Add header to all BP4 data files, metadata files and index table

bindings/CXX11/adios2/cxx11/Engine.tcc, bindings/CXX11/adios2/cxx11/Variable.h, bindings/CXX11/adios2/cxx11/Variable.tcc, source/adios2/core/Variable.h, source/adios2/toolkit/format/bp3/BP3Deserializer.tcc, source/adios2/toolkit/format/bp4/BP4Deserializer.tcc, testing/adios2/bindings/fortran/TestF2C_BPReadFBlocks.cpp, testing/adios2/engine/bp/TestBPWriteReadBlockInfo.cpp
related to request in #1553 from @berkgeveci
=> Exposes IsReverseDims in BlockInfo

source/utils/bpls/bpls.cpp
I'm just redoing #1554, since the CI kept on hanging on that one.
=> bpls: fix some warnings for size_t printf arguments

source/adios2/helper/adiosMemory.h, source/adios2/helper/adiosMemory.inl, source/adios2/toolkit/format/bp3/BP3Serializer.tcc, source/adios2/toolkit/format/bp4/BP4Serializer.tcc
This simply renames `helper::CopyMemory` to `helper::CopyMemoryBlock` to
avoid a name clash with the `CopyMemory` defined in the MSVC build in #1485.
(cherry picked from commit 5f9bdb4e42a108ec19c2bf4034a3a2ddb0c5d951)
#1575
=> fix MSVC/conda build (resubmit #1575)

docs/environment.yml, readthedocs.yml
including pip sphinx packages
readthedocs can pick up the adios2 conda python module
=> moving all readthedocs requirements to conda

source/adios2/engine/hdf5/HDF5ReaderP.cpp, source/adios2/toolkit/interop/hdf5/HDF5Common.cpp, source/adios2/toolkit/interop/hdf5/HDF5Common.tcc, source/utils/adios_iotest/hdf5Stream.cpp
Sadly, variable-sized stack arrays are only a feature of C99, but not C++11,
so this patch uses std::vector instead.
This fixes #1485, the second issue there, at least hopefully so -- @ax3l, could you test this one, too, as I don't think the adios2 CI covers this case. (I changed the place identified by the error message from your report, and one more place with the same issue, but there may be more).
@chuckatkins, I haven't checked, but my guess is that the MSVC CI doesn't build ADIOS2 with HDF5, otherwise I would have expected to see this problem earlier. So that may be something for the future todo list.
=> fix HDF5Reader build with MSVC

examples/heatTransfer/write/IO_ph5.cpp, source/adios2/operator/compress/CompressSZ.cpp, testing/adios2/engine/hdf5/TestNativeHDF5WriteRead.cpp
It's not a standard type, so can't be relied on. It gave me trouble in one
config on my Mac (gcc8 + address sanitizer), but also contributed to the
last minute MVSC issues before the 2.4.0 release.
=> fix use of "uint"

source/adios2/engine/sst/SstParamParser.cpp
SST throws incorrect error messages when invalid values are given to CPCommPattern or QueueFullPolicy. Small issue but probably confusing for the user.
=> Fix incorrect error message in SST

testing/adios2/engine/staging-common/CMakeLists.txt, testing/adios2/engine/staging-common/ParseArgs.h, testing/adios2/engine/staging-common/TestCommonClient.cpp, testing/adios2/engine/staging-common/TestCommonRead.cpp, testing/adios2/engine/staging-common/TestCommonReadAttrs.cpp, testing/adios2/engine/staging-common/TestCommonReadLocal.cpp, testing/adios2/engine/staging-common/TestCommonReadShared.cpp, testing/adios2/engine/staging-common/TestCommonServer.cpp, testing/adios2/engine/staging-common/TestCommonWrite.cpp, testing/adios2/engine/staging-common/TestCommonWriteAttrs.cpp, testing/adios2/engine/staging-common/TestCommonWriteLocal.cpp, testing/adios2/engine/staging-common/TestCommonWriteModes.cpp, testing/adios2/engine/staging-common/TestCommonWriteShared.cpp, testing/adios2/engine/staging-common/TestData.h, testing/adios2/engine/staging-common/TestSupp.cmake
Currently this test is unstable with SST's default BP marshaling, so that variant is excluded.
=> Add a test for a global array with zero contribution from some rank

cmake/FindMPI.cmake, cmake/upstream/FindMPI.cmake, cmake/upstream/FindMPI/libver_mpi.c, cmake/upstream/FindMPI/test_mpi.c, testing/adios2/engine/staging-common/TestCommonReadShared.cpp
This fixes a few bugs when trying to use find MPI from dependees.
=> Bump FindMPI to v3.15.1, modified for v3.6 compatibility.

source/adios2/toolkit/format/bp3/BP3Serializer.cpp
This reverts the version changes in #1646 to the bp3 format as it can break existing compatibility.  Note that the 4 part version string is retained, this only reverts the way the version gets encoded into the BP byte stream.
=> Revert bp3 version changes

CMakeLists.txt, cmake/DetectOptions.cmake, source/adios2/CMakeLists.txt, source/adios2/core/IO.cpp, source/adios2/engine/dataman/DataManReader.cpp, source/adios2/engine/dataman/DataManWriter.cpp, source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/ssc/SscWriter.cpp, source/adios2/engine/table/TableWriter.cpp, source/adios2/engine/table/TableWriter.h, source/adios2/engine/table/TableWriter.tcc, source/adios2/toolkit/format/dataman/DataManSerializer.cpp, source/adios2/toolkit/format/dataman/DataManSerializer.h, source/adios2/toolkit/format/dataman/DataManSerializer.tcc, source/adios2/toolkit/transport/socket/SocketZmqReqRep.cpp, source/adios2/toolkit/transportman/stagingman/StagingMan.cpp, testing/adios2/engine/CMakeLists.txt, testing/adios2/engine/table/CMakeLists.txt, testing/adios2/engine/table/TableBase.cpp
The table engine is a meta-engine that uses BP4 underneath. Before offloading IO operations to the BP4 engine, it merges small puts into larger blocks to reduce the metadata size. The aggregation is done using the ZeroMQ transport.
=> Add Table engine for non-step based extremely large global arrays, and table based data

source/adios2/engine/sst/SstReader.tcc, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/dp/evpath_dp.c, testing/adios2/engine/staging-common/TestCommonClient.cpp, testing/adios2/engine/staging-common/TestSupp.cmake, testing/adios2/engine/staging-common/run_test.in
Lengthen kill delay from 2 seconds to 5 seconds.  We've been seeing some CI failures that indicate the reader isn't able to contact the writer.  On a heavily loaded CI machine, 2 seconds might not be enough for writer startup.  Hoping 5 is better.
=> Fixes to stabilize KillWriter tests

bindings/Python/py11File.tcc, source/adios2/toolkit/format/bp3/BP3Deserializer.tcc, source/adios2/toolkit/format/bp4/BP4Deserializer.tcc, testing/adios2/bindings/python/TestHighLevelAPI.py
This fixes the two previously expectedFailure test cases, though only after
fixing the test cases (they previously broke not because of the incorrect
reference data, but because they threw exceptions).
The problem occurred because m_Stream->Read() called SetBlockSelection again,
which was already done previously, anyway, but doing it again reset `variable->m_Count`.
So we now call `Get()` directly, since we're already interfacing with core directly, anyway, 
and that also saves another lookup of the Variable by string.
Also fixes the error message that confused me into thinking the problem was
with core, and a couple of similar cases.
=> python/hl: fix read() with selection of LocalArrays

bindings/Python/py11File.cpp, bindings/Python/py11File.tcc, testing/adios2/bindings/python/TestBPWriteTypesHighLevelAPI.py, testing/adios2/bindings/python/TestBPWriteTypesHighLevelAPI_HDF5.py, testing/adios2/bindings/python/TestHighLevelAPI.py
That's what one should expect for a single value, not a list / 1d array
with a single element. It is a change in behavior, though, though reading
global values was only partially supported previously, anyway.
Fixes #1671
=> python/hl: return single GlobalValue as scalar/0-d array

source/adios2/toolkit/sst/dp/rdma_dp.c
#1713 introduced a bug in the RDMA DP that was causing failures on Summit. This PR resolves this.
=> RDMA SST DP Fix on Summit

source/adios2/engine/bp4/BP4Reader.cpp, source/adios2/engine/bp4/BP4Reader.h
This ensures it can work in serial programs and also improves type safety.
=> bp4: Replace MPI_Wtime with std::chrono for poll timeouts

source/adios2/engine/bp3/BP3Reader.tcc, source/adios2/engine/bp4/BP4Reader.tcc, source/adios2/toolkit/format/bp/BPBase.cpp, source/adios2/toolkit/format/bp/bp3/BP3Base.cpp, source/adios2/toolkit/format/bp/bp3/BP3Base.h, source/adios2/toolkit/format/bp/bp4/BP4Base.cpp, source/adios2/toolkit/format/bp/bp4/BP4Base.h, source/adios2/toolkit/format/bp/bp4/BP4Serializer.tcc, testing/adios2/engine/bp/TestBPWriteAggregateRead.cpp
Reflect that reader don't need aggregation
Addresses #1745
=> Modify data file name functions in BP3 and BP4

source/adios2/toolkit/query/JsonWorker.cpp
Cast to `std::string` to avoid ambiguity in `std::string::compare`.
Fix #1804 
Seen in https://github.com/conda-forge/adios2-feedstock/pull/8
=> OSX: Fix JSON Compile Issue

source/adios2/toolkit/format/bp/BPBase.cpp
Fix #1806: just a little `-Wtautological-compare` warning.
=> Fix Warning: Unsigned Never <0

testing/adios2/engine/staging-common/run_test.in, thirdparty/EVPath/EVPath/cm_internal.h
This PR pulls in a minor EVPath upstream mod that kills a warning that only seems to appear on Conda OSX builds.  It also adds a little bit more output in staging-common/run_test so that it's clearer what the script might be waiting on if it hangs.  This was added to diagnose one of our rare CI fails, I've left it here because it's useful but seems not be worth a separate PR.
=> EVPath upstream

source/adios2/CMakeLists.txt
Fix compile errors with missing `nlohmann/json.hpp` include.
Fix #1830
=> CMake: SSC also uses JSON

bindings/CXX11/adios2/cxx11/IO.cpp, bindings/CXX11/adios2/cxx11/IO.h, source/adios2/core/IO.cpp, source/adios2/core/IO.h, source/adios2/core/VariableBase.cpp, source/adios2/core/VariableBase.h, testing/adios2/engine/bp/TestBPWriteReadAttributes.cpp
Added boolean flag to retrieve full or relative (default) attribute names
This prevents breaking the API from v2.5.0
=> Full Names Key option to IO::AvailableAttributes

testing/adios2/xml/CMakeLists.txt, testing/adios2/xml/TestXMLConfigSerial.cpp
Related to #1850 in v2.5.0 , the issue was solved by this [commit](https://github.com/ornladios/ADIOS2/pull/1817/commits/3234c58ba43f7ee50795449b49e09daa9eefa858) in PR #1817 .
This PR adds tests to verify passing a config file in serial MPI-linked mode works
=> Serial tests for config files

source/adios2/toolkit/format/bp/BPSerializer.cpp, source/adios2/toolkit/format/bp/BPSerializer.inl
Triggered a clang warning
addressing #1808
=> Removing template specialization type from definitions

source/adios2/engine/insitumpi/InSituMPIReader.cpp, source/adios2/engine/insitumpi/InSituMPIWriter.cpp, testing/adios2/engine/insitumpi/CMakeLists.txt, testing/adios2/engine/insitumpi/TestInSituMPIMPMDExceptions.cpp, testing/adios2/engine/staging-common/CMakeLists.txt
The insitumpi engine will return successfully when there is only writer (or reader) launched. This is a little confusing when the MPI environment is getting complicated, for example, running cheetah workflow on Summit. In this case it's very hard for users to directly tell whether the writers and readers are launched using correct split MPI communicators. So even if they are not launched correctly, both the writers and readers are still going to finish successfully, but of course in this case data is not going to be correct at all. So it's better to throw an exception when there is no writers or no readers launched.
=> added exceptions in insitumpi

source/adios2/common/ADIOSMacros.h, source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/ssc/SscWriter.cpp, source/adios2/helper/adiosJSONcomplex.h, source/adios2/toolkit/format/dataman/DataManSerializer.h, testing/adios2/engine/SmallTestData.h, testing/adios2/engine/bp/TestBPWriteReadAttributes.cpp
This enables support for complex attribute types, just as in ADIOS1.
See request in #1908
=> Attributes: Allow Complex Types

source/adios2/CMakeLists.txt, source/adios2/core/IO.cpp, source/adios2/core/IO.h, source/adios2/core/IOHDF5.cpp, source/adios2/core/IOMPI.cpp, source/adios2/helper/adiosComm.cpp, source/adios2/helper/adiosComm.h, source/adios2/helper/adiosCommDummy.cpp, source/adios2/helper/adiosCommMPI.cpp, source/adios2/toolkit/interop/hdf5/HDF5Common.cpp, source/adios2/toolkit/interop/hdf5/HDF5Common.h, source/adios2/toolkit/interop/hdf5/HDF5CommonMPI.cpp
Replace the hard-coded cascading-if table of engine construction with a factory using runtime lookup.  This will be useful for runtime registration of optional engines.
Split registration of IO factory entries.  Register serial engines statically.  Add runtime registration of MPI engines that are guaranteed to be available if the application creates a MPI-backed ADIOS communicator.
The HDF5 engine is special in that it is serial or parallel based on how HDF5 itself was built.  Register it only as one or the other.  Teach the HDF5 engine factory function to create the engine only when using the matching kind of communicator.
The SST engine also supports working with or without MPI.  Leave it registered statically for now.  Later the two variants can be split.
=> core: Re-implement IO::Open with an internal engine factory

bindings/C/adios2/c/adios2_c_adios.cpp, bindings/C/adios2/c/adios2_c_adios.h, bindings/CXX11/adios2/cxx11/fstream/ADIOS2fstream.cpp, bindings/CXX11/adios2/cxx11/fstream/ADIOS2fstream.h, bindings/Fortran/f2c/adios2_f2c_adios.cpp, bindings/Fortran/modules/mpi/adios2_adios_init_mod.f90, bindings/Fortran/modules/nompi/adios2_adios_init_mod.f90
Applications should be able to choose non-MPI constructors even when
using an ADIOS with MPI support available:
* For `adios2::fstream` we can simply provide overloads with and without MPI.
* For C bindings, provide `adios2_init` and `adios2_init_config` variants
named with `_serial` and `_mpi` suffixes.  Define the original names
using macros to match the old interface provided based on whether MPI
support is available.
* For Fortran bindings, update their implementation to cooperate with
the C bindings correctly.  For now we continue to provide only the
MPI-based or non-MPI-based module to Fortran.
=> bindings: Always provide non-MPI constructors

source/adios2/toolkit/sst/cp/cp_writer.c
Always reuse the incoming connection to the rank 0 reader rather than using CMget_conn() to get a new one.  This is no real change with public IP on both sides because CMget_conn() should just return that incoming connection.  However if the reader is behind a NAT, CMget_conn() wouldn't work *and* initiating a new connection won't work either.  This will allow limited functionality for 1x1 staging with a private reader.
Currently creating the PR to run this through the sanitizers.
=> WIP: Always reuse the incoming connection to the rank 0 reader

bindings/C/CMakeLists.txt, bindings/C/adios2/c/adios2_c_adios.cpp, bindings/C/adios2/c/adios2_c_adios_mpi.cpp, bindings/C/adios2/c/adios2_c_io.cpp, bindings/C/adios2/c/adios2_c_io.tcc, bindings/C/adios2/c/adios2_c_io_mpi.cpp, bindings/CXX11/CMakeLists.txt, bindings/CXX11/adios2/cxx11/ADIOS.cpp, bindings/CXX11/adios2/cxx11/ADIOSMPI.cpp, bindings/CXX11/adios2/cxx11/IO.cpp, bindings/CXX11/adios2/cxx11/IO.h, bindings/CXX11/adios2/cxx11/IOMPI.cpp, bindings/CXX11/adios2/cxx11/fstream/ADIOS2fstream.cpp, bindings/CXX11/adios2/cxx11/fstream/ADIOS2fstreamMPI.cpp, source/adios2/helper/adiosCommMPI.cpp
Move code conditioned by `ADIOS2_HAVE_MPI` into source files that are built only when that condition is true.  Later this will be useful for compiling the MPI-specific sources in a separate library.
=> bindings: Factor out MPI-specific bindings into separate sources

CMakeLists.txt, cmake/install/post/generate-adios2-config.sh.in
By default, Cmake will set the `CMAKE_INSTALL_BINDIR` variable to `"bin"`, denoting a path within
`CMAKE_INSTALL_PREFIX`. It may also be an absolute path which is currently
not considered in the post-install scripts. This PR allows using absolute paths, too.
=> Allow setting absolute paths for CMAKE_INSTALL_BINDIR

scripts/ci/cmake/ci-fedora-asan.cmake, scripts/ci/images/fedora-asan/Dockerfile, source/adios2/operator/compress/CompressZFP.cpp, source/adios2/toolkit/sst/cp/ffs_zfp.c
This only fixes one memory leak, in one context in which it's being called, but still an improvement. To reproduce:
```
ADIOS2/build$  cmake -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_FLAGS="-fsanitize=address" -DADIOS2_USE_MPI=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS} -fsanitize=address" -DCMAKE_SHARED_LINKER_FLAGS="${CMAKE_SHARED_LINKER_FLAGS} -fsanitize=address" ../
ADIOS2/build$ make -j`nproc`
ADIOS2/build$ ctest -R BPWRZFP.ADIOS2BPWRZFP1D -V # all will fail without this PR; none will fail with it
```
=> Fix memory leak from CompressZFP.

source/adios2/engine/bp3/BP3Writer.cpp, source/adios2/engine/bp3/BP3Writer.h, source/adios2/engine/bp4/BP4Writer.cpp, source/adios2/engine/bp4/BP4Writer.h, source/adios2/toolkit/transportman/TransportMan.cpp, source/adios2/toolkit/transportman/TransportMan.h
Change OpenFilesAsync so that it no longer returns a future, but rather the future remains in the class and subsequent calls into the class wait for the async task before they continue.  This preserves the current state of functionality while clearing up TSAN warnings, at a cost of an additional .valid() check on every public member invocation (rather than the one-time cost when those checks were in BP3/BP4 writer).
=> TransportMan TSAN changes

source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_reader.c, testing/adios2/engine/staging-common/TestCommonReadAttrs.cpp
Hoping to kill a heisen-bug in which a close handler tries to access reader state after the stream is destroyed, but before we completely shut down networking.  I'll run this through CI a few times to see if we trigger anything.
=> Add a Destroyed state to streams

source/adios2/toolkit/sst/CMakeLists.txt
CMake < 3.14 forget to propagate private dependencies of object
libraries.  Propagate them the same way CMake >= 3.14 do.
=> cmake: Fix sst object lib dependency propagation with CMake < 3.14

bindings/Fortran/CMakeLists.txt, bindings/Fortran/f2c/adios2_f2c_adios.cpp, bindings/Fortran/f2c/adios2_f2c_adios_mpi.cpp, bindings/Fortran/f2c/adios2_f2c_io.cpp, bindings/Fortran/f2c/adios2_f2c_io_mpi.cpp, bindings/Fortran/modules/adios2_adios_init_mod.F90, bindings/Fortran/modules/adios2_adios_init_mod_mpi.f90, bindings/Fortran/modules/adios2_adios_init_mod_serial.f90, bindings/Fortran/modules/adios2_io_open_mod.F90, bindings/Fortran/modules/adios2_io_open_mod_mpi.f90, bindings/Fortran/modules/adios2_io_open_mod_serial.f90
~~Combine the `bindings/Fortran/modules/{mpi,nompi}/*` sources to provide a single definition of the modules providing the `adios2_init` and `adios2_open` generic procedures.  Include the MPI signatures only when ADIOS is built with MPI enabled.~~ EDIT: This part was moved to #1994.
Split the implementations of the serial and MPI variants of the Fortran bindings into separate source files.  For each of the `adios2_init` and `adios2_open` generic procedures, ~~all signatures must remain declared in a single module, so use Fortran submodules~~ (EDIT: generic procedure interfaces can have different signatures added by different modules) put the implementations in separate modules in separate sources.  Later this will be useful for compiling the MPI-specific sources in a separate library.
=> bindings: Factor out MPI-specific Fortran bindings into separate sources

.travis.yml, source/adios2/helper/adiosString.cpp
If no unit is appended to, e.g. the `maxbuffersize` string, then the last two numbers are chopped and things are interpreted as bytes. For example, 1GiByte (`std::to_string(1024*1024*1024)`) became ~10MiByte.
This fixes it and assumes the user meant Bytes.
=> Fix: stringToByteUnits Default

source/adios2/engine/bp3/BP3Reader.cpp, source/adios2/toolkit/format/bp/bp3/BP3Deserializer.cpp, testing/adios2/helper/CMakeLists.txt, testing/adios2/helper/TestReadNonBPFile.cpp
Previously, when opening a non-.bp through adios, it would tell you that the .bp file was big endian, rather than saying that it wasn't a .bp file.
This PR fixes that.
Fixes 1702.
=> Sensible error message when parsing non-bp3

source/adios2/core/IO.cpp, source/adios2/core/VariableBase.cpp, source/adios2/helper/adiosString.cpp, source/adios2/helper/adiosString.h, source/adios2/operator/compress/CompressZFP.cpp, testing/adios2/engine/bp/operations/TestBPWriteReadZfp.cpp
Fixes #1875.
Note that I did not add the ability to be case insensitive; as suggested in the issue. I merely added an error message which states clearly what is required, and states clearly what was provided.
=> Fix ZFP error message.

source/adios2/helper/adiosCommMPI.cpp
When various destructors are called, the MPI communicator helper
will clean up by deleting the adios communicator.  Well, this change
prevents that from happening twice.  When compiled with PGI and
executed with TAU profiling, this double-free causes memory to be
corrupted.  This PR fixes issue #2001
=> helper: Avoid freeing Comm-held MPI_Comm more than once

bindings/C/adios2/c/adios2_c_adios_mpi.cpp, bindings/C/adios2/c/adios2_c_io_mpi.cpp, bindings/CXX11/adios2/cxx11/ADIOSMPI.cpp, bindings/CXX11/adios2/cxx11/IOMPI.cpp, bindings/CXX11/adios2/cxx11/fstream/ADIOS2fstreamMPI.cpp, bindings/Python/py11ADIOS.cpp, bindings/Python/py11File.cpp, bindings/Python/py11IO.cpp, source/adios2/helper/adiosCommMPI.cpp, source/adios2/helper/adiosCommMPI.h, source/adios2/toolkit/sst/util/sst_conn_tool.cxx, source/utils/adios_reorganize/Reorganize.cpp
Through a series of commits:
* f7fec28f4 (core: Refactor ADIOS factory to use Comm encapsulation, 2019-06-21, `v2.5.0~66^2~35`)
* 29177b01c (engine: Construct with Comm encapsulation, 2019-06-18, `v2.5.0~66^2~31`)
* 337156181 (helper: Factor out MPI-specific Comm interfaces, 2019-09-12)
* 89891238b (core: Replace MPI with Comm in ADIOS, IO, and Stream interfaces, 2019-10-07)
we converted the `core::ADIOS` constructor from taking a `MPI_Comm` and calling `MPI_Comm_dup` internally to taking an instance of `helper::Comm` by value, typically moved from an instance created by `helper::CommFromMPI`.  Therefore `helper::CommFromMPI` calls `MPI_Comm_dup` to preserve the existing semantics.
However, two commits introduced uses of `helper::CommFromMPI` in places that did not previously use …
=> helper: Do not always duplicate MPI_Comm on Comm construction

source/adios2/core/ADIOS.cpp, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPNoXMLRecovery.cpp
=> Prevent hang when throwing out of adios constructor in MPI.

source/adios2/core/Engine.tcc, source/adios2/engine/inline/InlineReader.cpp, source/adios2/engine/inline/InlineReader.h, source/adios2/engine/inline/InlineReader.tcc, source/adios2/engine/inline/InlineWriter.cpp, source/adios2/engine/inline/InlineWriter.h, source/adios2/engine/inline/InlineWriter.tcc, testing/adios2/engine/inline/TestInlineWriteRead.cpp
There's some clean up and stuff to the inline engine, along with these two fixes:
- All variables now have their block info cleared out when starting to write a new step, instead of only the variables that were read on the previous step.
- Reader now reports that it is on the same step as the Writer, since for the inline engine, it doesn't make sense for them to be on different steps.
=> Inline engine fixes

source/adios2/engine/bp3/BP3Writer.cpp, source/adios2/engine/bp4/BP4Writer.cpp, source/adios2/toolkit/transport/Transport.h, source/adios2/toolkit/transport/file/FileFStream.cpp, source/adios2/toolkit/transport/file/FileFStream.h, source/adios2/toolkit/transport/file/FilePOSIX.cpp, source/adios2/toolkit/transport/file/FilePOSIX.h, source/adios2/toolkit/transport/file/FileStdio.cpp, source/adios2/toolkit/transport/file/FileStdio.h, source/adios2/toolkit/transport/null/NullTransport.cpp, source/adios2/toolkit/transport/null/NullTransport.h, source/adios2/toolkit/transport/shm/ShmSystemV.cpp, source/adios2/toolkit/transport/shm/ShmSystemV.h, source/adios2/toolkit/transportman/TransportMan.cpp, source/adios2/toolkit/transportman/TransportMan.h
This implements async open() in the fstream, stdio and posix transports only, and only for the write/create open mode.  @pnorbert , I think this is one of those features that is not exercised in CI at all, and perhaps can't trivially be, lacking a super slow filesystem, so please if there's a way to test other than my own efforts let me know.  (I did add a thread sleep into the asynchronous open threads and it still passed tests, so hopefully OK.)  @KyleFromKitware , this looks good to TSAN on my end, but a check from you would be appreciated too.
Closes #1990
=> Move async file open functionality to transports

ReadMe.md
Add a badge to install ADIOS2 via conda-forge: [![Conda Version](https://img.shields.io/conda/vn/conda-forge/adios2)](https://anaconda.org/conda-forge/adios2) 
Conda-forge packages are currently built for win-64, osx-64, linux-64, linux-aarch64, and linux-ppc64le.
By default, conda-forge packages install without MPI. The user can control variants via:
- `conda install -c conda-forge adios2` default, nompi variant
- `conda install -c conda-forge adios2=*=mpi*` any mpi-compatible implementation
- `conda install -c conda-forge adios2=*=mpi_mpich*` pick mpich variant.
Same result as `conda install -c conda-forge mpich adios2=*=mpi*` .
- `conda install -c conda-forge adios2=1.13=nompi*` explicitly forbid MPI.
Usually not necessary, as the build number offset causes `nompi` to be preferred …
=> Readme: Conda Badge

bindings/Fortran/CMakeLists.txt, bindings/Fortran/modules/adios2_adios_init_mod.F90, bindings/Fortran/modules/adios2_adios_init_mod_mpi.F90, bindings/Fortran/modules/adios2_adios_init_mod_serial.F90, bindings/Fortran/modules/adios2_io_open_mod.F90, bindings/Fortran/modules/adios2_io_open_mod_mpi.F90, bindings/Fortran/modules/adios2_io_open_mod_serial.F90, cmake/ADIOSFunctions.cmake
Convert the separate modules implementing Fortran `adios2_init` and `adios2_open` generic procedure signatures for MPI and non-MPI variants into submodules.  This allows the primary modules to be built first and the implementation submodules built later in separate libraries.
In order to support compilers that do not support Fortran submodules, use preprocessor conditions to optionally build without submodules as before.
=> bindings: Convert Fortran MPI- and non-MPI implementations to submodules

source/adios2/engine/ssc/SscReader.tcc, source/adios2/helper/adiosMpiHandshake.cpp
@JasonRuonanWang I was getting a bus error due to unaligned memory access on the JAXA system (it has strict alignment requirements). This PR removes the unaligned accesses.
=> Fix unaligned memory access in SSC engine

source/adios2/engine/insitumpi/InSituMPISchedules.cpp
This fixes a regression bug in the InSituMPI engine that causes segfaults on big-endian platforms.
@pnorbert
=> Fix InSituMPI crash on big-endian platforms

source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_reader.c
No changes in locking here, just modifying the macros so that the Locked boolean is stream-local and we're a bit more uniform.  Doing piece-wise movement towards making TSAN happy to make it easier to evaluate each change.
=> Revamp locking macros on SST reader side

cmake/adios2-config-common.cmake.in
Since #1176, our CMake package configuration file makes `enable_language({C,CXX,Fortran})` calls on behalf applications using `find_package(ADIOS2)`.  This causes such applications to require a Fortran compiler even if they do not themselves use Fortran or link to any ADIOS2 Fortran binding libraries.
Remove the `enable_language()` calls from our package configuration file.  Applications should enable whatever languages they are using.  ~~If any problem the `enable_language()` calls were addressing comes up again, we can consider other solutions.~~  EDIT: Filter our own usage requirements to avoid referencing languages that are not enabled by the application.
Fixes: #1885
=> cmake: Do not enable languages on behalf of consumers

testing/adios2/engine/staging-common/CMakeLists.txt, testing/adios2/engine/staging-common/ParseArgs.h, testing/adios2/engine/staging-common/TestCommonReadLocal.cpp, testing/adios2/engine/staging-common/TestCommonWriteLocal.cpp, testing/adios2/engine/staging-common/TestData.h, testing/adios2/engine/staging-common/TestSupp.cmake
Add a test in which we write/read local variables and the size of one of which varies across ranks and timesteps.  @pnorbert Please look at this.  One of the variables written, i8, has a different size across ranks and timesteps.  But I'm not seeing failures with BP or SST.  Can you help sort what the code where you are seeing failures might be doing differently?
=> Add a test in which we write/read changing local variables

source/adios2/core/IO.cpp, source/adios2/core/IO.tcc, source/adios2/core/Operator.cpp, source/adios2/core/VariableBase.cpp
Simple tweaks to a few files using DebugMode.  The idea here is that if it's worth raising an exception in DebugMode, it's worth raising it unconditionally.  None of the changes here affect anything where the actual checks inside an "if(DebugMode)" conditional are more expensive than a compare or two.  It does remove some checks which had the effect of making semantics different in DebugMode than in normal mode.  (Specifically, normal mode would allow multiple variables with the same name to be defined without error, but with unclear consequences.  Now multiple definition is disallowed always.)
(This is just for a few files in core for now, but other uses could benefit from examination.)
=> Debug mode changes

source/adios2/core/IO.tcc, testing/adios2/engine/bp/TestBPWriteAppendReadADIOS2.cpp
I've fixed the bug related to attribute in append mode. After the fix, when open a bp file ( the file has been appended in which the same attribute might have been written multiple times) for read, if the same attribute has been defined, the reader will not define it again which leads to an exception. Instead, the reader will check the value of this attribute. If the value is the same, it won't do anything. If the value is changed, it will throw an exception because the value of attribute is not allowed to be changed.
=> fixed the attribute bug in append mode

source/adios2/toolkit/sst/cp/cp_reader.c
Currently these mods ignore the attributes issue (updated by both the main and network thread due to discard/install skipped model).   They also ignore writer-side TSAN issues.  But, run clean for me with the following TSAN suppression file:
race:*RemoveAllAttributes*
race:*EvpathReadRequestHandler*
race:*EvpathDestroyWriter*
race:*cp_writer.c*
race:libadios2_evpath.so
Tracking down and fixing those suppressions will be the subject of future PRs.
Change-wise, this adds some comments on routines WRT what thread will be calling them and what their locking needs are.  Generally critical sections are broadened to include state shared by the threads.  Locks are preferentially acquired at entry to interface routines, rather than internally.
=> SST Reader-side TSAN mods

source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/dp/evpath_dp.c
This corrects a possible race condition that has to do with the timing of connection close detection and how it's handled on the reader side.  Generally, a close of the connection to the writer (from the reader) is interpreted as a failure, *unless* we have received a Close message from the writer and/or the reader Status has been updated to Closed by status propogation on the reader side.  But, it is possible that we'll get a connection close on a link either 1) in peer mode, but on a connection upon which we won't get the close, or 2) in commmin mode when we're not rank 0 (and therefore won't get a Close message) but before we do status propogation.  In these circumstances, we should *not* interpret the connection close as an immediate failure.  (If it is a failure we should get later …
=> Reader side connection close race

examples/heatTransfer/heat_bp4.xml, source/adios2/toolkit/transport/file/FileFStream.cpp, source/adios2/toolkit/transport/file/FileStdio.cpp, source/adios2/toolkit/transport/file/FileStdio.h, source/adios2/toolkit/transportman/TransportMan.cpp, testing/adios2/transports/CMakeLists.txt, testing/adios2/transports/TestFile.cpp
This allows the `fstream` and `stdio` transports to be configured for unbufferd I/O by setting the buffer to `null`.  See  https://gcc.gnu.org/onlinedocs/libstdc++/manual/streambufs.html#io.streambuf.buffering
The defaults remain unchanged but this now allows an extra transport parameter to disable buffered i/o.
=> Enable "buffered" parameter for file transports

source/adios2/engine/ssc/SscHelper.cpp, source/adios2/engine/ssc/SscHelper.h, source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/ssc/SscReader.tcc, source/adios2/engine/ssc/SscWriter.tcc, testing/adios2/engine/ssc/TestSscBase.cpp
@pnorbert This should work once it is merged. You should be able to use both the BlocksInfo API and the Variable API to get single values.
=> Fixing a few problems for single values in SSC

docs/user_guide/source/engines/dataman.rst
The dataman doc page looks a little weird in format. Trying to fix it.
=> trying to fix format in dataman doc

source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/dp/evpath_dp.c
This runs cleanly for me under TSAN with only the following 4 exclusions:
race:*RemoveAllAttributes*
race:*LoadAttributes*
race:free_FFSBuffer
race:read_generation_environment_variables
Of these, the first two relate to the attribute issues and await reworking those semantics.  The last one is FFS-level and is *supposed* to be excluded by a __attribute__((no_sanitize("thread"))), but doesn't seem to be for some reason.  Still have to see why.  And what's going on with free_FFSBuffer.
=> Tsan writer

source/adios2/engine/sst/SstReader.cpp, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/ffs_marshal.c
This includes another directive to TSAN to ignore a subroutine, this one that is the upcall function pointer initialization that is serialized with the uses of those pointers (which might happen when locks are held).  It's just not worth jumping through the hoops to make TSAN happy another way (by breaking critical sections which might introduce other race conditions).
The other change is moving attribute (and precious data) installation into the BeginStep search-for-timestep phase, rather than discarding metadata for known-to-be-unnecessary timesteps upon arrival.  This better fits the attribute model because we really shouldn't be installing attributes until we "pass" the timestep they appear on (so previously we were doing it too soon).  However, it does mean that we're keeping …
=> Patch attribute handling to satisfy TSAN

bindings/C/adios2/c/adios2_c_adios.cpp, bindings/C/adios2/c/adios2_c_adios.h, bindings/C/adios2/c/adios2_c_adios_mpi.cpp
The `adios2_init{,_config}_{serial,mpi}` constructor functions were added by #1946.  They have not yet been included in a release, so we can change the signatures.  Drop the `debug_mode` argument.
~~Create undocumented/private `..._with_debug_mode` variants of the constructor functions to implement the legacy `adios2_init` and `adios2_init_config` constructors (whose args vary based on use of MPI).~~ EDIT: Define the legacy `adios2_init` and `adios2_init_config` constructors (whose args vary based on use of MPI) as function-like preprocessor macros that drop the `debug_mode` argument.  This preserves compatibility with callers of the original signatures.
Issue: #2127
=> bindings: Remove debug_mode flag from C adios2_init_{serial,mpi}

source/adios2/CMakeLists.txt
The `tautimer.cpp` source file uses `dlopen` and friends.  Link explicitly to the library providing those symbols.  Previously the symbols were only available when the library was used by a consumer that happened to link the 'dl' library or equivalent.
=> toolkit: link taustubs to 'dl' library explicitly

testing/adios2/engine/inline/TestInlineWriteRead.cpp
This was accidentally left out of #2145.
=> testing: Switch inline engine test MPI usage based on libraries linked

source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstReader.h, source/adios2/engine/sst/SstReader.tcc
In the existing formulation, ReadVariableBlocks() is a per-variable call.  It requests all writer-side data necessary to fulfill the local read (possibly multiple requests), waits for those requests to complete and then fills the read buffers for that variable.  If latency is long on those requests, this incurs a lot of overhead because multiple variables are handled only serially, while SST can handle many concurrent data requests.  This refactoring breaks ReadVariableBlocks() into two routines, ReadVariableBlocksRequests() and ReadVariableBlocksFill(), with a step in between that waits for all the read requests to complete.  The object is to maximize concurrency in the read requests by issuing the read requests for all pending variables (not just one) and then waiting on all those …
=> Optimize SST/BP Reader

docs/user_guide/source/ecosystem/utilities/adios_reorganize.rst, source/utils/CMakeLists.txt, source/utils/adios_reorganize/Reorganize.h
Provide a serial `adios_reorganize` tool that does not need MPI.  Split the MPI variant into a separate `adios_reorganize_mpi` tool that uses MPI and is available only when ADIOS2 is built with MPI support.
=> utils: Provide separate serial and MPI 'adios_reorganize{,_mpi}' tools

bindings/Python/CMakeLists.txt, bindings/Python/py11ADIOS.cpp, bindings/Python/py11ADIOSMPI.cpp, bindings/Python/py11File.cpp, bindings/Python/py11FileMPI.cpp, bindings/Python/py11IO.cpp, bindings/Python/py11IOMPI.cpp, bindings/Python/py11glue.cpp
Rename Python glue helpers to match current conventions.
Move method definitions guarded by `#if ADIOS2_USE_MPI` into separate source files that are added only when using MPI.
While at it, fix the `INSTALL_RPATH` of the `.so` on Linux.
=> bindings: Clean up Python binding MPI interfaces

testing/adios2/bindings/C/TestBPWriteReadMultiblock.cpp, testing/adios2/engine/staging-common/TestCommonWriteF.F90, testing/adios2/performance/manyvars/PerfManyVars.c, testing/adios2/performance/manyvars/TestManyVars.cpp
In very early days of ADIOS2, a timeout of 0.0 in BeginStep() meant "Block, don't timeout", but this convention got changed when we actually implemented timeout and realized that 0.0 would be a better value for "poll" or "try to do this now, but if it's not immediately doable, return NotReady".  This PR corrects some places that still have the old convention, perhaps added since PR #1493 (which changed the convention).   None changes of these are likely impactful, in that they were either on write-mode (where we don't do timeouts anywhere AFAIK), or were restricted to engines that don't implement timeouts.
=> Kill lurking instances of BeginStep() where timeout is specified as 0.0

source/adios2/helper/adiosNetwork.cpp, source/adios2/helper/adiosNetwork.h
Since  #1659 the `AvailableIpAddresses` function is needed by the Table engine but its conditions only make it available for dataman or ssc.  Update the conditions to enable the functions for Table and drop them for SSC (which does not use them).  Also add a comment explaining why the conditions are needed in the first place.
=> helper: Enable adiosNetwork functions for Table engine

testing/CMakeLists.txt, testing/adios2/bindings/C/CMakeLists.txt, testing/adios2/bindings/fortran/CMakeLists.txt, testing/adios2/bindings/fortran/operation/CMakeLists.txt, testing/adios2/bindings/python/CMakeLists.txt, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/operations/CMakeLists.txt, testing/adios2/engine/common/CMakeLists.txt, testing/adios2/engine/dataman/CMakeLists.txt, testing/adios2/engine/hdf5/CMakeLists.txt, testing/adios2/engine/inline/CMakeLists.txt, testing/adios2/engine/insitumpi/CMakeLists.txt, testing/adios2/engine/null/CMakeLists.txt, testing/adios2/engine/nullcore/CMakeLists.txt, testing/adios2/engine/ssc/CMakeLists.txt, testing/adios2/engine/staging-common/CMakeLists.txt, testing/adios2/engine/table/CMakeLists.txt, testing/adios2/helper/CMakeLists.txt, testing/adios2/interface/CMakeLists.txt, testing/adios2/performance/manyvars/CMakeLists.txt, testing/adios2/performance/query/CMakeLists.txt, testing/adios2/transports/CMakeLists.txt, testing/adios2/xml/CMakeLists.txt, testing/adios2/yaml/CMakeLists.txt
Teach `gtest_add_tests_helper` and `fortran_add_test_helper` to add both serial and MPI tests when possible.  Update the `mpi` argument allowed enumeration values to distinguish the case of "mpi allowed" from "mpi only".  Update all call sites accordingly.
With this, tests can run both serial and MPI variants when ADIOS2 is built with MPI enabled.  Previously the tests would only run one or the other variant.
=> testing: Teach test helper functions to add both Serial and MPI tests

cmake/FindPythonModule.cmake
=> Fix mpi4py required

bindings/Python/py11File.cpp, bindings/Python/py11File.h, bindings/Python/py11glue.cpp, source/adios2/core/IO.cpp, source/adios2/core/IO.h, source/adios2/core/IO.tcc, source/adios2/helper/adiosString.cpp, source/adios2/helper/adiosString.h, source/adios2/helper/adiosString.tcc, source/adios2/helper/adiosType.h, source/adios2/helper/adiosType.inl, testing/adios2/bindings/python/TestHighLevelAPI.py
Related to #2196 and #2197 to allow passing a list of case-insensitive input keys to customized variables information.
This PR does not break the current API for `available_variables`.
CC: @khuck @dyokelson
=> Python available_variables to allow list of specific keys

source/adios2/toolkit/sst/cp/cp_writer.c
Perform normal release operations on queued Release notices from the readers at writer close, rather than just dumping them. The push-based RDMA data plane needs this because it needs to perform data transfer operations in response to release messages.
=> Handle pending releases when closing writer

bindings/Fortran/CMakeLists.txt, cmake/DetectOptions.cmake
Resolves #2228 by replacing errors with warnings. There was no way to fix it without API-breaking changes. These warnings *can't* be silenced with `-Wno-argument-mismatch` since GCC 10 removed that.
Current warnings:
```bash
/Users/usr/Downloads/ADIOS23/bindings/Fortran/modules/adios2_attribute_data_mod.f90:225:43:
225 |             call adios2_attribute_data_f2c(data, length, attribute%f2c, ierr)
|                                           1
......
240 |             call adios2_attribute_data_f2c(data, length, attribute%f2c, ierr)
|                                           2
Warning: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/INTEGER(8)).
/Users/usr/Downloads/ADIOS23/bindings/Fortran/modules/adios2_attribute_data_mod.f90:114:44:
114 | …
```
=> Fortran GCC 10 compat: -fallow-argument-mismatch for

bindings/Python/py11glue.cpp, testing/adios2/bindings/python/CMakeLists.txt
The one-argument `adios2.ADIOS(...)` constructor has two overloads when MPI is enabled: `ADIOS(bool)` and `ADIOS(MPI4PY_Comm)`.  The representation of `MPI4PY_Comm` is just an integer, so a call with a `bool` may try to convert it (and fail).  Re-order the pybind11 definitions of these signatures so that the `ADIOS(bool)` is tried first.  That way a call with a `bool` will use it and a call with a `MPI4PY_Comm` will not convert and fall back to the proper variant.
Also update the test suite to always add the Serial variant of the tests and additionally enable the MPI variants when possible.  The `Bindings.Python.BPWriteReadTypes.Serial` test in particular covers the overload selection problem fixed here.
Fixes: #2233
=> bindings: Fix Python serial program init when ADIOS2 has MPI enabled

testing/adios2/engine/dataman/TestDataMan1D.cpp, testing/adios2/engine/dataman/TestDataMan2DMemSelect.cpp, testing/adios2/engine/dataman/TestDataMan3DMemSelect.cpp, testing/adios2/engine/dataman/TestDataManReaderDoubleBuffer.cpp, testing/adios2/engine/dataman/TestDataManReaderSingleBuffer.cpp, testing/adios2/engine/dataman/TestDataManReliable.cpp, testing/adios2/engine/dataman/TestDataManWriterDoubleBuffer.cpp, testing/adios2/engine/dataman/TestDataManWriterSingleBuffer.cpp
A random timeout error was seen in CI when running dataman reliable test. This PR tries to prevent similar errors from happening again.
=> reduced data steps in dataman tests in order to prevent timeout

CMakeLists.txt, cmake/DetectOptions.cmake, cmake/FindIME.cmake, docs/user_guide/source/engines/bp3.rst, docs/user_guide/source/engines/bp4.rst, docs/user_guide/source/setting_up/source/cmake.rst, source/adios2/CMakeLists.txt, source/adios2/toolkit/transport/Transport.cpp, source/adios2/toolkit/transport/Transport.h, source/adios2/toolkit/transport/file/FileIME.cpp, source/adios2/toolkit/transport/file/FileIME.h, source/adios2/toolkit/transportman/TransportMan.cpp
FileIME is an alternative to FilePOSIX that directly reads and writes files stored on DDN's IME burst buffer using the IME native API (kernel's VFS is bypassed). This has been tested on Oakforest-PACS installed at the University of Tsukuba.
=> Add FileIME transport

source/adios2/engine/bp4/BP4Reader.cpp
When checking data in UpdateBuffer, new step(s) may have not arrived yet. When checking active flag next, the writer may have completed write and terminated. So we may have missed a step or two. A final check on the index avoids this race condition. 
Left some debug print and value change to still make it fail in Debug builds to see in if this was actually the race condition seen in CI. This needs to be removed for the release.
=> Handle race condition in BP4Reader

testing/adios2/engine/staging-common/CMakeLists.txt, testing/adios2/engine/staging-common/TestSupp.cmake
=> WIP:  LockGeometry test

source/adios2/engine/hdf5/HDF5ReaderP.cpp
Fix signed-unsigned conversion warnings seen on MSVC:
- `conversion from 'size_t' to 'int', possible loss of data`
- `'>=': signed/unsigned mismatch`
=> HDF5P: Signed/Unsigned Warnings

.github/workflows/build-and-test.yml, azure-pipelines.yml, source/utils/adios_reorganize/Reorganize.h
The mac builds have been very flaky the past several days so I'm disabling them for now to allow other work to continue and we can re-enable them in a PR once the issue is resolve.
=> ci: Disable mac builds

source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/ssc/SscReader.h, source/adios2/engine/ssc/SscWriter.cpp, source/adios2/engine/ssc/SscWriter.h
Previously, SSC writers block EndStep for sending data. This PR moves MPI_Wait and MPI_Win_fence from EndStep to BeginStep. Data transfers can then be overlapped with application algorithms that happen between EndStep(N) and BeginStep(N+1).
=> [SSC] Hide data transfer from application activities

bindings/CXX11/adios2/cxx11/Engine.cpp, bindings/CXX11/adios2/cxx11/Engine.h, source/adios2/core/Engine.cpp, source/adios2/core/Engine.h, source/adios2/engine/bp3/BP3Writer.cpp, source/adios2/engine/bp3/BP3Writer.h, source/adios2/engine/bp3/BP3Writer.tcc, source/adios2/engine/bp4/BP4Writer.cpp, source/adios2/engine/bp4/BP4Writer.h, source/adios2/engine/bp4/BP4Writer.tcc, source/adios2/toolkit/format/bp/BPBase.cpp, source/adios2/toolkit/format/bp/BPBase.h, source/adios2/toolkit/format/buffer/heap/BufferSTL.cpp, source/adios2/toolkit/format/buffer/heap/BufferSTL.h, source/adios2/toolkit/transportman/TransportMan.cpp, source/adios2/toolkit/transportman/TransportMan.h, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPBufferSize.cpp
…datasize correctly in case of multiple calls of PerformPuts(). Addresses #2320
=> Fix performputs buffersize

source/adios2/engine/bp4/BP4Reader.cpp, source/adios2/engine/bp4/BP4Reader.h, source/utils/bpls/bpls.cpp
Rework the timeout loops and separate timeout loops for opening md.idx and md.0.
Adds extra 5s wait for md.0 if md.idx is present but md.0 is not yet present.
=> Rework bp4 open

source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/dp/evpath_dp.c, source/adios2/toolkit/sst/dp/rdma_dp.c, testing/adios2/engine/staging-common/CMakeLists.txt, testing/adios2/engine/staging-common/TestThreads.cpp, thirdparty/EVPath/EVPath/cm.c, thirdparty/EVPath/EVPath/cm_internal.h, thirdparty/EVPath/EVPath/evpath.h, thirdparty/atl/atl/attr.c
=> SST more thread safe

bindings/CXX11/adios2/cxx11/IO.h, bindings/CXX11/adios2/cxx11/Types.cpp, bindings/CXX11/adios2/cxx11/Types.h, bindings/CXX11/adios2/cxx11/Types.tcc, docs/user_guide/source/advice/advice.rst, examples/useCases/insituGlobalArrays/insituGlobalArraysReaderNxN.cpp, testing/adios2/engine/bp/TestBPWriteAppendReadADIOS2.cpp, testing/adios2/engine/bp/TestBPWriteReadAttributes.cpp, testing/adios2/engine/common/TestEngineCommon.cpp, testing/adios2/engine/hdf5/TestHDF5WriteReadAttributesADIOS2.cpp, testing/adios2/engine/staging-common/TestCommonReadAttrs.cpp, testing/adios2/interface/TestADIOSDefineAttribute.cpp, testing/adios2/interface/TestADIOSDefineVariable.cpp
In #2318 we accidentally renamed the public-facing `GetType` to `GetDataType` too.  Revert that part of the change.
=> bindings: Restore public adios2::GetType function name

source/adios2/engine/bp4/BP4Reader.cpp, source/adios2/toolkit/format/bp/bp3/BP3Deserializer.tcc, source/adios2/toolkit/format/bp/bp4/BP4Deserializer.tcc, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPStepsFileGlobalArray.cpp, testing/adios2/engine/bp/TestBPStepsFileLocalArray.cpp, testing/adios2/engine/bp/TestBPStepsInSituGlobalArray.cpp, testing/adios2/engine/bp/TestBPStepsInSituLocalArray.cpp, testing/adios2/engine/staging-common/CMakeLists.txt, testing/adios2/engine/staging-common/TestCommonWriteLocal.cpp
Added tests for reading back global/local arrays with different modes: File vs Stream, All steps vs step by step, and block-by-block.
Exposes bugs in #1639 and #2339 and also exposes read problems with variables that are not written in the first step and/or not written every step.
A lot of tests fail in this PR. Any attempt to solve the handling of steps in BP3/BP4 must pass these tests.
More tests needs to be created, especially for in-situ reading where new steps are becoming available during reads.
=> Tests for reading variables with Steps

source/utils/adios_iotest/settings.cpp, source/utils/adios_iotest/settings.h
Currently, the iotest x y z rank decomposition is done with the -d flag, using literal dimensions; so `-d 2 4 2 `defines a 2x4x2 decomposition, and the number of ranks for the application must be 16. This PR adds the option to specify the ratio of the dimensions of ranks by providing a comma-separated list to the -d flag, so that `-d 1,2,1` would have the same results ad `-d 2 4 2` if 16 ranks were provided, but would also work for a scaled up or scaled down number of ranks (for example, `-d 1,2,1` with 2 ranks would be equivalent to `-d 1 2 1`; `-d 1,2,1` with 54 ranks would be equivalent to `-d  3 6 3`; with 128 ranks, `-d 4 8 4`; etc.)
The reason for this change is to work better with Cheetah. It is not possible to correlate options that are separated by spaces inside a sweep in …
=> Add rank decomposition by dimensional ratio to iotest

bindings/C/adios2/c/adios2_c_io.cpp, source/adios2/core/ADIOS.cpp, source/adios2/core/Attribute.cpp, source/adios2/core/Attribute.h, source/adios2/core/Attribute.tcc, source/adios2/core/AttributeBase.cpp, source/adios2/core/AttributeBase.h, source/adios2/core/IO.cpp, source/adios2/core/IO.h, source/adios2/core/IO.tcc, source/adios2/core/VariableBase.cpp, source/adios2/engine/insitumpi/InSituMPIReader.cpp, source/adios2/engine/ssc/SscHelper.cpp, source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/sst/SstWriter.cpp, source/adios2/helper/adiosXML.cpp, source/adios2/helper/adiosYAML.cpp, source/adios2/toolkit/format/bp/BPSerializer.cpp, source/adios2/toolkit/format/dataman/DataManSerializer.cpp, source/adios2/toolkit/interop/hdf5/HDF5Common.cpp, source/utils/adios_reorganize/Reorganize.cpp, source/utils/adios_reorganize/Reorganize.h, source/utils/bpls/bpls.cpp, source/utils/bpls/bpls.h
Flatten IO variable and attribute storage maps.  Replace each two-layer map (and intermediate index) with one direct map.  Map directly from the variable name (or attribute name) to the corresponding `Variable<T>` (or `Attribute<T>`) instance.  Avoid using per-type maps by mapping to `unique_ptr<VariableBase>` (or `unique_ptr<AttributeBase>`) and statically downcast as needed.
This removes several uses of `ADIOS2_FOREACH_*` macros and likely enables removal of many more in future work.
=> core: Simplify IO variable and attribute storage

source/adios2/toolkit/format/bp/bp4/BP4Serializer.cpp, source/utils/bp4dbg/adios2/bp4dbg/metadata.py
Fix the reported number of blocks in the BP4 metadata for a variable. When one rank wrote multiple blocks in a step, it was only counted as one block in the last step of collecting metadata (sort-merge step on rank 0). 
This number in the metadata was not used by BP4 reader so it did not cause reading problems. 
Also modified bp4dbg that caught this error, now it reads like BP4 (based on length of index, not based on reported number of blocks). It prints an error now if discrepancy is found between these two ways of reading.
=> BP4 metadata format fix

CMakeLists.txt
The top line requires a `cmake_minimum_required(VERSION 3.12)`.
=> Remove superfluous check on CMake version.

source/adios2/toolkit/transport/file/FilePOSIX.cpp, source/adios2/toolkit/transport/file/FilePOSIX.h
-- don't know what is happening on the NVMe
=> Print errno and strerror in POSIX transport to see better error messages

bindings/C/adios2/c/adios2_c_types.h
```
In file included from /home/svcpetsc/petsc-hash-pkgs/577169/include/adios2/c/adios2_c_adios.h:14:0,
from /home/svcpetsc/petsc-hash-pkgs/577169/include/adios2_c.h:16,
from /scratch/svcpetsc/glci-builds/GXbQf6e_/1/petsc/petsc/src/sys/objects/pinit.c:649:
/home/svcpetsc/petsc-hash-pkgs/577169/include/adios2/c/adios2_c_types.h:141:15: error: ‘adios2_string_array_element_max_size’ defined but not used [-Werror=unused-variable]
static size_t adios2_string_array_element_max_size = 4096;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
=> Fix compile warning:

bindings/CXX11/adios2/cxx11/IO.h, source/adios2/engine/bp3/BP3Writer.cpp
=> Fix documentation that append mode works with BP4 engine. 

source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/ssc/SscReader.h, source/adios2/engine/ssc/SscReader.tcc, source/adios2/engine/ssc/SscWriter.cpp, source/adios2/engine/ssc/SscWriter.h, source/adios2/engine/ssc/SscWriter.tcc, testing/adios2/engine/ssc/CMakeLists.txt, testing/adios2/engine/ssc/TestSscCommon.h, testing/adios2/engine/ssc/TestSscVaryingSteps.cpp
This has been requested by several applications, but I have been too lazy to implement. Part of the reason is because SSC is mainly designed and optimized for fixed IO patterns, and I really wanted to just focus on that. Now that unexpectedly more users are asking for it, so I finally decided to implement it. It's for sure not yet optimal performance wise, but at least it should work at scale. I will do optimizations in future PRs.
=> SSC now works with flexible IO pattern

docs/user_guide/source/engines/inline.rst, examples/hello/inlineReaderWriter/helloInlineReaderWriter.cpp, source/adios2/core/IO.cpp, source/adios2/core/IO.h, source/adios2/engine/inline/InlineReader.cpp, source/adios2/engine/inline/InlineReader.h, source/adios2/engine/inline/InlineReader.tcc, source/adios2/engine/inline/InlineWriter.cpp, source/adios2/engine/inline/InlineWriter.h, testing/adios2/engine/inline/TestInlineWriteRead.cpp
The inline engine now uses the requested mode to identify the correct reader and writer.
This streamlines the API so that users can more easily swap between engines.
Note: It is not obvious from the diff, but no backwards incompatible changes were made.
=> Identify via mode

docs/user_guide/source/engines/inline.rst, source/adios2/core/IO.cpp, testing/adios2/engine/inline/TestInlineWriteRead.cpp
The inline engine must have exactly one writer, and exactly one reader.
If a user attempts to add multiple readers or multiple writers, throw an exception.
This is a first step towards unifying the engine APIs, since currently we require
the user to specify which engine is the reader with a key.
Enforcing this invariant will allow us to remove the parameter keys, since we will
be able to uniquely identify the reader and writer via their respective modes.
As a bit of unrelated cleanup: throw exceptions when users request unsupported features,
like append mode or sync mode for the inline engine.
=> Enforce invariants for inline engine

source/utils/bpls/bpls.cpp, source/utils/bpls/bpls.h, testing/utils/cwriter/TestUtilsCWriter.bplsh.expected.txt
Go over file content step by step using BeginStep/EndStep loop.
It works with BP3, BP4 and HDF5, and it works with actual producer concurrently but the main purpose is to be able to start listing content from an existing BP4 dataset with huge metadata file that cannot be opened otherwise.
Missing functionality is to print value or minmax of a variable in each step, as this information is not available in the engine/IO object.
=> Bpls -t: read as stream

testing/adios2/engine/bp/TestBPWriteReadAttributes.cpp
See http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r0.html
=> u8 string literals are ill-formed in C++20

source/adios2/engine/dataspaces/DataSpacesWriter.tcc
The DataSpaces engine was failing to build because it expected VariableBase's m_type member to be a string, rather than an object. This uses ToString() the bridge this mismatch.
=> Fix DataSpaces Engine Variable m_Type type mismatch

cmake/DetectOptions.cmake, source/adios2/engine/ssc/SscHelper.cpp, thirdparty/nlohmann_json/nlohmann_json/src/single_include/nlohmann/json.hpp
An urgent request from HBPS project. XGC has been compiled only using PGI compiler, but SSC never tried that because nlohmann::json used to break PGI. 
I just tried on Summit using PGI, and it actually worked. Now let's see if it works with CI.
=> let ssc use pgi compiler

source/adios2/engine/sst/SstReader.cpp, source/adios2/engine/sst/SstReader.h, source/adios2/engine/sst/SstWriter.cpp, source/adios2/engine/sst/SstWriter.h, source/adios2/engine/sst/SstWriter.tcc, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_reader.c, source/adios2/toolkit/sst/cp/cp_writer.c, source/adios2/toolkit/sst/cp/ffs_marshal.c, source/adios2/toolkit/sst/dp/dp.c, source/adios2/toolkit/sst/dp/evpath_dp.c, source/adios2/toolkit/sst/dp/rdma_dp.c, source/adios2/toolkit/sst/dp_interface.h, source/adios2/toolkit/sst/sst_data.h
And be specifiable via the same engine parameter as insitu ("verbose").  The old environment variable, SstVerbose, also still works.  If both are specified with take the greatest as the verbosity level.   @philip-davis Note changes in dp_interface and rdma_dp.
=> Rework SstVerbose to include levels (0-5)

bindings/CXX11/adios2/cxx11/ADIOS.h, examples/hello/sstWriter/helloSstWriter.cpp
Client code that does not enable `ADIOS2_USE_MPI` may accidentally try to pass a `MPI_Comm` instance to our constructor.  If the type the MPI library uses to implement MPI_Comm happens to be convertible to one of the types offered by our serial constructors (e.g. `bool`), the invocation will appear to succeed but will ignore the communicator passed.  Add explicitly deleted constructors that have better conversions for common `MPI_Comm` types.
With this, an attempt in client code to call the `adios2::ADIOS` constructor with a `MPI_Comm` object will fail to compile with an error such as:
error: use of deleted function 'adios2::ADIOS::ADIOS(void*)'
adios2::ADIOS adios(comm);
...note: declared here
ADIOS(void *define_ADIOS2_USE_MPI_to_use_MPI_constructor) = delete;
^~~~~
=> bindings: Help C++11 clients avoid calling serial constructor with MPI_Comm

bindings/Fortran/f2c/adios2_f2c_engine.cpp, testing/adios2/bindings/fortran/TestBPWriteTypes.F90
Addresses #2472    @pnorbert  looks like a terrible oversight from my side, the Fortran bindings need more testing on the read side.
=> Redirect f2c to correct call

source/adios2/toolkit/format/bp/bp4/BP4Serializer.cpp, testing/adios2/engine/bp/TestBPBufferSize.cpp
The BP4 serialization engine maintains the same serialization buffer `format::BP4Serializer` across steps. This allows to avoid heavyweight allocation operations after a certain "warmup" phase. Methods such as [`format::BPBase::ResizeBuffer`](https://github.com/ornladios/ADIOS2/blob/addcb471f0341c93ba7a5f99a1a58a571a374f8a/source/adios2/toolkit/format/bp/BPBase.cpp#L305) support this idea by taking care not to shrink the buffer.
The method [`format::BP4Serializer::SerializeDataBuffer`](https://github.com/ornladios/ADIOS2/blob/addcb471f0341c93ba7a5f99a1a58a571a374f8a/source/adios2/toolkit/format/bp/bp4/BP4Serializer.cpp#L375) (called upon `Engine::EndStep`) does, however, pay no such attention.
This has noticeable consequences in writing to ADIOS2 via openPMD in PIConGPU. (Possibly related …
=> Do not shrink serialization buffer upon EndStep – Fix Performance Bug

docs/user_guide/source/api_full/fortran.rst, docs/user_guide/source/api_full/python.rst
Added documentation for python full API and corrected fortran documentation
=> Documentation

source/adios2/engine/ssc/SscHelper.h, source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/ssc/SscReader.h, source/adios2/engine/ssc/SscReader.tcc, testing/adios2/engine/ssc/TestSscBase.cpp, testing/adios2/engine/ssc/TestSscBaseUnlocked.cpp, testing/adios2/engine/ssc/TestSscLockBeforeEndStep.cpp, testing/adios2/engine/ssc/TestSscOneSidedFencePull.cpp, testing/adios2/engine/ssc/TestSscOneSidedFencePush.cpp, testing/adios2/engine/ssc/TestSscOneSidedPostPull.cpp, testing/adios2/engine/ssc/TestSscOneSidedPostPush.cpp, testing/adios2/engine/ssc/TestSscOnlyOneStep.cpp, testing/adios2/engine/ssc/TestSscOnlyTwoSteps.cpp, testing/adios2/engine/ssc/TestSscReaderMultiblock.cpp, testing/adios2/engine/ssc/TestSscString.cpp, testing/adios2/engine/ssc/TestSscUnbalanced.cpp, testing/adios2/engine/ssc/TestSscVaryingSteps.cpp, testing/adios2/engine/ssc/TestSscWriterMultiblock.cpp
This might be related to the performance bottleneck seen in WarpX reported by @lwan86
=> Fix a performance issue for first step data in ssc

cmake/FindBlosc.cmake
The current check always returned true for the BLOSC_ROOT env var, even if it is unset.
cc @chuckatkins 
Orthogonal to this, I cannot find a `libblosc.lib` install on Windows with this `FindBlosc.cmake` logic - help appreciated.
I already tried setting `CMAKE_PREFIX_PATH='C:/Program Files (x86)/blosc'` and `BLOSC_ROOT='C:/Program Files (x86)/blosc'` but  this still results in:
```
CMake Error at C:/hostedtoolcache/windows/Python/3.7.9/x64/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
Could NOT find Blosc (missing: BLOSC_LIBRARY) (found suitable version
"1.15.0", minimum required is "1.7")
-- Configuring incomplete, errors occurred!
```
The blosc install (static) on Windows looks like this:
```
$  cmake -S dep-blosc/c-blosc-1.15.0 …
```
=> Fix: FindBlosc Env Hint

source/utils/CMakeLists.txt, source/utils/adios_reorganize/bp2h5, source/utils/adios_reorganize/bp2h5_mpi
=> bp2h5: Use copy instead of symlinks because of windows

source/adios2/common/ADIOSTypes.h, source/adios2/operator/compress/CompressBlosc.cpp, source/adios2/operator/compress/CompressBlosc.h, testing/adios2/engine/bp/operations/TestBPWriteReadBlosc.cpp
fix: #2018
The current implementation of the Blosc ADIOS2 operator is due to limitations of Blosc not supporting adios variables larger than 2GiB.
ADIOS1 was originally using a chunked format to work around this limitation.
- Add option `threshold` to set a threshold under which data will only be copied instead of compressed (equivalent to Blosc in ADIOS1).
- Use chunk format to avoid 2GiB limit for variables (datasets).
- Add support to decompress Blosc data written with ADIOS before this PR.
- - update blosc tests
The header written to decompressed the date is different from the ADIOS1 implementation. 
Compared to ADIOS1 this PR implements compression and decompression much cleaner.
@maintainer Where do I should document the new option `threshold` for the Blosc operator. I have not …
=> improve Blosc compression operator

source/adios2/operator/compress/CompressSZ.cpp
In SZ compression, the SZ_Compress and SZ_Decompress functions allocate buffers and return memory pointers, but do not provide an API to release the buffers. They have to be released in ADIOS2 in order to avoid memory leak.
=> fixed a memory leak in SZ compression

source/adios2/operator/compress/CompressMGARD.cpp
The dimensions in mgard operator should be set to [1,1,1] by default rather than [0,0,0]. Otherwise in use cases of less than 3 dimensional data, mgard library will throw exception "all dimensions must be positive".
=> fixed mgard dimensions

source/adios2/operator/compress/CompressMGARD.cpp
These memory pointers are not released anywhere, which cause memory leaks.
=> fixed memory leak in mgard operator

ReadMe.md, docs/user_guide/source/setting_up/package.rst, docs/user_guide/source/setting_up/source/cmake.rst
=> Fix some docs

testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPInquireVariableException.cpp
Check that the reader throws an exception if InquireVariable is outside of the BeginStep/EndStep Block in C++ with FileStream engine.
=> Added a test to address issue 2500

cmake/DetectOptions.cmake
`ADIOS2_USE_Fortran` is `AUTO` by default, so even if no Fortran compiler was found, it'd still try to check a Fortran compiler flag, which failed without a Fortran compiler being enabled:
```
CMake Error at /opt/local/share/cmake-3.19/Modules/Internal/CheckCompilerFlag.cmake:52 (message):
check_compiler_flag: Fortran: needs to be enabled before use.
```
The right thing to use is `ADIOS2_HAVE_Fortran`.
=> prevent cmake failure when no Fortran compiler is present

bindings/C/adios2/c/adios2_c_variable.cpp
For local arrays, `m_Shape` is empty, while `m_Count` is not, so we read off ndims there.
Closes https://github.com/ornladios/ADIOS2/issues/2711
=> WIP: Correct return value of adios2_variable_ndims

source/utils/adios_iotest/settings.cpp
`argCopy`'s allocation did not save space for the `NUL` terminating
byte. Instead of manually calculating memory sizes, use `strdup`.
=> adios_iotest/settings: avoid an off-by-one

bindings/C/adios2/c/adios2_c_types.h
Closes https://github.com/ornladios/ADIOS2/issues/2724.
=> Change type of adios2_local_value_dim to size_t

source/adios2/operator/compress/CompressBlosc.cpp
Warn the user if unknown parameters are passed to the blosc compressor. Otherwise, typos get quickly unnoticed.
cc @psychocoderHPC @franzpoeschel
=> Blosc: Warn Unknown Parameters

source/adios2/helper/adiosComm.inl, source/adios2/helper/adiosNetwork.cpp, source/adios2/toolkit/profiling/taustubs/tautimer.cpp
Closes https://github.com/ornladios/ADIOS2/issues/2705 .
=> Make ADIOS2 build on FreeBSD

source/adios2/operator/compress/CompressBlosc.h
Generalize packed data attributes in the blosc compressor.
Assume (as before) GCC-like attributes, but use MSVC specific syntax when detected.
Related to https://github.com/ornladios/ADIOS2/issues/2745#issue-911752108 / #2592
=> Compress Blosc: Fix MSVC Build

bindings/CXX11/adios2/cxx11/ADIOS.cpp, bindings/CXX11/adios2/cxx11/ADIOS.h, testing/adios2/interface/TestADIOSInterface.cpp
As reported by @khuck , the ADIOS2 C++ API has some unexpected behaviour.  In particular, constructors like this:
adios2::ADIOS adios("config.xml");
Do *not* match with this constructor:
ADIOS(const std::string &configFile, const bool debugMode = true);
Instead, they match with this constructor:
ADIOS(const bool debugMode = true);
Because C++ (at least some compilers) would preferentially convert the "const char*" to "bool", resulting in a config file specification that is silently ignored. For more info see:
https://www.bfilipek.com/2019/07/surprising-conversions-char-bool.html
This PR adds a new entry to the C++ API:
ADIOS(const char *configFile);
And adds a test to make sure that the simple ADIOS("configfile.xml") specification results in an attempt to parse that file, not the …
=> Add const char* entry to ADIOS constructors to avoid ugliness

cmake/FindBlosc.cmake
This fixes static lib build issues for `ppc64le` (manylinux images for Summit/OLCF): https://github.com/openPMD/openPMD-api/pull/1013
```
/opt/rh/devtoolset-9/root/usr/bin/c++ -fPIC -O3 -DNDEBUG CMakeFiles/sst_conn_tool.dir/sst_conn_tool.c.o [...] ../../../../../lib64/libadios2_enet.a ../../../../../lib64/libadios2_taustubs.a -ldl -lpthread /usr/local/lib/libblosc.a /usr/local/lib64/libzfp.a -lm /usr/local/lib/libhdf5.a /usr/lib64/libdl.so /usr/lib64/libm.so 
/opt/rh/devtoolset-9/root/usr/libexec/gcc/aarch64-redhat-linux/9/ld: /usr/local/lib/libblosc.a(blosc.c.o): in function `blosc_init.part.0':
blosc.c:(.text+0x3c4): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
```
Blosc depends unconditionally on threads.
If we are not using the blosc cmake config …
=> FindBlosc.cmake: Threads

source/adios2/common/ADIOSMacros.h, source/adios2/core/Operator.cpp, source/adios2/core/Operator.h, source/adios2/operator/compress/CompressZFP.cpp, testing/adios2/engine/bp/operations/CMakeLists.txt, testing/adios2/engine/bp/operations/TestBPWriteReadZfpComplex.cpp, testing/adios2/engine/dataman/TestDataMan2DZfp.cpp
This PR provides a temporary solution for applications which need lossy compression for complex data types, by treating complex arrays as real arrays. It also supports data arrays larger than 3D by merging some of the slower changing dimensions. 
Again this is only a temporary solution, as a workaround for some of our users. The ultimate solution will depend on the underlying compression algorithms providing native supports.
=> enabled complex types and larger dimensions for ZFP

source/adios2/core/IO.cpp, source/adios2/engine/bp4/BP4Writer.cpp, source/adios2/engine/bp5/BP5Engine.cpp, source/adios2/engine/bp5/BP5Engine.h, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/bp5/BP5Writer.tcc, source/adios2/helper/adiosSystem.cpp, source/adios2/helper/adiosSystem.h, source/adios2/toolkit/format/bp/bp4/BP4Base.cpp, source/adios2/toolkit/format/bp/bp4/BP4Base.h, source/utils/bpls/bpls.cpp
BP4/BP5 write engines now create a .bpversion file immediately at open, which is used to determine what reader engine to use when File, BPFile, FileStream virtual engines are selected. 
-- also turning back aggregation by default to trigger ctest failures
=> Bpversion and fileopen

source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/bp5/BP5Writer.h
Eliminate BP headers in data files (not necessary) and delay writes for Metadata file and Metadata Index file until first EndStep to avoid slowing open.
=> Change header handling in BP5

thirdparty/ffs/ffs/ffs/ffs_conv.c, thirdparty/ffs/ffs/fm/fm_formats.c, thirdparty/ffs/ffs/fm/tests/scale_test.c
create_conversion performance improvements
=> FFS upstream

source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.h
This has the effect of grouping the data blocks that we've had to copy so that we can fit more of them into chunks, rather than the prior approach which would close off a chunk as soon as we saw a large deferred put that we were going to leave in application memory until we were putting the data to disk.
=> Delay adding large Deferred Puts to output vector until last minute

source/adios2/helper/adiosCommMPI.cpp
I am using and MPI library where the MPI error codes (`MPI_ERR_COMM` etc.) are not compile-time constants. If I read the MPI standard (version 3.1, section 2.5.4) correctly, it states that only very few MPI constants are compile-time constants.
ADIOS2 fails to build with this MPI library. This patch changes a `switch` to an `if` statement to remedy this.
=> Use `if` instead of `switch` to check MPI constants

source/adios2/core/CoreTypes.h, source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/bp5/BP5Writer.h, source/adios2/engine/bp5/BP5Writer_TwoLevelShm.cpp, source/adios2/engine/sst/SstWriter.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.h, source/adios2/toolkit/format/buffer/BufferV.h, source/adios2/toolkit/format/buffer/chunk/ChunkV.cpp, source/adios2/toolkit/format/buffer/chunk/ChunkV.h, source/adios2/toolkit/format/buffer/malloc/MallocV.cpp, source/adios2/toolkit/format/buffer/malloc/MallocV.h, source/adios2/toolkit/transport/Transport.cpp, source/adios2/toolkit/transport/Transport.h, source/adios2/toolkit/transport/file/FilePOSIX.cpp, source/adios2/toolkit/transport/file/FilePOSIX.h, source/adios2/toolkit/transportman/TransportMan.cpp, source/adios2/toolkit/transportman/TransportMan.h, testing/h5vol/TestH5VolWriteReadBPFile.cpp
- Clean up BufferV::iovec by using std::vector, and add it to core/CoreTypes. 
- Add vector IO operations to TransportMan::Write(), and a generic loop implementation of Transport::WriteV
- Implement FilePOSIX::WriteV() with using posix writev() with max 8 entries at a time, but keep this turned off since it is not performing better at scale on Summit or Cori after limited testing. The rest of this PR still simplifies using vectorized IO.
=> core::iovec, TransportMan.Write(iovec), Transport:Writev

bindings/C/adios2/c/adios2_c_engine.cpp, bindings/C/adios2/c/adios2_c_engine.h, bindings/C/adios2/c/adios2_c_types.h, testing/adios2/engine/bp/TestBPWriteReadBlockInfo.cpp
adios2_varinfo *adios2_inquire_blockinfo(adios2_engine *engine,
adios2_variable *variable,
const size_t step);
Caveat: Min/Max and Value are not implemented yet, except for string values.
=> Add to C API a function to get blockinfo:

bindings/CXX11/adios2/cxx11/IO.cpp, bindings/CXX11/adios2/cxx11/IO.h, source/adios2/core/IO.cpp, source/adios2/core/IO.h, testing/adios2/engine/dataman/TestDataMan2DBzip2.cpp, testing/adios2/engine/dataman/TestDataMan2DSz.cpp, testing/adios2/engine/dataman/TestDataMan2DZfp.cpp
The original IO::AddOperation function was not implemented to a workable level. While the XML API provides a purely parameter configurable operator addition mechanism, the non-XML API should also provide an equivalent way of adding operators by only passing std::string based parameters. 
This is important to applications which are very expensive to modify. With the previous Variable::AddOperation being the only way, user applications have to be modified every time there is a change in the operators or a new operator is implemented. Being able to add arbitrary operators to arbitrary variables by only passing pure std::string based parameters can save huge amount of effort maintaining such application codes.
=> implemented IO::AddOperation

bindings/CXX11/adios2/cxx11/Variable.cpp, bindings/CXX11/adios2/cxx11/Variable.h, source/adios2/core/VariableBase.cpp, source/adios2/core/VariableBase.h, testing/adios2/engine/bp/operations/CMakeLists.txt, testing/adios2/engine/bp/operations/TestBPWriteReadZfpRemoveOperations.cpp
Add API function in C++ `Variable<T>::RemoveOperations();` to allow for on and off compression
Add ZFP tests
Related to #2867
=> Remove operations

docs/user_guide/source/setting_up/source/hpc_systems.rst
Prior 'build on HPC' info didn't cover RDMA.
=> Add a little bit of documentation for RDMA builds

cmake/DetectOptions.cmake, source/adios2/common/ADIOSTypes.h, source/adios2/operator/compress/CompressZFP.cpp, source/adios2/operator/compress/CompressZFP.h, testing/adios2/engine/bp/operations/CMakeLists.txt
In the previous PR #2920 which added among other things tests for ZFP with CUDA it does not check if the current ZFP installation supports ZFP. 
For this purpose I added a PR at the ZFP which adds a parameter to see this (https://github.com/LLNL/zfp/pull/147).
While this has been merged to keep compatibility to previous commits of ZFP I added some logic at our cmake code to figure out if we have ZFP_CUDA.
__EDITED__
I made some refactor at the compressZFP so that it moves out the include from the header to the implementation file, also I changed some of the defines provide from ZFP to more stable ones. 
I also made the code compatible for ZFP 0.5.1 (the one that we publicly support) to 0.5.5 (latest).
=> CMAKE: add check for ZFP_CUDA

CMakeLists.txt, bindings/CXX11/adios2/cxx11/Variable.h, docs/user_guide/source/components/engine.rst
1. Cmake output for the cuda architecture will (hopefully) prevent users from trying to run on a different architecture than the default one (set to V100 for Summit runs) without setting the correct `CMAKE_CUDA_ARCHITECTURES`
2. Minimal text on the limitations and how to device buffers for readthedocs
=> Adding documentation for using Cuda buffers

source/adios2/CMakeLists.txt, source/adios2/core/Engine.h, source/adios2/engine/bp3/BP3Reader.cpp, source/adios2/engine/bp3/BP3Writer.cpp, source/adios2/engine/bp4/BP4Reader.cpp, source/adios2/engine/bp4/BP4Reader.h, source/adios2/engine/bp4/BP4Writer.cpp, source/adios2/engine/bp4/BP4Writer.h, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/dataman/DataManReader.cpp, source/adios2/engine/dataman/DataManWriter.cpp, source/adios2/engine/hdf5/HDF5ReaderP.cpp, source/adios2/engine/hdf5/HDF5WriterP.cpp, source/adios2/engine/inline/InlineReader.cpp, source/adios2/engine/inline/InlineWriter.cpp, source/adios2/engine/skeleton/SkeletonReader.cpp, source/adios2/engine/skeleton/SkeletonWriter.cpp, source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/ssc/SscReader.tcc, source/adios2/engine/ssc/SscWriter.cpp, source/adios2/engine/ssc/SscWriter.h, source/adios2/engine/ssc/SscWriter.tcc, source/adios2/engine/sst/SstReader.cpp, source/adios2/helper/adiosFunctions.h, source/adios2/helper/adiosLog.cpp, source/adios2/helper/adiosLog.h
For long time we have only had arbitrarily styled runtime output. Some of them are very ambiguous and uninformative. This PR is the start of an attempt to have a more unified and finer-grained output style, which at least let users know the outputs are from ADIOS2 rather than some thirdparty libraries, and have some ideas which layer of ADIOS2 they are from. 
Some basic example outputs that have been implemented are:
```
[Wed Nov 17 02:27:02 2021] [ADIOS2 Output] [Rank 0] <Engine> <BP4Writer> <Open> : myVector_cpp.bp
[Wed Nov 17 02:27:02 2021] [ADIOS2 Output] [Rank 0] <Engine> <BP4Writer> <PutDeferred> : bpFloats
[Wed Nov 17 02:27:02 2021] [ADIOS2 Output] [Rank 0] <Engine> <BP4Writer> <PutDeferred> : bpInts
[Wed Nov 17 02:27:02 2021] [ADIOS2 Output] [Rank 0] <Engine> <BP4Writer> <Close> : …
```
=> Add adiosLog in helper for better looking output

cmake/FindDAOS.cmake
In the original FindDAOS.cmake file there is a condition 
if(CMAKE_VERSION VERSION_LESS 3.12)
which assumes that if cmake version is newer than 3.12 then it should be able to automatically find DAOS library. However, cmake 3.21 does not seem to find the DAOS library at all even for a DAOS installation in /usr/local. By removing this condition, any cmake version is now able to find DAOS automatically.
=> modify daos cmake file to make it find daos library more easily

source/adios2/core/Operator.h, source/adios2/operator/compress/CompressBZIP2.cpp, source/adios2/operator/compress/CompressBlosc.cpp, source/adios2/operator/compress/CompressLibPressio.cpp, source/adios2/operator/compress/CompressMGARD.cpp, source/adios2/operator/compress/CompressPNG.cpp, source/adios2/operator/compress/CompressSZ.cpp, source/adios2/operator/compress/CompressSirius.cpp, source/adios2/operator/compress/CompressZFP.cpp, source/adios2/operator/compress/CompressorFactory.cpp
This is to avoid naming conflicts with the macros defined in compression libraries. For example, SZ library defines a universal macro SZ, which, in some compiling environments, has a conflict with OperatorType::SZ.
=> rename OperatorType enum

bindings/CXX11/adios2/cxx11/Variable.cpp, bindings/Python/py11Variable.cpp, source/adios2/core/VariableBase.cpp, source/adios2/core/VariableBase.h, source/adios2/toolkit/format/bp/BPSerializer.h, source/adios2/toolkit/format/bp/BPSerializer.tcc
This PR is to further refine the Operator framework. The original design of using a map<string, string> Info to hold operation metadata and intermediate results was very inefficient and confusing, as it needs to expose those intermediate results and compressor metadata everywhere, and every time it is used, it has to be cast from string to numbers back and forth, which does not make any sense.
With the self-contained compression buffer, now BP5, as well as any future engines and serializers, can handle this logic within a few lines of code, whereas in the original BPOperation, it needs a whole class, making it extremely hard for future engine / serializer developers to understand how it works. So it is now removed.
=> Removed the Info map from VariableBase::Operation

source/adios2/core/Engine.tcc, testing/adios2/engine/bp/TestBPWriteReadVariableSpan.cpp
`Variable<T>::Span Engine::Put` with existing Variable Operations currently not supported as specified in the [docs](https://adios2.readthedocs.io/en/latest/components/components.html?highlight=Span#put-modes-and-memory-contracts). 
This PR adds an exception with error friendly message to this use case.
Prevents faulty data as reported in #2965
CC: @franzpoeschel
=> Add exception for unsupported Operation with Variable<T>::Span Engine::Put Signature

CMakeLists.txt
Fixes: #2979
The issue was that we were only compiling for physical archs higher than our computers arch.
We must let the users to specify the CUDA arch passing `-DCMAKE_CUDA_ARCHITECUTRES="xxyyzz"` 
When it comes to decide for a good default arch, `compute_52` is the oldest non-deprecated CUDA virtual architecture, thus, is a good candidate for a base architecture to support. Setting this as the default `CMAKE_CUDA_ARCHITECTURE` arch resolves the error with the CUDA unit tests.
@JasonRuonanWang
=> CUDA: set MAXWELL as the default architecture

examples/cuda/cudaWriteRead.cu, source/adios2/engine/bp5/BP5Writer.tcc, source/adios2/helper/adiosMemory.h, source/adios2/helper/adiosMemory.inl, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, source/adios2/toolkit/format/buffer/BufferV.h, source/adios2/toolkit/format/buffer/chunk/ChunkV.cpp, source/adios2/toolkit/format/buffer/chunk/ChunkV.h, source/adios2/toolkit/format/buffer/malloc/MallocV.cpp, source/adios2/toolkit/format/buffer/malloc/MallocV.h
No span or operations for now.
=> Base modifications to make BP5 GPU aware

source/adios2/helper/adiosMemory.inl, source/adios2/toolkit/transport/file/FileIME.cpp
This is to fix the following compile error with GCC 9
```
/home/jason/d/a2/source/adios2/toolkit/transport/file/FileIME.cpp:33:45: error: use of deleted function ‘std::atomic<unsigned int>::atomic(const std::atomic<unsigned int>&)’
33 | std::atomic_uint FileIME::client_refcount = 0;
|                                             ^
In file included from /home/jason/d/a2/source/adios2/toolkit/transport/file/FileIME.h:14,
from /home/jason/d/a2/source/adios2/toolkit/transport/file/FileIME.cpp:10:
/usr/include/c++/9/atomic:778:7: note: declared here
778 |       atomic(const atomic&) = delete;
|       ^~~~~~
/usr/include/c++/9/atomic:782:17: note:   after user-defined conversion: ‘constexpr std::atomic<unsigned int>::atomic(std::atomic<unsigned int>::__integral_type)’
782 |       constexpr …
```
=> fix gcc9 compile error for ime transport

cmake/DetectOptions.cmake
I tried to replicate error message when trying to find CUDA in the CI machines, I found this cmake message:
```
-- Could not find nvcc, please set CUDAToolkit_ROOT
```
@pnorbert I wonder if this is the error message that you mentioned earlier, if so, this MR silence this if the user has not set `ADIOS2_ENABLE_CUDA=ON`
=> CMAKE: silence find_package(CUDA)

source/adios2/helper/adiosCUDAReduceImpl.h
This PR fixes an issue that causes the min value not to be correctly calculated using CUDA. When ADIOS is linked with the CUDA version of ZFP and the CUDA version of MGARD, the following tests can pass:
```
jieyang@jieyang-Thelio:~/dev/ADIOS2/build$ ctest -R CUDA
Test project /home/jieyang/dev/ADIOS2/build
Start 883: Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.Serial
1/2 Test #883: Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.Serial ...   Passed    0.77 sec
Start 884: Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.MPI
2/2 Test #884: Engine.BP.*/BPWRZFPCUDA.ADIOS2BPWRZFPCUDA/*.BP4.MPI ......   Passed    2.20 sec
100% tests passed, 0 tests failed out of 2
Total Test time (real) =   3.01 sec
```
```
jieyang@jieyang-Thelio:~/dev/ADIOS2/build$ ctest -R MGARD
Test project …
```
=> Fix bug in calculating min values using CUDA

examples/cuda/CMakeLists.txt, examples/cuda/cudaWriteRead.cu, source/adios2/CMakeLists.txt, source/adios2/core/VariableBase.cpp, source/adios2/helper/adiosMemory.cpp, testing/adios2/engine/bp/operations/CMakeLists.txt, testing/adios2/engine/bp/operations/CudaRoutines.h, testing/adios2/engine/bp/operations/TestBPWriteReadZfpCuda.cpp
The CUDA dependency must be private so that it does not propagate.
=> CUDA: set CUDA dependencies private

examples/cuda/cudaWriteRead.cu, scripts/ci/scripts/run-clang-format.sh
I tested that this still format C,C++ files by intentionally adding a commit which introduce format mistakes. The checks for that commit is here:
https://github.com/ornladios/ADIOS2/pull/3011/checks?sha=20ad1d499df3b051d0543bce71c7b3c4a717cfbb
=> clang-format: format cu files

source/adios2/toolkit/transport/file/FileFStream.cpp
@pnorbert 
#3020 introduced compile errors which CI didn't catch. This PR is to fix those errors.
=> fix compile error newly introduced

examples/cuda/cudaWriteRead.cu, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.h
Testing includes Deferred and Sync modes for buffers with continuous allocated memory on the GPU. We need to add CI for this in the future.
Still needs implementation and testing for all other corner cases (Random access, non-continuous buffers, single values (? would applications really used this on the GPU?), etc.)
=> Base modifications to make BP5 GPU aware on the Read side

source/adios2/helper/adiosMemory.cpp, source/adios2/helper/adiosMemory.h, source/adios2/helper/adiosMemory.inl, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
Bug fix to copy the data correctly to the GPU buffer. I also renamed some of the functions and variables so it's easier to read the code and differentiate between moving data to and from the GPU buffer.
The CUDA tests (from #3028) are passing now.
=> Bug fix for BP5 using cuda buffers with Get

source/adios2/helper/adiosMemory.h, source/adios2/helper/adiosMemory.inl, source/adios2/toolkit/format/bp/bp4/BP4Deserializer.tcc
While testing BP5 and BP4 with GPU I realized I forgot to push the changes to make the read side of BP4 CUDA aware. 
I will update the Testing function to include BP4 in the tests so we can officially test GPU buffers, but so far this code passed my offline tests.
=> BP4 GPU aware for Get calls

bindings/C/adios2/c/adios2_c_engine.cpp, bindings/C/adios2/c/adios2_c_engine.h
Added a help function for C API to deallocate the block info structure allocated by the adios2_inquire_block_info function.
=> Added a help function for C API to deallocate block info structure.

docs/user_guide/source/advanced/gpu_aware.rst, docs/user_guide/source/components/engine.rst, source/adios2/common/ADIOSTypes.h
+ small changes in the code comments
=> Documentation for GPU-aware BP4 and BP5

source/adios2/engine/bp5/BP5Engine.h, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/bp5/BP5Writer.h, source/utils/bp5dbg/adios2/bp5dbg/idxtable.py, source/utils/bpls/bpls.cpp
1+8 byte for recordID + record length, then content. recordID 's' for Steps, 'w' for writer map
Writer map always PRECEEDS the step record where it was recorded.
=> BP5 index format is now record-based: 

source/adios2/engine/bp5/BP5Engine.cpp, source/adios2/engine/bp5/BP5Engine.h
(e.g. nUmaggReGatoRs is NumAggregators). Set NumSubFiles default to 0 as other default sets NumAggregators in BP5Writer::InitParameters()
=> Find and accept parameters CASE INSENSITIVE 

source/adios2/CMakeLists.txt, source/adios2/engine/ssc/SscHelper.cpp, source/adios2/engine/ssc/SscHelper.h, source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/ssc/SscReaderGeneric.cpp, source/adios2/engine/ssc/SscReaderGeneric.tcc, source/adios2/engine/ssc/SscReaderNaive.cpp, source/adios2/engine/ssc/SscReaderNaive.h, source/adios2/engine/ssc/SscReaderNaive.tcc, source/adios2/engine/ssc/SscWriter.cpp, source/adios2/engine/ssc/SscWriterGeneric.h, source/adios2/engine/ssc/SscWriterGeneric.tcc, source/adios2/engine/ssc/SscWriterNaive.cpp, source/adios2/engine/ssc/SscWriterNaive.h, source/adios2/engine/ssc/SscWriterNaive.tcc, testing/adios2/engine/ssc/TestSsc7d.cpp, testing/adios2/engine/ssc/TestSscBase.cpp, testing/adios2/engine/ssc/TestSscSingleStep.cpp, testing/adios2/engine/ssc/TestSscSuperLarge.cpp, testing/adios2/engine/ssc/TestSscUnbalanced.cpp, testing/adios2/engine/ssc/TestSscVaryingSteps.cpp, testing/adios2/engine/ssc/TestSscWriterMultiblock.cpp, testing/adios2/engine/ssc/TestSscXgc2Way.cpp, testing/adios2/engine/ssc/TestSscXgc3Way.cpp, testing/adios2/engine/ssc/TestSscXgc3WayMatchedSteps.cpp
NAIVE mode in SSC is implemented for use cases where a huge number of writers need to send data to a small number of readers, and the entire global data arrays can fit into the system memory of a single rank. 
In these scenarios, metadata and data can be aggregated within a single MPI collective call. The entire workflow only uses ordinary MPI function calls, no one-sided MPI needed. All these simplifications will largely improve SSC's scalability on world's leading computing facilities.
=> Added naive engine mode for SSC

bindings/CXX11/adios2/cxx11/Attribute.cpp, bindings/CXX11/adios2/cxx11/Attribute.h, testing/adios2/interface/TestADIOSDefineAttribute.cpp
This already exists in the [C bindings](https://adios2.readthedocs.io/en/latest/api_full/api_full.html#_CPPv425adios2_attribute_is_valueP11adios2_boolPK16adios2_attribute), but apparently not yet in the C++ bindings.
This PR adds a C++ binding.
=> Add C++ binding for distinguishing scalar from vector attributes

source/adios2/operator/compress/CompressSZ.cpp, source/adios2/operator/compress/CompressSZ.h, testing/adios2/engine/dataman/TestDataMan2DSz.cpp
The SZ 1.x library does not provide a thread-safe API. This PR is to add a mutex at the ADIOS2 SZ operator layer to prevent unpredictable behaviors when multiple threads use SZ compressor simultaneously.
=> added mutex in sz operator

bindings/CXX11/adios2/cxx11/Engine.h, bindings/CXX11/adios2/cxx11/Group.h, bindings/CXX11/adios2/cxx11/IO.h, bindings/CXX11/adios2/cxx11/Types.h, bindings/CXX11/adios2/cxx11/Variable.h
These template instantiations only need to be in cpp files. No need to put in header files.
=> remove template instantiation in header files

bindings/CXX11/adios2/cxx11/Attribute.h, bindings/CXX11/adios2/cxx11/Variable.h
Building a C++20 library against ADIOS2 fails with GCC 11.2.0. This PR allows compilation without fatal errors. An explanation of what has been tightened in the C++ standard is at https://stackoverflow.com/questions/63513984/can-class-template-constructors-have-a-redundant-template-parameter-list-in-c2.
See also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97202.
=> Syntax fix in declarations for C++20 compliance

cmake/DetectOptions.cmake, source/adios2/toolkit/format/dataman/DataManSerializer.cpp, source/adios2/toolkit/format/dataman/DataManSerializer.h
Fixes #3151
It seems that GCC 10 handles template instantiation differently from previous GCC versions, and as a result, some template instantiation in DataMan serializer failed to pick up the correct template instantiation. This PR changed the affected template instantiation to simple function overloading.
=> Fix a template instantiation issue with GCC 10 in dataman serializer

thirdparty/enet/enet/CMakeLists.txt
Going ahead and pulling in ENET upstream so that you don't get a stream of errors on every build from the doxygen run.
=> ENET upstream

docs/user_guide/source/index.rst, docs/user_guide/source/operators/ZFPCompressor.rst, docs/user_guide/source/operators/operators.rst
=> docs: added operators and zfp section

examples/hello/bpTimeWriter/helloBPTimeWriter.py
The helloBPTimeWriter python example was not working on my system. Made a few small changes and got it working, and the output file contains the expected numbers.
=> Fix helloBPTimeWriter Python example.

bindings/CXX11/CMakeLists.txt, bindings/CXX11/adios2/cxx11/Engine.cpp, bindings/CXX11/adios2/cxx11/Engine.h, bindings/CXX11/adios2/cxx11/IO.cpp, bindings/CXX11/adios2/cxx11/IO.h, bindings/CXX11/adios2/cxx11/IO.tcc, bindings/CXX11/adios2/cxx11/Operator.h, bindings/CXX11/adios2/cxx11/Variable.cpp, bindings/CXX11/adios2/cxx11/Variable.h, bindings/CXX11/adios2/cxx11/VariableNT.cpp, bindings/CXX11/adios2/cxx11/VariableNT.h, testing/adios2/engine/bp/TestBPWriteReadVector.cpp
Since long time, users have been struggling with the templated C++ API of ADIOS2. It makes things unnecessarily hard for users to define and use ADIOS2 variables with data types that are only determined at runtime. It makes things even harder for users who want to put variable objects of different data types into a single container. 
It's time to correct this harmful C++ fundamentalism. A C++ code does not have to use templates. Whether to use templates should be determined in a case by case manner. 
This PR adds a template-free C++ API, which should be recommended for most use cases instead of the templated API. Some parts of it is currently still built on top of the templated API, but we should aim to remove most of the templated implementations in ADIOS2 core so we will save a huge lot …
=> Add template-free C++ API 

source/adios2/core/Variable.cpp, source/adios2/core/Variable.h, source/adios2/core/Variable.tcc, source/adios2/core/VariableBase.cpp, source/adios2/core/VariableBase.h
Variable<T>::Shape() does not use any templated types so there is no point to make it templated
=> moved Variable<T>::Shape() to VariableBase

bindings/CXX11/adios2/cxx11/VariableNT.cpp, source/adios2/core/VariableBase.cpp, source/adios2/core/VariableBase.h, source/utils/adios_reorganize/Reorganize.cpp
The implementation of Variable::Shape() was so extremely complicated. There were
Variable<T>::Shape()
Variable<T>::DoShape()
Variable<T>::GetShape()
These functions basically do a very simple thing in a crazy incomprehensible way, resulting in tens of functions in the virtual table, whereas the functionality itself can be easily implemented in one single non-templated function. 
This PR, together with the previous PR, removes such a weird implementation, as part of our effort to fully remove templates in adios2::core.
=> removed VariableBase::GetShape

bindings/CXX11/adios2/cxx11/Variable.h, bindings/CXX11/adios2/cxx11/VariableNT.cpp
This function in the Variable API class seems like it should be a private function, instead of public. It accepts a pointer parameter defined in adios2::core, which is not supposed to be exposed to users in any situation. From the API logic and the context, I only see cases in which it is called from inside the API classes, not from users.
=> moved ToBlocksInfoMin to private

bindings/CXX11/adios2/cxx11/Engine.cpp, bindings/CXX11/adios2/cxx11/Engine.h, bindings/CXX11/adios2/cxx11/VariableNT.h, source/adios2/core/Engine.cpp, source/adios2/core/Engine.h, source/adios2/engine/ssc/SscReader.cpp, source/adios2/engine/ssc/SscReader.h, source/adios2/engine/ssc/SscReaderBase.h, source/adios2/engine/ssc/SscReaderGeneric.cpp, source/adios2/engine/ssc/SscReaderGeneric.h, source/adios2/engine/ssc/SscReaderGeneric.tcc, source/adios2/engine/ssc/SscReaderNaive.cpp, source/adios2/engine/ssc/SscReaderNaive.h, source/adios2/engine/ssc/SscReaderNaive.tcc, testing/adios2/engine/ssc/TestSscStruct.cpp
This is still based on the templated API, for apps that need to use in near future. But in the long run, we should aim to implement a non-template BlocksInfo from the API layer down to adios2::core. The current API layer is extremely inefficient in the sense that it needs to traverse every single BlockInfo element for a deep copy from adios2::core to the API objects. This causes ridiculous performance loss for apps that have a large number of blocks and need to call BlocksInfo frequently. It REALLY should be implemented so that we can use a single memcpy() to copy an entire block. Even if it means that we always need to reserve memory space for the largest possible data type, it will still be much more efficient in block intensive workflows.
=> added BlocksInfo API for VariableNT, and implementation for VariableStruct in SSC

bindings/CXX11/adios2/cxx11/VariableNT.cpp, bindings/CXX11/adios2/cxx11/VariableNT.h, source/adios2/core/IO.cpp, source/adios2/core/IO.h, source/adios2/core/VariableStruct.cpp, source/adios2/core/VariableStruct.h, testing/adios2/engine/ssc/TestSscStruct.cpp, testing/adios2/interface/TestADIOSDefineVariable.cpp
Since multiple struct variables can use one struct definition, there needs a freeze feature to finalize a struct definition, so that it ensures the struct definition is not changed in between defining different variables. 
This function can be called from the user code. Even if users don't call it, it will still automatically freeze when the first variable is being created using a struct definition.
=> added freeze function to StructDefinition

docs/user_guide/source/engines/bp5.rst, source/adios2/engine/bp5/BP5Engine.h, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Reader.h, source/adios2/engine/sst/SstReader.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.h, source/utils/adios_reorganize/Reorganize.h
Threads now dynamically pick read tasks one by one from the same queue of requests
=> Bp5 multithreaded read, dynamic version

source/adios2/engine/bp5/BP5Reader.cpp, testing/adios2/engine/bp/TestBPWriteReadMultiblock.cpp
cherry-picked 08990a8ae6a4d1 from 2.8.1 and 
manually brought in fixes from 2.8.1
=> Merge bp5 flush read from 281

bindings/CXX11/adios2/cxx11/Attribute.h, bindings/CXX11/adios2/cxx11/Variable.h, source/adios2/core/Attribute.h
=> fix api for gcc11

source/adios2/toolkit/transport/file/FileDaos.cpp
DAOS 2.0 requires different parameters for DAOS functions. Code can be build on Presque now.
=> Changed parameters for DAOS API functions.

source/h5vol/H5VolReadWrite.c, source/h5vol/H5VolReadWrite.h, source/h5vol/H5Vol_dataset.c, testing/h5vol/TestH5VolWriteReadBPFile.cpp
There are some signature changes in 1.13 and the VOL was written around hdf5 1.12.   A few changes needs to make in order for tests to succeed. 
Notice the current VOL is using BP4, and the memory selection is handled only in BP5.  It requires memory selection to have the same dimension as the global dimension. While HDF5 does not have such limitation.
=> Necessary revision to get VOL work HDF5 1.13 & BP4

source/adios2/core/Engine.cpp, source/adios2/core/Engine.h, source/adios2/engine/bp3/BP3Reader.cpp, source/adios2/engine/bp4/BP4Reader.cpp, source/adios2/engine/sst/SstReader.cpp, source/adios2/toolkit/format/bp/bp3/BP3Deserializer.tcc, source/adios2/toolkit/format/bp/bp4/BP4Deserializer.tcc, source/adios2/toolkit/sst/cp/cp_common.c, testing/adios2/engine/staging-common/TestCommonRead.cpp, testing/adios2/interface/TestADIOSInterface.cpp
Extending prior PR to BP3/4...
Note:  The test here checks to see if a variable created by reader BeginStep gets deleted in Reader::Close().  I'd like to test to make sure that non-created variables remain available, but that isn't really possible because for some engines, InqVar simply doesn't work under any circumstances for such variables.  This is because of the interwoven nature of the logic and the need to return NULL for an otherwise valid variable if the IO is in "streaming read mode" and there is no valid data for that timestep.  So for now, simply not testing that part as the tangle is too broken to fix.
However, this PR introduces Engine-class methods to RegisterCreatedVariable() and RemoveCreatedVars() so that reader engines can more easily clean up after themselves.  I've …
=> Destroy only created vars on BeginStep and again on Reader close

source/adios2/engine/inline/InlineWriter.cpp
Previously we were requiring that when an inline writer is created and inline reader must be created before the writer can start BeginStep. I was able to work around that when getting ADIOS/Fides to work with Catalyst for batch in situ processing, but for Catalyst Live (interactive in situ) I can't work around it. I need to be able to create the reader a bit later than is currently possible. 
With this and a small fix in VTK, Catalyst Live is working! Still needs more testing of some different situations, but overall it ended up being a lot easier to get working than I expected. @pnorbert I can demo it with gray scott at Tuesday's meeting if you'd like to see it. 
@chuckatkins Is it good to merge this into release and do another patch release?
=> Allow an inline writer to be created and used without an inline reader

source/adios2/toolkit/sst/dp/mpi_dp.c
Multiple changes are contained in this commit:
- Adoption of BSD Queues instead of custom made linked-lists. BSD Queues are readily available in:
- Every Linux distro.
- macOS.
- Windows using cygwin as we already require.
- Fixed minor memory leaks on StreamWSR destruction.
- Used of linked-lists in often-insertion/no-random-access scenarios.
- Removed unneeded dynamic allocated variables.
- Finer grain lock/mutex usage.
- Added multiple comments and diagram.
- Renamed most of the data structures for better consistency.
- Rearranged function order in the file to better follow its execution.
Tested in:
=> MPI_DP: Optimize scalable component

scripts/ci/gh-actions/macos-setup.sh
Cmake 3.24 deprecated some features that are used in our install test. This MR fix the CMake used for MacOS build to 3.23.3.
This is a temporary fix, final fix is being tracked here: https://github.com/ornladios/ADIOS2/issues/3309
=> ci: fix macos install test missing deps

source/adios2/engine/sst/SstReader.cpp, source/adios2/toolkit/format/bp/bp3/BP3Deserializer.tcc, testing/adios2/engine/staging-common/CMakeLists.txt, testing/adios2/engine/staging-common/ParseArgs.h, testing/adios2/engine/staging-common/TestCommonReadAttrs.cpp, testing/adios2/engine/staging-common/TestCommonWriteAttrs.cpp, testing/adios2/engine/staging-common/TestSupp.cmake
Addresses #3298, but not for BP3/4 file and streaming-through-file engines.  A test is added to staging-common.
=> Modifiable attributes for staging and BP5

source/adios2/toolkit/sst/dp/mpi_dp.c
This PR prints the MPI initialization warning on rank 0 of the world comm instead of all ranks.
@vicentebolea
=> SST with MPI dataplane: only print MPI initialization warning on rank 0

source/utils/CMakeLists.txt, source/utils/bpls/bpls.cpp
This fixes the error:
```
ld.exe: source/utils/CMakeFiles/bpls.dir/bpls/bpls.cpp.obj:bpls.cpp:(.text+0x67994): undefined reference to '__imp_PathMatchSpecA'
```
=> utils: Fix bpls linking in Windows

source/adios2/helper/adiosComm.inl, source/adios2/toolkit/aggregator/mpi/MPIShmChain.cpp
Added error checks in Comm send/recv functions to throw an error in case of bad source/dest.
fixes #3344
=> Handshake fix: rank 0 should receive msg from last rank, not from -1.

cmake/install/post/generate-adios2-config.sh.in, scripts/ci/gh-actions/macos-setup.sh, scripts/ci/images-v2/packages.yaml.in, testing/install/Fortran/CMakeLists.txt
fixes #3348 
fixes #3335
fixes #3309
=> CMAKE: Support cmake 3.24

source/adios2/toolkit/sst/cp/cp_internal.h, source/adios2/toolkit/sst/cp/cp_writer.c, testing/adios2/engine/staging-common/TestDistributionRead.cpp, testing/adios2/engine/staging-common/TestDistributionWrite.cpp
This mod excludes the timestep that is currently being processed in ProvideTimestep() from consideration for transmission in the RequestTimestep handler.  This resolves a race condition where the "in-the-queue-but-not-quite-complete" timestep might be sent out OnDemand before it's ready because it looks to the handler like it's the next one to be requested OnDemand.  Instead, the handler will queue its request and let ProvideTimestep() proceed as normal.  This obviates the need for the prior race condition patch because ProvideTimestep() will never find that the step it is working on has been sent out before it's done.
This patch also includes changes to the TestDistributionRead/Write in their OnDemand sections which were previously unused.  Those tests are now suitable for running on the …
=> Fix race condition in OnDemand delivery

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.h
In general in ADIOS, writers populate portions of a virtual multidimensional variables logically decomposed across writer ranks and readers request multidimensional slices out of that space.  Each block of each writer's contribution was contiguous (or made contiguous) when it was written, and each readers completed request will end up being contiguous in reader memory, but because a reader request might pull data from multiple writer blocks or involve only a subset of a block, filling a read request often involves non-contiguous transfers.  That is, sections of a writer block that were contiguous in that block end up being non-contiguous in the reader destination, and vice versa.  Because of this BP5 was conservative, always reading data into a temporary buffer and then slicing it into …
=> BP5 read direct to application memory (1 dimensional case)

testing/adios2/engine/bp/operations/TestBPWriteReadPNG.cpp
This error doesn't always seem to pop up in CI, but trying a fix regardless.
=> WIP:  Fix untyped conversion in PNG operator test

.github/workflows/everything.yml
CI: Workaround for Windows builds 20221120.1
- Observed in windows-2022 and windows 2019 version 20221120.1
- It is a known issue on how CMake 3.25 discovers static libraries.
- It consists in CMake wrongly picking static libraries from the Perl
Strawberry distribution.
Upstream issue:
- https://github.com/actions/runner-images/issues/6627
This will be resolved in the incoming CMake 3.25.1 which will be eventually included in one of the next windows Github-hosted images
=> CI: Workaround for Windows builds 20221120.1

.github/workflows/everything.yml
This reverts commit 3bd90769e05c66600710c0182d96a973f98c1561.
Revers #3394
The above commit was a workaround for a problem that has been resolved in the GitHub runner Windows images.
Upstream resolved issue: https://github.com/actions/runner-images/issues/6627
=> Revert "CI: Workaround for Windows builds 20221120.1"

source/adios2/core/IO.cpp, source/adios2/core/IO.h, source/adios2/engine/ssc/SscHelper.cpp, source/adios2/engine/ssc/SscHelper.h, source/adios2/engine/ssc/SscReaderBase.h, source/adios2/engine/ssc/SscReaderGeneric.cpp, source/adios2/engine/ssc/SscReaderNaive.cpp, source/adios2/engine/ssc/SscWriterGeneric.cpp, source/adios2/engine/ssc/SscWriterGeneric.h
This is a step towards a broader rework of struct handling.  (Jason, review if you can, but this is mostly moving the structure map internal so that I don't break Ssc with future changes.
=> Move Ssc-internal struct manipulation to Ssc-Internal Maps

bindings/CXX11/adios2/cxx11/VariableNT.cpp, bindings/CXX11/adios2/cxx11/VariableNT.h, source/adios2/common/ADIOSTypes.cpp, source/adios2/common/ADIOSTypes.h, source/adios2/core/IO.cpp, source/adios2/core/VariableStruct.cpp, source/adios2/core/VariableStruct.h, source/adios2/engine/ssc/SscHelper.cpp, source/adios2/engine/ssc/SscWriterGeneric.cpp, source/adios2/engine/ssc/SscWriterNaive.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, testing/adios2/engine/ssc/TestSscStruct.cpp, testing/adios2/engine/staging-common/TestStructRead.cpp, testing/adios2/engine/staging-common/TestStructWrite.cpp, testing/adios2/interface/TestADIOSDefineVariable.cpp
More clean up of pending PRs.  This is largely cosmetic.  Where the prior struct interface called the components of a user-defined structure "items" (and had methods named appropriately), this PR now calls them "fields".  Also, it changes the name of a property of a field that I had initially misinterpreted.   The "Size" parameter to "AddItem" was used to define statically sized array fields (not to give the overall size of the field).  This has been changed to "ElementCount", and the BP5 implementation of structs changed to match this interpretation of that parameter.  Tests have also been changed to use the "offsetof()" macro rather than assuming _a priori_ knowledge of compiler-assigned field offsets.
The details of this are open to change.  Maybe "Member" instead of "Field"?  Maybe …
=> Rename some portions of Struct interface

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
The BP5 tests do not pass for contiguous buffers because the `IsContiguousTransfer` function returns true regardless of the buffer memory space. The bug appears after PR #3387.
@eisenhauer you mention that you made sure to avoid the case of GPU buffers but I cannot find any code for this. Maybe it was removed later, but in the current form, all the GPU tests with BP5 are failing.
=> GPU buffers will never bypass the ADIOS internal buffers

bindings/CXX11/adios2/cxx11/ADIOS.cpp, bindings/CXX11/adios2/cxx11/ADIOS.h, bindings/CXX11/adios2/cxx11/IO.cpp, bindings/CXX11/adios2/cxx11/IO.h, source/adios2/core/ADIOS.cpp, source/adios2/core/ADIOS.h, source/adios2/core/IO.cpp, source/adios2/core/IO.h, source/adios2/engine/ssc/SscWriterGeneric.cpp, source/adios2/engine/ssc/SscWriterNaive.cpp, testing/adios2/engine/ssc/TestSscStruct.cpp, testing/adios2/engine/staging-common/TestStructRead.cpp, testing/adios2/engine/staging-common/TestStructWrite.cpp, testing/adios2/interface/TestADIOSDefineVariable.cpp
Essentially this PR:
1. Moves DefineStruct from the ADIOS to the IO class in the bindings, but maintains the ADIOS as the owner of the object (to facilitate using StructDefinitions in multiple IOs.)
2. Eliminates InquireStruct (lookup struct definition by name) from the external bindings as unnecessary.  (Still in core, at least for now.)
3. Eliminates the StructDefinitions() method in favor of direct internal access to the map m_StructDefinitions().
What is _not_ done here is to change anything other than the C++ bindings.  When the Struct bindings are finalized in C++, C bindings at least should follow.  We also need to see if we can support Fortran derived types and numpy structured arrays.
Having DefineStruct in the ADIOS was likely motivated by the idea that a struct definition is …
=> Adjust DefineStruct bindings

source/adios2/core/Variable.cpp, source/adios2/core/Variable.h, source/adios2/core/VariableBase.cpp, source/adios2/core/VariableBase.h, source/adios2/core/VariableStruct.h, source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/helper/adiosCUDA.cu, source/adios2/helper/adiosCUDA.h, source/adios2/helper/adiosMemory.cpp, source/adios2/helper/adiosMemory.h, source/adios2/helper/adiosMemory.inl, source/adios2/toolkit/format/bp/BPSerializer.tcc, source/adios2/toolkit/format/bp/bp4/BP4Deserializer.tcc, source/adios2/toolkit/format/bp/bp4/BP4Serializer.tcc, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, source/adios2/toolkit/format/buffer/chunk/ChunkV.cpp
Currently the `isGPU` member is true if the CUDA backend is enabled. When multiple backends will exist, the flag will be confusing. The PR prepares the code for adding Kokkos as an option for memory management:
1. Codes for each backend will have a separate helper file. I moved all the CUDA function to the `helper::adiosCUDA` files. 
2. All backends will share the same logic and will only diverge when the copy needs to take place (or the minmax computation)
=> Clean the GPU code to allow multiple backends

cmake/DetectOptions.cmake, source/adios2/toolkit/sst/CMakeLists.txt
This will disable the SST MPI if the MPI_Port_open function is not working or if MPICH is not defined.
Related #3377
=> CMAKE: Check usability of MPI_Port_open

source/adios2/helper/adiosCUDA.h, testing/adios2/engine/bp/TestBPWriteReadCuda.cpp
Testing functions for the GPU backend (for now hardcoded for CUDA but it will extended when we include other backends).
The test that was here before was checking that ADIOS2 will produce correct results when setting the correct memory space (CUDA or Host). This PR adds two more functions to the testing:
1. When `MemorySpace::Detect` is used ADIOS2 should always be correct, this is checked by the new function `CUDADetectMemSpace`. 
2. When the memory space is not set correctly, ADIOS2 throws an error.
This PR requires a discussion about what should happen when the memory space is set incorrectly. Currently, on the Put side (for a 1D contiguous allocated array):
```c++
var.SetMemorySpace(adios2::MemorySpace::Host);
bpWriter.Put(var, gpuData)
// Segfaults …
```
=> Testing for GPU backend for correct/incorrect memory spaces

CMakeLists.txt, bindings/CXX11/adios2/cxx11/Engine.cpp, bindings/CXX11/adios2/cxx11/Engine.h, bindings/CXX11/adios2/cxx11/KokkosView.h, bindings/CXX11/adios2/cxx11/Variable.cpp, bindings/CXX11/adios2/cxx11/Variable.h, cmake/DetectOptions.cmake, examples/kokkos/kokkosWriteRead.cpp, source/adios2/common/ADIOSTypes.h, source/adios2/core/Variable.cpp, source/adios2/core/VariableBase.cpp, source/adios2/core/VariableBase.h, source/adios2/engine/bp5/BP5Writer.cpp
This PR attempts to give compile time errors if a GPU application is trying to use ADIOS2 without any GPU support (I added the `ADIOS2_HAVE_GPU_SUPPORT` macro set to TRUE if there is any GPU backend: CUDA, Kokkos, HIP, etc.) 
Before this PR if an application mistakingly set the ADIOS2 memory space to CUDA or Detect when ADIOS2 was not build with CUDA enabled it would get a segmentation fault. After this PR a code like this:
```c++
data.SetMemorySpace(adios2::MemorySpace::CUDA);
bpReader.Get(data, gpuSimData);
```
is now giving
```
example.cpp: In function 'int BPWrite(std::string, size_t, int)':
/gpfs/alpine/csc143/proj-shared/againaru/adios/code_example_cuda/cudaADIOS2example.cpp:63:45: error: 'CUDA' is not a member of 'adios2::MemorySpace'
63 | …
```
=> Allowing the option of CUDA memory space only if CUDA is enabled

CMakeLists.txt, cmake/DetectOptions.cmake, cmake/FindUCX.cmake, cmake/adios2-config-common.cmake.in, docs/user_guide/source/engines/sst.rst, docs/user_guide/source/setting_up/source/cmake.rst, source/adios2/toolkit/sst/CMakeLists.txt, source/adios2/toolkit/sst/cp/cp_common.c, source/adios2/toolkit/sst/dp/dp.c, source/adios2/toolkit/sst/dp/ucx_dp.c
SST: Add UCX SST Dataplane
This commit implements a UCX SST dataplane.
The UCX dataplane was added without support for PRELOAD functionality as discussed previously.
Currently this commit disables PRELOAD functionality by commenting out the portion of the code. We need to decide how we want to ensure that PRELOAD
is disabled when using the UCX dataplane.
Another open topic is the priority of the UCX dataplane (compared to other DPs), if others are available. Currently we are hardcoding the priority to a value of 10.
The dataplane was tested with UCX v1.11 and openmpi v4.1.4 (compiled with UCX support) with the following cases:
1. SST ctests.
99% tests passed, 1 tests failed out of 168
The following tests FAILED:
1056 - Engine.Staging.TestOnDemandMPI.ADIOS2OnDemandMPI.Sst.MPI (Timeout)
2. …
=>     SST: Add UCX SST Dataplane

CMakeLists.txt, cmake/DetectOptions.cmake, cmake/adios2-config-common.cmake.in, source/adios2/CMakeLists.txt, source/adios2/core/ADIOS.cpp, source/adios2/core/ADIOS.h, source/adios2/core/IO.cpp, source/adios2/engine/bp3/BP3Reader.cpp, source/adios2/engine/bp3/BP3Writer.cpp, source/adios2/engine/bp4/BP4Reader.cpp, source/adios2/engine/bp4/BP4Reader.tcc, source/adios2/engine/bp4/BP4Writer.cpp, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Reader.h, source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/hdf5/HDF5ReaderP.cpp, source/adios2/helper/adiosSystem.cpp, source/adios2/helper/adiosSystem.h, source/adios2/toolkit/transport/file/FileAWSSDK.cpp, source/adios2/toolkit/transport/file/FileAWSSDK.h, source/adios2/toolkit/transportman/TransportMan.cpp, source/adios2/toolkit/transportman/TransportMan.h
New transport "awssdk" and transport parameters "endpoint=<url>" and "cache=<path>"
Cache metadata files with AWSSDK transport.  
e.g. time ./bin/bpls -la  adios-test-data/gs.bp  -T "Library=awssdk,endpoint=https://projects.pawsey.org.au,cache=/tmp/cache"
Other changes:
Added ADIOS::GlobalServices to initialize and shutdown AWS once across simulatneous ADIOS objects.
BP5Reader: Create n-1 extra file managers for n threads in BP5 in Open, and reuse them during stepping through all the steps instead of creating new file managers in each PerformGets().
Dependecy: AWS SDK, namely the "s3;iam;sts" modules from the SDK.
=> Added the AWSSDK transport using the AWS SDK S3 API. 

source/adios2/toolkit/sst/dp/ucx_dp.c
Mostly remove unused variables.  Fix one arithmetic on void pointer.
=> Kill warnings in UCX dataplane

source/adios2/toolkit/transport/file/FileIME.cpp
This bug was introduced in PR #3388 
here:
[https://github.com/ornladios/ADIOS2/commit/f31d2cb05ff4dd375d431d8043d2e16aee798b64](https://github.com/ornladios/ADIOS2/commit/f31d2cb05ff4dd375d431d8043d2e16aee798b64#diff-4cb33e244ce899f10daacb5669a29eed59c1227475c9825e81ae68990a8de984)
I do not understand how the CI did not catch this nor did any of my previous runs. 
@pnorbert please make sure my fix is correct. Should we include checking this in the CI?
=> Fig bug in the IME file transport

bindings/CXX11/adios2/cxx11/IO.cpp, bindings/CXX11/adios2/cxx11/VariableNT.cpp, bindings/CXX11/adios2/cxx11/VariableNT.h, source/adios2/core/ADIOS.h, source/adios2/core/IO.cpp, source/adios2/core/VariableStruct.cpp, source/adios2/core/VariableStruct.h, source/adios2/engine/ssc/SscHelper.cpp, source/adios2/engine/ssc/SscHelper.h, source/adios2/engine/ssc/SscWriterGeneric.cpp, source/adios2/engine/ssc/SscWriterNaive.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.h, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, testing/adios2/engine/staging-common/TestStructRead.cpp
Proposed API changes to the reader side for struct variables.
The idea is this:  Rather than the prior API where you had to do this:
`                auto varStruct = io.InquireStructVariable("particles", particleDef);`
(That is, you had to know the details of the structure definition _a priori_ in order to find the variable.)
We're going to do something like this:
```
auto varStruct = io.InquireStructVariable("particles");
if (varStruct && (varStruct.GetReadStructDef() == nullptr))
{
auto WriteStruct = varStruct.GetWriteStructDef();
(void)WriteStruct; // unused here, but available if needed
auto particleDef =
io.DefineStruct("particle1", sizeof(particle));
particleDef.AddField("a", offsetof(particle, a),
adios2::DataType::Int8);
particleDef.AddField("b", offsetof(particle, b), …
```
=> Reader-side struct API changes

examples/basics/joinedArray/joinedArray_write.cpp, source/adios2/core/VariableBase.h, source/adios2/toolkit/format/bp/BPBase.cpp, source/adios2/toolkit/format/bp/BPBase.h, source/adios2/toolkit/format/bp/BPBase.tcc, source/adios2/toolkit/format/bp/BPSerializer.cpp, source/adios2/toolkit/format/bp/bp3/BP3Deserializer.tcc, source/adios2/toolkit/format/bp/bp4/BP4Deserializer.tcc, source/adios2/toolkit/format/bp/bp4/BP4Serializer.cpp, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPJoinedArray.cpp
Declaration:          auto var = outIO.DefineVariable<double>(table", {adios2::JoinedDim, Ncols}, {}, {1, Ncols});
Setting block size:   var.SetSelection({{}, {Nrows[block], Ncols}});
=> Added support for Joined Arrays in the BP4 format and engine.

cmake/DetectOptions.cmake
Related to #3434 after cherry picking Jieyang's commits, we no longer need the FindMGARD file.
Making small changes so we don't have a warning related to this when MGARD is not used.
=> Warning fix when finding the MGARD library

source/adios2/toolkit/sst/dp/rdma_dp.c
=> Better error when libfabric defaults to or is specified a bad FABRIC_IFACE

docs/user_guide/source/engines/sst.rst
Fix a couple misplaced **bold**s in the sst.rst doc file
=> Fix misplaced *s in sst.rst

source/adios2/toolkit/format/bp/bp4/BP4Serializer.tcc, source/adios2/toolkit/format/bp5/BP5Serializer.cpp
Closes #3257
This will be overwritten by the new GPU backend logic introduced in v2.9.0
=> Fix build error on Summit for PGI with CUDA backend

scripts/ci/images-v2/Dockerfile.ci-spack-el8-base, scripts/ci/images-v2/Dockerfile.ci-spack-el8-cuda-base, scripts/ci/images-v2/Dockerfile.ci-spack-el8-leaf, scripts/ci/images-v2/build-base.sh, scripts/ci/images-v2/build-cuda.sh, scripts/ci/images-v2/build.sh
=> ci: migrate to almalinux, cuda base image

CMakeLists.txt, docs/user_guide/source/advanced/gpu_aware.rst
Followup #3446 
We missed this change, its to set the `CMAKE_CUDA_ARCHITECTURES` when using Kokkos_CUDA
=> ci,kokkos,cuda: remove warnings

CODEOWNERS, scripts/ci/images-v2/Dockerfile.ci-spack-el8-base, scripts/ci/images-v2/Dockerfile.ci-spack-el8-cuda-base, scripts/ci/images-v2/Dockerfile.ci-spack-el8-leaf, scripts/ci/images-v2/build-base.sh, scripts/ci/images-v2/build-cuda.sh, scripts/ci/images-v2/build.sh, scripts/ci/images-v2/specs.yaml.in, source/adios2/CMakeLists.txt
Fixes: #3205 
Ideally we want to have an install test that fails when it sees empty dirs in the installation tree.
=> cmake: do not install empty sst dirs

.github/workflows/everything.yml, testing/contract/lammps/config.sh
followup: #3494 
While the Lammps and Scorpio applications are being updated to drop the Adios2 deprecated functions, we need to make some changes to keep our CI green. This MR:
- Uses @pnorbert lammps branch which includes the changes to use ADIOS 2.9
- Temporary disable the Scorpio contract as it will keep failing until their team updates
their code to our current API.
=> Workaround for lammps and Scorpion to have a green CI

CMakeLists.txt
Using the newly introduced `Kokkos_CUDA_ARCHITECTURES` and `Kokkos_HIP_ARCHITECTURES`
If the user sets the `-D CMAKE_CUDA_ARCHITECTURES` to something else, the user defined variable will be used (the same for HIP) so we cover the case when the used intends to use a different architecture.
=> Set the CMAKE GPU architectures to what is used for Kokkos

source/adios2/core/Operator.cpp, source/adios2/core/Operator.h, source/adios2/helper/adiosMemory.cpp, source/adios2/helper/adiosMemory.h, source/adios2/helper/adiosMemory.inl, source/adios2/operator/OperatorFactory.cpp, source/adios2/operator/OperatorFactory.h, source/adios2/operator/compress/CompressBlosc.cpp, source/adios2/operator/compress/CompressBlosc.h, source/adios2/operator/compress/CompressMGARD.cpp, source/adios2/operator/compress/CompressMGARD.h, source/adios2/operator/compress/CompressMGARDPlus.cpp, source/adios2/operator/compress/CompressMGARDPlus.h, source/adios2/toolkit/format/bp/BPSerializer.tcc, source/adios2/toolkit/format/bp/bp3/BP3Deserializer.tcc, source/adios2/toolkit/format/bp/bp4/BP4Deserializer.tcc, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, source/adios2/toolkit/format/dataman/DataManSerializer.tcc, testing/adios2/engine/bp/operations/TestBPWriteReadMGARDCuda.cpp
If an operator (direct or inverse) is not applied (due to a threshold or some other reason) the `Operate` or `Decompress` functions are now returning 0 and are not responsible with copying the data to the ADIOS2 internal buffers.
This allows ADIOS2 to use the appropriate function for copying the data (taking into consideration the memory space).
Operators that use this: Blosc, MGARD, MGARDPlus
**Testing** Adding test for MGARD with small GPU buffers. 
*Note:* the original code inside operators was using `memcpy` so I am simply moving the logic outside (I am not checking for reverse endian)
Adding to #3465 to skip copy for blocks with 0 elements
=> Move the buffer copy logic outside operators

bindings/Fortran/modules/adios2_parameters_mod.f90
Resubmitting to the release branch.   Note that there is fragility here because the numerical values in the fortran bindings must match the numerical values in the C bindings and we have nothing that guarantees that.  Also, there are modes for different things mixed in the different lists.  Sigh.
=> Add adios2_mode_readRandomAccess to fortran bindings

docs/user_guide/source/advanced/plugins.rst, examples/plugins/engine/CMakeLists.txt, examples/plugins/engine/ExampleReadPlugin.h, examples/plugins/engine/ExampleWritePlugin.h, examples/plugins/engine/examplePluginEngine_read.cpp, examples/plugins/engine/examplePluginEngine_write.cpp, examples/plugins/operator/examplePluginOperator_read.cpp, examples/plugins/operator/examplePluginOperator_write.cpp, source/adios2/engine/plugin/PluginEngine.cpp, source/adios2/helper/adiosPluginManager.cpp, source/adios2/operator/plugin/PluginOperator.cpp, testing/install/EnginePlugin/CMakeLists.txt
Fixes #3492. For some reason a `PerformPuts()` was removed that causes the example to break. The example is used in one of the install tests, but it wasn't returning failure states when it happens so that's why we missed in CI. That's been fixed as well. It also turns out that that has been failing for awhile due to not being able to find the plugin libs, so that should be fixed now too.
=> Fix plugin engine example

source/adios2/engine/bp5/BP5Writer.cpp, testing/adios2/engine/bp/TestBPWriteReadCuda.cpp
There was one place where we did not propagate the memory space and `Host` was used by default. This resulted in seg faults when using `SetMemorySelection` on a GPU buffer with BP5. Fixed in the first commit + adding a testing for memory selection with CUDA (for both BP4 and BP5)
This will close issue #3478
=> Bug fix in BP5 when memory selection is used with GPU buffers

source/adios2/toolkit/format/bp/bp4/BP4Serializer.tcc
This solves a fix for WarpX where processes write different number of blocks.
Related to PR #3465 and issue #3460
*Note:* This only affects BP4
=> Fix bug when writing null blocks 

bindings/Python/py11Engine.cpp, testing/adios2/bindings/python/CMakeLists.txt, testing/adios2/bindings/python/TestGetException_nompi.py
=> Throw an exception in Python bindings on Get() buffer type mismatch

docs/user_guide/source/ecosystem/h5vol/vol.rst, docs/user_guide/source/engines/hdf5.rst, examples/CMakeLists.txt, examples/h5subfile/CMakeLists.txt, examples/h5subfile/h5_subfile.cpp, source/CMakeLists.txt, source/adios2/toolkit/interop/hdf5/HDF5Common.cpp, source/h5vol/H5Vol_dataset.c, source/h5vol/H5Vol_def.h
If H5 has subfile support, it will be the default to write H5 files. 
Use envs to control subfile parameters through the underlying  HDF5 library: 
(# of subfiles per node) H5FD_SUBFILING_IOC_PER_NODE  
H5FD_SUBFILING_STRIPE_SIZE
etc.
=> H5 subfile support

source/adios2/operator/compress/CompressZFP.cpp
The ZFP compressor supports only the `rate` parameter when the GPU backend is used (even if the arrays are CPUs if ZFP is linked to CUDA, the `accuracy` and `precision` parameters will result in errors). This PR makes the errors easier to understand.
ZFP supported parameters:
This is something that might change soon so it will be updated (the main reason why I am not adding this in testing).
=> Throw an error when unsupported parameters are used with the ZFP CUDA backend

bindings/CXX11/adios2/cxx11/KokkosView.h
This is not a bug, more of an oversight (we don't need this in the current release). 
I tested the Kokkos backend in ADIOS2 with HIP on Crusher and it works fine as long as we pass the pointer (i.e. `view.data()`). I forgot to add the HIP memory space in the part of ADIOS2 that allows submitting directly the `Kokkos::View`. This PR fixes that.
Tested on Crusher BP4/BP5.
=> Allowing Put/Get to receive Kokkos Views with HIP backend

scripts/build_scripts/build-adios2-cuda-perlmutter.sh, scripts/build_scripts/build-adios2-cuda-summit.sh, scripts/build_scripts/build-adios2-kokkos-crusher.sh, scripts/build_scripts/build-adios2-kokkos-perlmutter.sh, scripts/build_scripts/build-adios2-kokkos-summit.sh
For Summit, Perlmutter and Crusher
=> Build scripts for ADIOS2 with CUDA and Kokkos backend

CTestCustom.cmake.in
These tests are only enabled in master and were not tested when we brought this new build. Disabling this since they might just be impossible or very hard to fix them
=> Disable emu tests

bindings/C/CMakeLists.txt, bindings/CXX11/CMakeLists.txt, bindings/Fortran/CMakeLists.txt, cmake/ADIOSFunctions.cmake, source/adios2/CMakeLists.txt, source/adios2/toolkit/sst/CMakeLists.txt, thirdparty/EVPath/CMakeLists.txt, thirdparty/atl/CMakeLists.txt, thirdparty/dill/CMakeLists.txt, thirdparty/enet/CMakeLists.txt, thirdparty/ffs/CMakeLists.txt, thirdparty/perfstubs/perfstubs/CMakeLists.txt
In the installation tree, we need to set the soname/version of our third library same as our ADIOS soname/soversion. This is needed for package manager to deal with multiple versions of ADIOS installed in their system.
=> cmake: set correct soname

source/adios2/helper/adiosType.h, source/adios2/toolkit/format/bp/bp4/BP4Deserializer.tcc, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, testing/adios2/interface/CMakeLists.txt, testing/adios2/interface/TestADIOSSelection.cpp
Despite this having changes in testing/adios/interface, it actually doesn't involve any changes in the API or ABI. The story is this: There is a call, SetMemorySelection(), that affects how ADIOS accesses memory on both the writer and reader side. While there are tests for SetMemorySelection() on the writer side in testing/adios/bp, the only place where reader-side SetMemorySelection was tested was in testing/adios/interface, and oddly those tests were hard-coded to only use the BP3 engine (which hasn't been the default forever). Turns out that the reason that it was hard-coded is that that reader-side functionality was missing from BP4 and BP5. This PR implements that missing functionality in those engines and tweaks the testing so that the engine is no longer hard-coded as BP3 in the …
=> Implement BP5 (and BP4) reader-side memory selection, do testing

examples/heatTransfer/write/HeatTransfer.cpp
Replace the `MPI_REAL8` datatype, which is _optional_ in the MPI standard and not always available, with `MPI_DOUBLE`. The latter is always available and corresponds to the data sent around.
First seen as an OpenMPI compile error on a user's machine:
https://github.com/openPMD/openPMD-api/issues/1424#issuecomment-1516916044
I found no further examples that use the same MPI type and would need an update.
=> Heat Transfer Example: MPI Datatype

examples/heatTransfer/write/HeatTransfer.cpp
Heat Transfer Example: MPI Datatype
(cherry picked from commit 50aa9a3ce90a09222fb81b3dc5c3d0197433e5dc)
#3593
=> Backport:  Heat Transfer Example: MPI Datatype #3593 

scripts/ci/gh-actions/windows-setup.ps1
It attempts to solve windows setup errors in CI such as:
```
Downloading Microsoft MPI Runtime 10.1.1
Invoke-WebRequest: D:\a\ADIOS2\ADIOS2\gha\scripts\ci\gh-actions\windows-setup.ps1:29
Line |
29 |      Invoke-WebRequest "$baseurl/msmpisetup.exe" -OutFile $msmpisetup
|      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Authentication failed, see inner exception.
Error: Process completed with exit code 1.
```
As seen here: https://github.com/ornladios/ADIOS2/pull/3619
=> Fix flaky MSMPI installation in windows builds

source/h5vol/H5VolUtil.c, source/h5vol/H5VolUtil.h
as reported in: 
https://github.com/ornladios/ADIOS2/issues/3638
=> replaced uint with size_t 

source/h5vol/CMakeLists.txt, source/h5vol/H5VolReadWrite.c
to fix the issue reported here:  
https://github.com/ornladios/ADIOS2/issues/3649#issuecomment-1572840107
=> work around  with include <unistd.h> on  windows

bindings/CXX11/adios2/cxx11/KokkosView.h
Found by Norbert today when trying to compile the Kokkos example from the `ADIOS2-Examples` repo. This happens only when using Kokkos without any GPU backend.
=> Bug fix for Kokkos applications without GPU backend

source/adios2/operator/compress/CompressBlosc.cpp, source/adios2/toolkit/format/bp/bpBackCompatOperation/compress/BPBackCompatBlosc.cpp
Explictly specialize to avoid macro resolution when windows.h is included. What a world to live in.
X-ref: https://github.com/ornladios/ADIOS2/issues/3680#issuecomment-1615308336
@vicentebolea did I do this right? This PR should go in `master` and `release_29` alike.
=> Fix: std::min w/ windows.h in C-Blosc2

testing/adios2/engine/dataman/TestDataMan1D.py
It looks like the default for macos and python 3.8+ "spawn" method does not work on macos, swith to "fork" for all situations. https://bugs.python.org/issue33725. Rebased on the current master.
=> Fix for the issue #3646. 

.github/workflows/everything.yml
Hopefully this fixes the issue with saving cache on workflows run on the `master` branch.  I described the situation with a few more details [here](https://github.com/ornladios/ADIOS2/pull/3705#issuecomment-1660835138).
=> ci: Fix conditional expression syntax to fix cache save

.github/workflows/everything.yml
This PR hopefully *really* fixes the failures to save cache on `master` branch workflows.
I re-ran a `master` workflow with extra logging (which is handy), so [here](https://github.com/ornladios/ADIOS2/actions/runs/5731669038/job/15534531545) I could see why the cache was not getting saved: Instead of the restore action `cache-hit`output containing `false` or `true` as [documented](https://github.com/actions/cache/tree/main/restore#outputs), when no cache could be restored, it was set to `null`.
There was a [bug](https://github.com/actions/cache/issues/533) filed for this issue, but it was ignored and eventually closed automatically.
=> ci: work around bug in actions/cache

source/adios2/CMakeLists.txt, source/adios2/engine/bp5/BP5Engine.h, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Reader.h, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.h, source/adios2/toolkit/remote/CMakeLists.txt, source/adios2/toolkit/remote/Remote.cpp, source/adios2/toolkit/remote/Remote.h, source/adios2/toolkit/remote/remote_common.cpp, source/adios2/toolkit/remote/remote_common.h, source/adios2/toolkit/remote/remote_server.cpp, source/adios2/toolkit/transport/file/FileRemote.cpp, source/adios2/toolkit/transport/file/FileRemote.h, source/adios2/toolkit/transportman/TransportMan.cpp
This is a replacement for the prior WIP Remote PR (which I will delete when this is merged).  This has been reformatted with the new clang-format parameters and contains a tiny bit of Norbert's campaign tweaks (the RemoteDataPath parameter).  However, it can still be activated with the `DoRemote` environment variable (activates Get()-level remote data access) and the `DoFileRemote` environment variable (activates transport-level remote data access).  If only DoRemote is activated, the metadata is read locally and Get() operations sent to the remote server.  If only DoFileRemote is activated, _**all**_ file access is sent to the remote server, including metadata reads.  (This is a temporary measure to test the mechanism, not a final solution.). If both are activated, metadata access …
=> Remote Data access via Get() or Transport

CMakeLists.txt, cmake/DetectOptions.cmake, scripts/ci/images/Dockerfile.ci-spack-ubuntu20.04-base, scripts/ci/images/Dockerfile.ci-spack-ubuntu20.04-clang, scripts/ci/images/Dockerfile.ci-spack-ubuntu20.04-gcc, scripts/ci/images/Dockerfile.ci-spack-ubuntu20.04-intel, scripts/ci/images/build-ubuntu.sh, source/adios2/CMakeLists.txt
This uses the new C-Blosc2 `Blosc2Config.cmake` packages, so we can do purely static builds.
Close #3714
=> Fix: Static Builds Against C-Blosc2

docs/user_guide/source/setting_up/source/cmake.rst
Not an exhaustive guide although using `-DPython_FIND_STRATEGY=LOCATION` will probably work for most of the people and otherwise it can hint to research what it does so the user can find out how to find the desired python.
=> cmake,readthedocs: update python enable instructions

source/adios2/CMakeLists.txt
=> cmake: correct info.h installation path

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.h
I have found that we broke ABI compatibiltiy with the bugfix for BP5Deserializer, my bad. Now I am armed with a abi compatibility tool and I can see what went wrong :) 
It appears that 2.9.1 is not fully ABI compatibly, that is something that we cannot change, the good this is that BP5Deserializer is an "internal" sort of type, thus is unlikely the user to hit a dynlink error. In order to make the future 2.9.2 as ABI compatible and to set a precedent I rework here the bugfix in order to revert to 2.9.0 ABI.
Here are the ABI compatibility report of 2.9.1 against 2.9.0:
Here are the ABI compatibility report of this MR against 2.9.0:
=> BP5Deserialize: modify changes to keep abi compt

docs/environment.yml, readthedocs.yml
Readthedocs is deprecating features that we still use in the release branch.
@eisenhauer 
X-ref: #3782
=> Backport readthedocs fixes

source/h5vol/H5VolReadWrite.h, source/h5vol/H5Vol_def.h
This PR updates the ADIOS2 HDF5 VOL connector to return a basic set of capability flags so that it can be tested with the [HDF5 VOL tests repository](https://github.com/HDFGroup/vol-tests/). Otherwise, the tests would fail when trying to call the H5Pget_vol_cap_flags API routine to retrieve the connector's capability flags.
Defining the new H5VL_adios2_introspect_get_cap_flags callback function allows HDF5 to properly resolve situations where the connector may have other connectors stacked on top of it that pass operations down and need to check if the connectors below it support certain functionality.
=> Update ADIOS2 HDF5 VOL with basic set of capability flags

.github/workflows/everything.yml
checkout@v3 is very flaky at this moment. Updating to v4.
https://github.com/actions/checkout/issues/1450
=> gha,ci: update checkout to v4

source/adios2/common/ADIOSTypes.cpp, source/adios2/common/ADIOSTypes.h, source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/bp5/BP5Writer.h, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.h, source/adios2/toolkit/format/buffer/BufferV.h, source/adios2/toolkit/format/buffer/chunk/ChunkV.cpp, source/adios2/toolkit/format/buffer/chunk/ChunkV.h, source/adios2/toolkit/format/buffer/malloc/MallocV.cpp, source/adios2/toolkit/format/buffer/malloc/MallocV.h
This PR is in support of the Derived Variables work and includes example usage in an inactive #ifdef in the BP5 writer engine.  While it seems to be functional, the functions here won't be used until derived variable implementation is complete (or we introduce unit testing of some kind for this).
=> Add MinBlocksInfo to BP5 writer engine

thirdparty/CMakeLists.txt
fixes: #3762
In this PR we add support to the new YAML-cpp version 0.8.0. We currently ship and support YAML-cpp 0.7.X. Before the 0.7, YAML-cpp was not a cmake project thus our minimum supported versions  0.7.X.
Some context: 
- I have tried building adios2 with 0.5.X(fail) 0.6.X(Fail) 0.7.X 0.8.X(Works with this change).
=> yaml-cpp: support 0.8.0 version

source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Reader.h, source/adios2/toolkit/profiling/iochrono/IOChrono.cpp, source/adios2/toolkit/profiling/iochrono/IOChrono.h
I'm considering this WIP because of things we likely want to discuss.  For example, it unconditionally drops profiling JSON in /tmp (with profiled reader file name and PID as part of the JSON filename).  Maybe it should do that only when explicitly enabled, maybe the drop location should be configurable, etc.  It's only profiling data, metadata and metametadata read times and byte counts.  We might add to that other items of interest on the read side.
=> WIP:  Reader-side Profiling

cmake/ADIOSFunctions.cmake, cmake/DetectOptions.cmake, examples/hello/README.md
Randomly found this bug when testing the query code.
=> Fix the `ADIOS_USE_{}` variable names to use ADIOS2

bindings/CXX11/adios2/cxx11/Query.cpp, bindings/CXX11/adios2/cxx11/Query.h, bindings/Python/py11Query.cpp, bindings/Python/py11Query.h, docs/user_guide/source/advanced/query.rst, examples/query/test.cpp, source/adios2/toolkit/query/BlockIndex.h, source/adios2/toolkit/query/Query.cpp, testing/adios2/bindings/python/CMakeLists.txt, testing/adios2/bindings/python/TestNullEngine.py, testing/adios2/bindings/python/TestQuery.py, testing/adios2/performance/query/TestBPQuery.cpp
added function to use MinBlocksInfo to browse bp5 statistics.
=> added support to query BP5 files

cmake/adios2-config-common.cmake.in
=> install: export adios2 device variables

cmake/DetectOptions.cmake
Fixes #3836 
This adds a c++ timer to the configure tests that determines whether the MPI DataPlane can be used.
@guj
=> MPI: add timeout for conf test for MPI DataPlane

source/adios2/toolkit/sst/dp/mpi_dp.c
X-ref: [#1443 ](https://github.com/ornladios/ADIOS2/issues/3829)
=> MPI DataPlane: do not call MPI_Init internally

cmake/DetectOptions.cmake
Avoid that for older C-Blosc2 releases, with `ADIOS2_USE_Blosc2=ON`, the search logic errors out after the config module was not found.
Regression introduced in #3715 (after rebase).
=> Blosc2 USE ON: Fix Module Fallback

source/adios2/toolkit/format/bp5/BP5Serializer.cpp
This fixes the bug brought up in #3856. 
I was going to add a test for it, but it's not working and I'm not sure why. I was planning to modify `testing/adios2/engine/bp/TestBPWriteReadLocalVariables.cpp` so that one of the variables created has a bzip operator added to it, but I get failures that I'm confused by. I get various failures depending on which variable I add the operator to. If I add it to the float variable I get the following in all cases (it's not just BP5, but 3 and 4 as well).
```
C++ exception with description "[Thu Oct 19 17:34:06 2023] [ADIOS2 EXCEPTION] <Operator> <CompressBZIP2> <CheckStatus> : BZ_OUTBUFF_FULL BZIP2 detected size of compressed data is larger than destination length in call to ADIOS2 BZIP2 Compress batch 0
```
If I switch to adding the operator on the …
=> BP5Serializer: handle local variables that use operators

ReadMe.md
We've had slack in Readme.md forever, but it was misspelled "spack" in the link and you've never been able to join the ADIOS slack without an invite.  Couple that with the fact that nobody is really on the ADIOS slack anymore and I recommend we just eliminate this as a contact mechanism in Readme.md.
=> Remove Slack as a contact mechanism

source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/toolkit/remote/Remote.h, source/adios2/toolkit/remote/remote_common.cpp, source/adios2/toolkit/remote/remote_common.h, source/adios2/toolkit/remote/remote_server.cpp, source/adios2/toolkit/transport/file/FileRemote.cpp
- Add idle timeout to server.  Unless the -no_timeout flag is specified, the server will exit after 10 minutes of idle time
- Specify the server port with a single constant in remote_common.h, rather than several explicit constants.
=> Remote Server Improvements

thirdparty/ffs/ffs/fm/fm_formats.c
Turns out that master already has this fix because it migrated into FFS master in July.  However, we haven't pulled in fresh FFS to release because there were significant API changes and we didn't want those in a patch release.  So this is a one-line change that fixes our hash issues (which were not really hash issues, but instead "calculating the length over which to do a hash" issues).
=> Fix data length calculation for hash

source/adios2/toolkit/format/bp5/BP5Serializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.h
Backport of #3877 
> …map. For 250k variables, time goes from 21sec to ~1sec in WSL. The order of entries in RecList was not necessary for the serializer to work correctly.
(cherry picked from commit 2e8bcaf558c1d96cd1bd88a612f1cbc119aee495)
=> Backport 3877 to master

source/adios2/toolkit/format/bp5/BP5Serializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.h
=> bp5: make RecMap an static anon namespaced var

source/adios2/toolkit/sst/dp/mpi_dp.c
We have been observing scalability issues with the MPI DP. I have been able to narrow down to potential root causes and I was able to propose possible solutions to it in this PR.
- Task id collision between different ranks at scale. This was expected to happens since we used the process id (PID) as the rank id (not a good idea). This has been replaced by an aggregate ID of the process PID and the machine hostid.
- Currently in the event of a reader rank failure the MPI Dataplane write simply frees and disconnect to every resource pertaining to its cohort.  Since at large scale the failure of readers nodes (or timeout event) are not that rare, in this PR I make the Write to skip releasing resources pertaining to the reader unless all the peers of the cohorts have exited. To make happy MPI, …
=> Fix MPI Data plane cohort handling

cmake/DetectOptions.cmake
This is needed since some builds fails (oneapi in Spack) since the Threads::Threads targets is used before find_package(Threads) is called.
=> cmake: find threads package first

.gitlab/config/generate_pipelines.py
This is needed for the generate_pipelines.py to support processing more than 100 branches in the Gitlab CI (The max per_page items that Gitlab CI allow).
I have also change the functional programming style form map/filter to comprehensions list to make the code more pythonic.
=> ci,crusher: increase supported num branches

scripts/ci/cmake/ci-el8-icc-ompi.cmake, scripts/ci/cmake/ci-el8-oneapi-ompi.cmake, scripts/ci/cmake/ci-ubuntu20.04-clang10-ompi.cmake, scripts/ci/cmake/ci-ubuntu20.04-clang6-ompi.cmake, scripts/ci/cmake/ci-ubuntu20.04-clang6-static-ompi.cmake, scripts/ci/cmake/ci-ubuntu20.04-gcc10-ompi.cmake, scripts/ci/cmake/ci-ubuntu20.04-gcc11-ompi.cmake, scripts/ci/cmake/ci-ubuntu20.04-gcc8-ompi.cmake, scripts/ci/cmake/ci-ubuntu20.04-gcc8-static-ompi.cmake, scripts/ci/cmake/ci-ubuntu20.04-gcc9-ompi.cmake, scripts/ci/gh-actions/run.sh
=> ci: Set openmpi and openmp parameters to make an efficient use of the CI

.github/workflows/everything.yml, testing/contract/examples/build.sh, testing/contract/examples/config.sh, testing/contract/examples/depends.sh, testing/contract/examples/install.sh, testing/contract/examples/setup.sh, testing/contract/examples/test.sh
CI Contract: Build examples with external ADIOS
Fixes https://github.com/ornladios/ADIOS2/issues/3795.
Fixes: #3811
=> CI Contract Build examples with external ADIOS

examples/hello/datamanKokkos/CMakeLists.txt
Set it to what is used to build Kokkos.
For some reason I was able to compile this code without the fix on Summit, but it was falling on Frontier.
=> Set the compiler for the Kokkos DataMan example

bindings/C/adios2/c/adios2_c_adios.h, bindings/Matlab/Makefile, bindings/Matlab/adiosopenc.c
Updated bindings/Matlab/Makefile to include a working MacOS (Sonoma) example, added preprocessor macro to check MPI usage and call the correct version of adios2_init() accordingly in bindings/Matlab/adiosopenc.c, fixed spelling error in bindings/C/adios2/c/adios2_c_adios.h
Related to issue: https://github.com/ornladios/ADIOS2/issues/3947
=> Fix MATLAB bindings for MacOS

bindings/C/adios2/c/adios2_c_adios.h, bindings/Matlab/Makefile, bindings/Matlab/adiosopenc.c
* Fix MATLAB bindings for MacOS - updated bindings/Matlab/Makefile, added preprocessor macro to check MPI usage and call the correct version of adios2_init() accordingly, fixed spelling error in bindings/C/adios2/c/adios2_c_adios.h
* Update adiosopenc.c to use adios2_init_serial regardless of MPI use.
=> Fix MATLAB bindings for MacOS, backported from master

.shellcheck_exclude_paths, scripts/ci/circle/postCDashStatus.sh, scripts/ci/circle/run.sh, scripts/ci/gh-actions/check-branch-name.sh, scripts/ci/gh-actions/get-changed-files.sh, scripts/ci/gh-actions/macos-setup.sh, scripts/ci/gh-actions/run.sh, testing/contract/lammps/build.sh, testing/contract/lammps/config.sh, testing/contract/lammps/install.sh, testing/contract/lammps/setup.sh, testing/contract/lammps/test.sh, testing/contract/scorpio/build.sh, testing/contract/scorpio/config.sh, testing/contract/scorpio/install.sh, testing/contract/scorpio/setup.sh, testing/contract/scorpio/test.sh, testing/contract/tau/build.sh, testing/contract/tau/config.sh, testing/contract/tau/install.sh, testing/contract/tau/setup.sh, testing/contract/tau/test.sh
Enable shell check scripts for existing scripts
=> Enable shell check scripts for existing scripts

bindings/Matlab/adiosopenc.c
Matlab was still using `adios2_mode_read` that only works for BP4 file.
=> Use adios2_mode_readRandomAccess in matlab open to make it work for BP5

cmake/DetectOptions.cmake, cmake/check_libfabric_cxi.c, source/adios2/toolkit/sst/CMakeLists.txt, source/adios2/toolkit/sst/dp/rdma_dp.c
This PR is a first step towards trying to make use of libfabric+CXI on Frontier for SST streaming.
It successfully connects to the provider in `init_fabric()` in my tests, and the hello_sst examples finishes without error – but for some reason without loading any data. I will provide a detailed run log later (I lost my earlier logs somehow and a new job is currently enqueued), but essentially `fi_cq_sread` returns one finished task from the queue that reports a successful remote read of zero bytes.
When changing the data size in the helloSst examples, different errors occur (permission violations or (if I remember correctly) error code 90 - message too long) depending on the chosen data size.
As you can see in the diff, the configuration of libfabric is somewhat different from the one …
=> Adapt libfabric dataplane of SST to Cray CXI provider

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.h
This is a quick fix to free a `vector<...>*` pointer in the destructor. However, this may be revised to use a vector instead of a pointer at all.
=> fix for ASAN issue related to JoinedDimArray handling in BP5 deserializer

source/adios2/toolkit/interop/hdf5/HDF5Common.cpp, source/adios2/toolkit/interop/hdf5/HDF5Common.h, source/adios2/toolkit/interop/hdf5/HDF5Common.tcc
Discussion in #3942 suggests that support for operators in "secondary" (for want of a better term) engines is not planned. My suggestion that ADIOS should let the user know this won't happen is added in this PR.
=> Have HDF5 write raise error if operator(s) requested

.github/workflows/pypackaging.yml
Currently when we run a manual workflow, the upload to pypi job is getting skipped due to insufficient conditions guarding that job.  This PR adds `workflow_dispatch` to the conditions under which it will be run.
=> pip: also run pypi upload job on workflow_dispatch

Copyright.txt
Here we include recent Kitware authors to the copyright.txt. We are basing this file for other features such as the newly pip package.
X-Ref: #3960
=> update copyright.txt to include recent kitware authors

CTestConfig.cmake, source/adios2/engine/sst/SstWriter.cpp
This deletes BP5 marshalling buffers for SST after use to fix a memory leak.  We may want to look into reusing those buffers, particularly for SST where we use the MallocV buffer subclass that grows with realloc() to keep things contiguous.  Reuse would potentially avoid the large-copy-on-realloc problem that happens apps that generate a lot of data.
=> SST ASAN buffer fix

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
Hopefully this addresses Issue #3987
=> Fix read request length on BP5 Local arrays with operators

source/adios2/engine/campaign/CampaignData.cpp
Uncompressed from the campaign archive  md.0 file has different size with the original file. The pointer to a chunk  was not updated during chunk inflation in a loop.
=> Campaign fix

source/adios2/engine/campaign/CampaignManager.cpp
Update  sqlite database if a table with bp files exists. Before there was an error.
=> campaign management: update sqlite database after another run

CMakeLists.txt, cmake/DetectOptions.cmake, cmake/adios2-config-common.cmake.in, cmake/install/pre/CMakeLists.txt, source/adios2/CMakeLists.txt
Blosc2 is a private dependency thus we do not have to export its targets.
=> blosc2: do not export blosc2 lib

plugins/operators/EncryptionOperator.cpp, plugins/operators/EncryptionOperator.h, source/adios2/operator/plugin/PluginOperator.cpp, source/adios2/operator/plugin/PluginOperator.h
Hi Team ADIOS!
I greatly appreciate the new `GetEstimatedSize` API for operators - thanks @pnorbert (as I see you committed that in 931941e).
I would like this to work for plugin operators also, so please consider these changes which implement this :) 
I am of course happy to accept revisions.
=> Allow plugin operators to take advantage of the estimated size API

source/adios2/toolkit/interop/hdf5/HDF5Common.cpp
it turns out strings written out through h5py are all variable strings
=> added support to read back from H5T_STRING VARIABLES

source/adios2/toolkit/remote/remote_server.cpp
Even the youngest padawan knows that read() sometimes returns partial results, how did this live so long?   Maybe because we're not really handling errors in the remote protocol so far...
=> Actually look at return value for read in remote_server

docs/user_guide/source/advanced/gpu_aware.rst
- Updated the paths to the example codes
- Updated the default behavior when building ADIOS2 with Kokkos/CUDA available
- Added info about the new Shape function for the Read side 
This is my contribution to issue #4073
=> Update documentation for 2.10 changes to the GPU-backend

docs/user_guide/source/tutorials/overview.rst
To highlight the C/Fortran API and the changes to how layouts should be handled.
=> Fix typo in the links to external tutorials 

docs/user_guide/source/api_full/fortran.rst
Noticed a small type in Fortran API docs and fixed it. Haven't tested docs build but I presume such a small change should be fine.
=> Fix typo in Fortran API docs

CMakeLists.txt
When #4114 was merged, I forgot to turn OFF the derived variables. This PR fixes this.
=> Setting the derived variable support OFF by default

source/adios2/toolkit/remote/CMakeLists.txt
=> pugixml: correct target name

bindings/Python/py11glue.cpp, python/adios2/stream.py, source/adios2/common/ADIOSMacros.h, testing/adios2/engine/SmallTestData.h, testing/adios2/engine/bp/TestBPWriteReadADIOS2.cpp
- based on char signess in installed adios library, use numpy.int8 or numpy.uint8 to read char arrays from BP files
- move char as last type in adios type macros, so that unsigned char always becomes uint8_t and signed char becomes int8_t in output (char arrays still become  char in output)
- add C++ test to write and read char/signed char/unsigned char arrays
fixes #4140
=> Fix python char

source/adios2/core/Engine.h, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Reader.h, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.h, source/utils/bpls/bpls.cpp, testing/utils/cwriter/TestUtilsCWriter.bplsh.expected.txt
Added the option `--show-derived` in bpls to print the expression string for derived variables.
```
$ ./bin/bpls expAdd.bp --show-derived -l
float    derived/addU  2*{10, 3, 6} = 2.98842 / 28.085
Derived variable with expression: x =sim1/Ux  y =sim1/Uy  z =sim1/Uz  x+y+z
float    sim1/Ux       2*{10, 3, 6} = 0.000224775 / 9.94031
float    sim1/Uy       2*{10, 3, 6} = 0.0201616 / 9.83318
float    sim1/Uz       2*{10, 3, 6} = 0.0031 / 9.95085
```
=> Option in `bpls` to show the expression string for derived variables

source/adios2/toolkit/remote/CMakeLists.txt, source/utils/CMakeLists.txt
followup of https://github.com/ornladios/ADIOS2/pull/4135
=> pugixml,cmake: fix linkage when pugixml is external

examples/simulations/gray-scott/catalyst/gs-pipeline.py
This line was removed when bringing this script over from the ADIOS2-examples repo, but removing it changes the expected camera behavior, so it's being added back in.
=> add line back to gs-pipeline.py

cmake/adios2-config-install.cmake.in
`cmake_minimum_required` is intended for top-level projects and scripts to set. Instead, just use the policy version.
=> adios2-config: set the policy directly

source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/toolkit/derived/Function.cpp, source/adios2/toolkit/profiling/iochrono/IOChrono.cpp
In the profile.json file
```
[
{ "rank":0, "start":"Fri_May_10_17:06:59_2024","DeriveVars_mus": 193012033, "DeriveVars":{"mus":193012033, "nCalls":1},"ES_mus": 416417, "ES":{"mus":416417, "nCalls":1},"ES_meta1_mus": 26, "ES_meta1":{"mus":26, "nCalls":1},"ES_meta2_mus": 130, "ES_meta2":{"mus":130, "nCalls":1},"ES_close_mus": 2093, "ES_close":{"mus":2093, "nCalls":1},"ES_AWD_mus": 414157, "ES_AWD":{"mus":414157, "nCalls":1}, "databytes":0, "metadatabytes":0, "metametadatabytes":0, "transport_0":{"type":"File_POSIX", "wbytes":786432000, "close":{"mus":271, "nCalls":1}, "write":{"mus":406584, "nCalls":4}, "open":{"mus":20610, "nCalls":1}}, "transport_1":{"type":"File_POSIX", "wbytes":752, "close":{"mus":153, "nCalls":1}, "write":{"mus":19, "nCalls":4}, "open":{"mus":984, "nCalls":1}} }
]
``` …
=> Adding hooks to gather performance for derived variables

source/adios2/CMakeLists.txt, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Reader.h, source/adios2/toolkit/remote/EVPathRemote.cpp, source/adios2/toolkit/remote/EVPathRemote.h, source/adios2/toolkit/remote/Remote.cpp, source/adios2/toolkit/remote/Remote.h, source/adios2/toolkit/remote/remote_common.cpp, source/adios2/toolkit/remote/remote_common.h, source/adios2/toolkit/remote/remote_server.cpp, source/adios2/toolkit/transport/file/FileRemote.cpp, source/adios2/toolkit/transport/file/FileRemote.h
No functional changes here.  Just reshuffling the code so that we can subclass remote for various underlying protocols.  This doesn't change any interactions with the current EVPath based remote adios server, but it sets the stage to have an Xroot-based remote protocol implementation without overly disrupting the places these calls are made.
=> Reorg Remote as base class in preparation for more remote subclasses

docs/user_guide/source/setting_up/source/cmake.rst
It was pointed out to me that the build documentation in readthedocs does not work. One typo was:
```
cmake ../ADIOS2 -DADIOS2_BUILD_EXAMPLES=ON
```
and second, it wasn't clear that they need to provide an install path based on our instructions (so adios2 doesn't get installed in `\usr\local`.
=> Typo in documentation

examples/hello/hdf5SubFile/hdf5SubFile.cpp, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/toolkit/remote/EVPathRemote.cpp, source/adios2/toolkit/remote/EVPathRemote.h, source/adios2/toolkit/remote/Remote.cpp, source/adios2/toolkit/remote/Remote.h, source/adios2/toolkit/remote/XrootdRemote.cpp, source/adios2/toolkit/remote/XrootdRemote.h, source/utils/xrootd-plugin/XrdSsiSvService.cpp
Change all RemoteHandle types to void * and make them appear only in the base class, change Xroot request/response sync to use future/promises, fix server-side type handling to use the right size for the type.  These changes are sufficient to pass a the simple TestCommonRead test using Xrootd remote server.  (No actual testing in CI yet, so you'll have to take my word for it.)
=> Basic Xrootd remote fixes

source/adios2/core/Engine.h, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Reader.h, source/adios2/toolkit/derived/Expression.cpp, source/adios2/toolkit/derived/Expression.h, source/adios2/toolkit/derived/parser/lexer.l, source/adios2/toolkit/derived/parser/pregen-source/lexer.cpp, source/utils/bpls/bpls.cpp
Related to PR #4145
Create a function that returns a single line string representation of a derived expression. This is mainly for `bpls` since one line has a more user friendly format. 
ExpressionTree to String Expression:
`ADD({sim1/Ux},{sim1/Uy},{sim1/Uz})`
```
$ ./bin/bpls expAdd.bp --show-derived -l
float    derived/addU  2*{10, 3, 6} = 2.98842 / 28.085
Derived variable with expression: ADD({sim1/Ux},{sim1/Uy},{sim1/Uz})
float    sim1/Ux       2*{10, 3, 6} = 0.000224775 / 9.94031
float    sim1/Uy       2*{10, 3, 6} = 0.0201616 / 9.83318
float    sim1/Uz       2*{10, 3, 6} = 0.0031 / 9.95085
```
The current solution is not the best. We do not create derived variables on the read side so the BP5Reader provides an internal function to get the expression string from the deserializer, …
=> Compress the expression string into one line for `bpls`

bindings/CXX11/adios2/cxx11/Variable.h, source/adios2/core/VariableBase.cpp
I'm currently adding support for memory selections to the openPMD-api on https://github.com/openPMD/openPMD-api/pull/1620. 
While working on it, I noticed that the selection specified in `Variable<T>::SetMemorySelection(...)` sticks to **all** subsequent `Put()` calls, without a  way to remove the memory selection again.
Is it intended that the setting will stick to the Variable or is that a bug? If it is intended, this PR adds a way to remove the setting again. Otherwise, this PR should be discarded and instead, the memory selection should be removed automatically after calling `Put()`.
cc @pnorbert
=> Add API call to reset memory selection

source/adios2/toolkit/remote/EVPathRemote.cpp, source/adios2/toolkit/remote/remote_server.cpp
Also fix an oversight in EVPath remote
=> Close more FDs because XRootd plays games in library init

source/adios2/common/ADIOSConfig.h.in
For us, this concerns mostly BP5. 
In ADIOS2 v2.9, BP5 was an optional feature, so all our code targeting BP5 in openPMD is behind an `#ifdef ADIOS2_HAVE_BP5` check. 
With ADIOS2 v2.10, BP5 is available unconditionally, so it was removed from the feature list in `CMakeLists.txt`:
```cmake
set(ADIOS2_CONFIG_OPTS
DataMan DataSpaces HDF5 HDF5_VOL MHS SST Fortran MPI Python PIP Blosc2 BZip2
LIBPRESSIO MGARD MGARD_MDR PNG SZ ZFP DAOS IME O_DIRECT Sodium Catalyst SysVShMem UCX
ZeroMQ Profiling Endian_Reverse Derived_Variable AWSSDK XRootD GPU_Support CUDA Kokkos
Kokkos_CUDA Kokkos_HIP Kokkos_SYCL Campaign
)
```
This means that the `#define ADIOS2_HAVE_BP5` is no longer there in `ADIOSConfig.h`. In consequence, the current release of openPMD does not work very well together with BP5 in ADIOS2 …
=> Add macro defines for BP3, BP4 and BP5

examples/hello/bpWriter/bpWriter.cpp, source/adios2/common/ADIOSTypes.h, source/adios2/core/ADIOS.cpp, source/adios2/core/ADIOS.h, source/adios2/core/Engine.cpp, source/adios2/core/Engine.h, source/adios2/engine/campaign/CampaignReader.cpp, source/adios2/helper/adiosYAML.cpp, source/adios2/helper/adiosYAML.h, source/adios2/toolkit/transport/file/FileAWSSDK.cpp, source/adios2/toolkit/transport/file/FileAWSSDK.h, source/utils/adios_campaign_manager/adios2_campaign_manager.py
- Parse ~/.config/adios2/hosts.yaml and build HostOptions dictionary. S3 protocol well defined, SSH and XRootD needs testing and fixing
- Enable creating a remote campaign with S3 location in adios2_campaign_manager
- CampaignReader handles S3 hosts and launches BP5 with AWSSDK transport library
Usage:
adios2_campaign_manager -v create MAST/30466 -n STFC-S3 --s3_bucket mast/test/adios/mini --s3_datetime "2024-04-19 10:20:15 -0400" -f 30466.bp
=> Campaign with S3 support

CMakeLists.txt, bindings/Python/CMakeLists.txt, python/CMakeLists.txt, source/adios2/toolkit/remote/CMakeLists.txt, source/adios2/toolkit/sst/util/CMakeLists.txt, source/utils/CMakeLists.txt, source/utils/adios_campaign_manager/CMakeLists.txt, source/utils/adios_iotest/CMakeLists.txt, source/utils/bp4dbg/CMakeLists.txt, source/utils/bp5dbg/CMakeLists.txt
We need this for package managers where we first need to install c/c++ components for the first package (libadios2) and later for the adios python/adios binaries package we need to install the remaining components.
=> cmake: add ADIOS2_LIBADIOS_MODE flag

source/adios2/toolkit/remote/remote_server.cpp
This adds a -report_port_selection flag that when used with -background tells the spawned server to use a random port and to report which port it is listening on.  It also generates and reports a random cookie that can be used to make sure that only the requestor can use the server (but this restriction is not yet implemented).
eisen@Endor build % bin/adios2_remote_server -background -report_port_selection
Listening on Port 63728
port:63728;msg:no_error;cookie:0xc86b1d78e0b7acd9
eisen@Endor build % 
Additionally, this PR switches the server form using a std::vector to using malloc's memory for a Get() destination.  This avoids the obligatory (but unnecessary in this situation) vector zero-init.  At some point we should probably use a buffer pool to avoid repeated malloc's.
=> Add random port/report port in background, switch to malloc for data buffers

source/adios2/toolkit/derived/Function.cpp, source/adios2/toolkit/derived/Function.h
The error we are getting when both XRootD and the derived variables are both ON:
```
Undefined symbols for architecture arm64:
"adios2::derived::Curl3DFunc(std::__1::vector<adios2::derived::DerivedData, std::__1::allocator<adios2::derived::DerivedData>>, adios2::DataType)", referenced from:
__GLOBAL__sub_I_XrdSsiSvService.cpp in XrdSsiSvService.cpp.o
"adios2::derived::CurlDimsFunc(std::__1::vector<std::__1::vector<unsigned long, std::__1::allocator<unsigned long>>, std::__1::allocator<std::__1::vector<unsigned long, std::__1::allocator<unsigned long>>>>)", referenced from:
__GLOBAL__sub_I_XrdSsiSvService.cpp in XrdSsiSvService.cpp.o
"adios2::derived::SameDimsFunc(std::__1::vector<std::__1::vector<unsigned long, std::__1::allocator<unsigned long>>, …
```
=> Patch for xrootd with derived variables

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, testing/adios2/engine/staging-common/TestCommonRead.cpp, testing/adios2/engine/staging-common/TestCommonReadF.F90, testing/adios2/engine/staging-common/TestCommonWrite.cpp, testing/adios2/engine/staging-common/TestCommonWriteF.F90, testing/adios2/engine/staging-common/TestShapeChangingWrite.cpp, thirdparty/ffs/ffs/ffs/ffs_conv.c, thirdparty/ffs/ffs/fm/fm.h, thirdparty/ffs/ffs/fm/fm_formats.c, thirdparty/ffs/ffs/fm/fm_internal.h
FFS has a feature where you can specify a default value for incoming structures (messages).  This is useful in an environment where different actors in a distributed system might be running different versions of software and helps let new systems accept old messages (if the "old" incoming message is missing a "new" field, that field is filled in with the default value and the message still be processed by new code, allowing a measure of transparent interoperability).  However, this feature is not useful in BP5 marshaling and the mechanism through which the default value is specified (enclosed in parens in the field name) restricts the set of ADIOS variable names to those that don't include an open paren.  This patch selectively disbles this feature of FFS for the FFS contexts that manage …
=> FFS tweaks

thirdparty/dill/dill/CMakeLists.txt, thirdparty/dill/dill/vm.c
Make Dill fall back to emulation on architectures where we don't have native CG.
=> Dill upstream in master

source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/toolkit/profiling/iochrono/IOChrono.cpp
Now BP5 Reader writes out  profilers. 
directory will be /tmp/<bp_file_name> after pull request 4205 is merged.
=> Read profiler fix

source/adios2/helper/kokkos/adiosKokkos.cpp
Backports https://github.com/ornladios/ADIOS2/pull/4213
=> kokkos: support ROCM >=6

source/adios2/common/ADIOSTypes.h, source/adios2/core/ADIOS.cpp, source/adios2/core/ADIOS.h, source/adios2/core/Engine.cpp, source/adios2/core/Engine.h, source/adios2/engine/campaign/CampaignManager.h, source/adios2/engine/campaign/CampaignReader.cpp, source/adios2/helper/adiosYAML.cpp, source/adios2/helper/adiosYAML.h, source/adios2/toolkit/transport/file/FileAWSSDK.cpp, source/adios2/toolkit/transport/file/FileAWSSDK.h, source/utils/adios_campaign_manager/adios2_campaign_manager.py
Backport #4189 and #4174 to master
4174:
- Deactivate campaign recording by default. Use .adios-campaign/ as directory name.
4189:
- Parse ~/.config/adios2/hosts.yaml and build HostOptions dictionary
- S3 protocol well defined, SSH and XRootD needs testing and fixing
- Enable creating a remote campaign with S3 location in adios2_campaign_manager
- CampaignReader handles S3 hosts and launches BP5 with AWSSDK transport library
- Add option 'verbose' to all protocols, and 'local_port' to the SSH protocol
- option 'recheck_metadata' for S3 protocol: if set to false, it will not check the file on S3 to confirm that cached version is full size (i.e. much faster read of metadata)
- FileAWSSDK: Flush to disk when writing to cache
Usage:
adios2_campaign_manager -v create MAST/30466 -n STFC-S3 …
=> Backport PR 4189 and 4174 to master

source/adios2/helper/kokkos/adiosKokkos.cpp
Bug introduced in #4214 (PR solving the problem in ROCM API change for hipPointerAttribute_t:
ROCM 5.3: https://rocm.docs.amd.com/projects/HIP/en/docs-5.3.3/doxygen/html/structhip_pointer_attribute__t.html
ROCM 6.1: https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/structhip_pointer_attribute__t.html
@pnorbert this needs to be part of the latest release/patch or the GPU support on Frontier will give compile errors
=> [Bug fix] Switch from `ROCM_VERSION_MAJOR` to `HIP_VERSION_MAJOR`

source/adios2/core/ADIOS.cpp, source/adios2/core/ADIOS.h, source/adios2/engine/bp5/BP5Engine.h, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/campaign/CampaignReader.cpp, source/adios2/helper/adiosNetwork.cpp, source/adios2/helper/adiosNetwork.h, source/adios2/toolkit/remote/EVPathRemote.cpp, source/adios2/toolkit/remote/EVPathRemote.h, source/adios2/toolkit/remote/Remote.cpp, source/adios2/toolkit/remote/Remote.h, source/adios2/toolkit/remote/XrootdRemote.cpp, source/adios2/toolkit/remote/XrootdRemote.h, source/adios2/toolkit/transport/file/FileRemote.cpp, source/adios2/toolkit/transport/file/FileRemote.h
- Added function LaunchRemoteServerViaConnectionManager() to Remote class to talk to local tunnel server to establish a connection to remote host (and launch adios2_remote_server on remote host). Local tunnel server is looked for on fixed port 30000 for now. Remote server's port and local port forwarded to remote server's port are dynamic.
- Ugly hack: added to ADIOS a static Class-member (m_StaticHostOptions) and class-function (StaticGetHostOptions()) that contains one of the ADIOS object's HostOptions, in order to allow access to HostOptions from functions that has no access to any ADIOS objects (e.g. FileRemote transport).
=> Connect to tunnel server to launch remote server

source/adios2/toolkit/format/bp5/BP5Serializer.cpp
Before this PR, adios2 calls `ApplyExpression` every time there is a derived variable (which is identified by the expression string we encode in the name). However, for variables where we store data we do not want to recompute the values. The easiest fix is to not store the expression string for these variables (since in essence they are no longer derived variables).
=> [Bug fix] Read side computation of derived variables should not be triggered when data is stored

CMakeLists.txt, cmake/DetectOptions.cmake
#4250  broke the CI, the reason is that we did not test this kvcache enable in the corresponding CI due to a typo. 
Disabling kvcache until we resolve this
=> cmake,ci: disable kvcache

source/adios2/toolkit/derived/Expression.cpp, source/adios2/toolkit/derived/Function.cpp, source/adios2/toolkit/format/bp5/BP5Deserializer.cpp
PR to fix errors and warnings related to derived variables (except the lexer related warnings since @lizdulac is opening a PR on fixing lexer issues)
**Mismatch in reading count when reading variables that are part of a derived variable**
`Req->Count.data()` are the dimensions of the derived variable in the current request
`VarRec->DimCount` are the total dimensions of one of the variables used by the derived variable.
In all ecause Curl adds one dimension at the end).
However, I am adding now an aggregated operator that will have a lower dimension than the composing variables, so this line seg faults.
=> Fix errors and warning related to derived variables

.github/workflows/everything.yml, .github/workflows/pypackaging.yml, scripts/ci/cmake/ci-win2019-vs2019-msmpi.cmake, scripts/ci/cmake/ci-win2022-vs2022-msmpi.cmake, scripts/ci/cmake/ci-win2022-vs2022-serial.cmake
This will save us from future feature removals of current deprecations. Warnings are found at the bottom of the following link: https://github.com/ornladios/ADIOS2/actions/runs/10100803550
=> ci: address gha warnings

source/adios2/core/IO.cpp, source/adios2/core/VariableDerived.cpp, source/adios2/core/VariableDerived.h, source/adios2/toolkit/derived/DerivedData.h, source/adios2/toolkit/derived/Expression.cpp, source/adios2/toolkit/derived/Expression.h, source/adios2/toolkit/derived/Function.cpp, source/adios2/toolkit/derived/Function.h
For derived operations that do not have the same input and output type, e.g. `float sqrt(int)`
DerivedData contains now in addition to the data pointer and the start and count Dims, the type of each input operand. The derived functions will have the following signature:
```
struct DerivedData
{
void *Data;
Dims Start;
Dims Count;
DataType Type;
};
std::function<DerivedData(std::vector<DerivedData>, DataType)> ComputeFct;
```
The second argument `DataType` is the output type.
=> Relaxing the restriction of the derived variables to have the same type as the operands

testing/examples/heatTransfer/TestBPFileMx1.cmake, testing/examples/heatTransfer/TestBPFileMx1_zfp.cmake, testing/examples/heatTransfer/TestBPFileMxM.cmake, testing/examples/heatTransfer/TestBPFileMxN.cmake, testing/examples/heatTransfer/TestInlineMxM.cmake, testing/examples/heatTransfer/TestSSCMx1.cmake, testing/examples/heatTransfer/TestSSCMxM.cmake, testing/examples/heatTransfer/TestSSCMxN.cmake, testing/examples/heatTransfer/TestSSTBPMx1.cmake, testing/examples/heatTransfer/TestSSTBPMxM.cmake, testing/examples/heatTransfer/TestSSTBPMxN.cmake, testing/examples/heatTransfer/TestSSTBPRDMAMxN.cmake, testing/examples/heatTransfer/TestSSTFFSMx1.cmake, testing/examples/heatTransfer/TestSSTFFSMxM.cmake, testing/examples/heatTransfer/TestSSTFFSMxN.cmake, testing/examples/heatTransfer/TestSSTFFSRDMAMxN.cmake
Another stab at killing CI heisenbugs that might be related to concurrent test execution.
=> Uniquify filenames in HeatTransfer tests

scripts/build_scripts/build-adios2-kokkos-frontier.sh
The gcc and cray modules on Frontier used in the build scripts have been deprecated as of July 2024:
```
gcc/11.2.0:
As of July 16, 2024, the 'gcc' module name is deprecated and has been replaced by 'gcc-native'. Running 'module load gcc' from a
default login shell has undefined behavior due to this name change. Please use 'module load PrgEnv-gnu gcc', or optionally 'module
load PrgEnv-gnu cpe/23.09' to load older versions of the GNU toolchain. See
https://docs.olcf.ornl.gov/software/software-news.html#frontier-system-software-update-july-16-2024 for more information.
```
=> Update the script to build adios with Kokkos for Frontier

docs/user_guide/source/advanced/derived_variables.rst
Third time is the lucky one (The format introduced in https://github.com/ornladios/ADIOS2/pull/4301 doesn't show the table)
=> Fixing formatting in the derived documentation

.github/workflows/pypackaging.yml
There is a total size limit in testpypi for releases. I went ahead and deleted older testpypi releases, but to avoid happening in the future, I marked the testpypi upload job as manual.
=> ci: fix pypi artifacts

source/adios2/toolkit/derived/Expression.cpp, source/adios2/toolkit/derived/Function.cpp, source/adios2/toolkit/derived/Function.h, testing/adios2/derived/TestBPDerivedCorrectness.cpp
The changes will allow `ADD` and `MAG` to work on a single variable and apply the operation as an aggregation on the last dimension.
e.g. for a 2D variable with dimensions (4, 2) with values:
```
1 2
3 4
5 6
7 8
```
`add(variable)` will return a 1D array with dimension (4) and values [3 7 11 15]
Since `CURL` is returning a single variable containing all 3 vectors x, y, z this PR will allow us to create a derived variable for magnitude of curl.
The PR is a different solution from #4208 that was splitting variable into corresponding subarrays. In the previous example, #4208 creates 4 1D arrays of dimension 2 and applies normal add over them. We need this functionality as well but this PR reduces the number of temporary variables used inside adios.
=> Introducing aggregated derived operators 

scripts/ci/gh-actions/macos-setup.sh, scripts/ci/gh-actions/windows-setup.ps1
Conda default channels requires a licence for organizations over 200 people, it is unclear whether this is ornl;github;kitware or just adios2 dev team. To play on the safe side, avoid using the defaults channel in conda.
=> ci: only use conda-forge channel

source/adios2/toolkit/derived/Expression.cpp, source/adios2/toolkit/derived/Expression.h, source/adios2/toolkit/derived/Function.cpp, source/adios2/toolkit/derived/Function.h, testing/adios2/derived/TestBPDerivedCorrectness.cpp
Create 3D cross product function that can be called in the format "cross(Ax, Ay, Az, Bx, By, Bz)"
For now, to compute AxB (A and B being 3D vectors), the components of the vector must be given individually as shown above.
"x" symbol operator not recognized in this pr (ie. AxB)
=> Extend Expressions: 3D Cross product

bindings/Python/py11Engine.cpp, python/adios2/stream.py, testing/adios2/python/TestBPWriteTypesHighLevelAPILocal.py
a. BlocksInfo(name, step)  
b. stream.write() sets selection if either 'start' or 'count' is provided (fix for local arrays).
This code below shows the original problem when enumerating the blocks of the `v3` variable in the localArray example, where the number of blocks changes across the steps. 
```
#!/usr/bin/env python3
import numpy as np
import adios2
def process_var(varname):
print("--------------------------")
print(f"Process variable {varname}")
v = f.inquire_variable(varname)
for step in range(v.steps()):
v.set_step_selection([step, 1])
bs = f.engine.blocks_info(varname, step)
for bid in range(len(bs)):   # could use here len(b[step])
v.set_step_selection([step, 1])
v.set_block_selection(bid)
data = f.read(v)
print(f"step {step} block {bid} len = {len(data)}")
with …
```
=> Fix in python API: 

source/adios2/toolkit/format/bp5/BP5Deserializer.cpp, testing/adios2/engine/bp/TestBPWriteReadLocalVariables.cpp
when some producers did not write any block to output.
Issue could be reproduced before this fix by running localArray example with multiple processes. `v3` is not written by every process and in the third step, there is a "gap" meaning, rank N did not write, but rank N+1 did write a block. Then the following script would fail in reading the blocks from the third step.
```
#!/usr/bin/env python3
import numpy as np
import adios2
def process_var(f, varname):
print("--------------------------")
print(f"Process variable {varname}")
v = f.inquire_variable(varname)
for step in range(v.steps()):
v.set_step_selection([step, 1])
bs = f.engine.blocks_info(varname, step)
for bid in range(len(bs)):   # could use here len(b[step])
v.set_block_selection(bid)
data = f.read(v)
print(f"step {step} block …
```
=> Fix an issue when reading blocks in streaming mode

source/utils/CMakeLists.txt, source/utils/bpcmp/CMakeLists.txt, source/utils/bpcmp/bpcmp.cmake.gen.in, source/utils/bpcmp/bpcmp.py, testing/utils/CMakeLists.txt, testing/utils/bpcmp/CMakeLists.txt, testing/utils/bpcmp/TestUtilsBPcmp.cpp, testing/utils/bpcmp/TestUtilsBPcmp.stats.expected.txt, testing/utils/bpcmp/TestUtilsBPcmp.verbose.expected.txt
Based on a request from GX developers, this is the first version of a python script to compare the information in two BP files (given a certain tolerance). The functionality is kept similar to https://gitlab.com/remikz/nccmp 
Current differences detected:
- **Metadata** (number of steps, number of variables, type and dimension of each variable)
- **Stats** (min/max with a tolerance) - only if the `--stats` option is used
- **Values** (values on each position with a tolerance)
The tolerance can be absolute value or percentage. 
Example metadata differences:
```
$ python bpcmp.py BPFileStepsWriteRead.bp BPFileStepsWriteReadKokkos.bp
COMPARE : FILE : BPFileStepsWriteRead.bp : FILE : BPFileStepsWriteReadKokkos.bp
DIFFER : NUM_STEPS : 10 <> 1 : BPFileStepsWriteRead.bp : …
```
=> Basic script to compare two BP files given a tolerance

source/adios2/operator/compress/CompressMGARD.cpp
It was uncompresed until now.
```
$ ctest -R MGARD.*/.*BP5.Serial
$ find testing/adios2/engine/bp/operations/bp5 -name "*bp" -exec du -sh {} \;
48K     testing/adios2/engine/bp/operations/bp5/BPWRMGARD3DSel_0.00001.bp
40K     testing/adios2/engine/bp/operations/bp5/BPWRMGARD1DSel_0.00001.bp
60K     testing/adios2/engine/bp/operations/bp5/BPWRMGARD2D_0.01.bp
36K     testing/adios2/engine/bp/operations/bp5/BPWRMGARD3D_0.00001.bp
44K     testing/adios2/engine/bp/operations/bp5/BPWRMGARD2DSel_0.0001.bp
40K     testing/adios2/engine/bp/operations/bp5/BPWRMGARD1D_0.00001.bp
36K     testing/adios2/engine/bp/operations/bp5/BPWRMGARD3D_0.0001.bp
40K     testing/adios2/engine/bp/operations/bp5/BPWRMGARD1DSel_0.0001.bp
32K     testing/adios2/engine/bp/operations/bp5/BPWRMGARDNull_0.01.bp
40K …
```
=> Compress the lossless part of MGARD data with Zstd. 

source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/bp5/BP5Writer.h
Organize the processes into groups so that the two steps of metadata aggregation has more or less the same number or participants. This replaces in-node aggregation in first step. The new strategy balances the size of metadata gathered in the two steps.
=> Backport #3759 to master.

source/adios2/toolkit/format/bp5/BP5Serializer.cpp
Memory selections when GPU pointers are used for BP5 copies the data to internal buffers before min/max is applied. I am updating the memory space for spans to Host when data is moved to temp buffers.
=> Setting the memory space for Spans to Host

source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/bp5/BP5Writer.h
(cherry-picked from master branch #4340)
Organize the processes into groups so that the two steps of metadata aggregation has more or less the same number or participants. This replaces in-node aggregation in first step. The new strategy balances the size of metadata gathered in the two steps.
=> Backport #3759 to Release 2.10 branch. 

scripts/ci/cmake/ci-macos-12-xcode13_4_1-static-serial.cmake
It fixes the macos 12 build. Still macos 11 will fail but something is better than nothing. Lets bring all the CI changes to this branch if we decided on doing another patch release.
x-ref: #4341
=> Backport 4305

source/adios2/core/Engine.tcc, source/adios2/engine/inline/InlineReader.tcc, source/adios2/engine/skeleton/SkeletonReader.tcc, source/adios2/engine/ssc/SscReader.cpp, testing/adios2/engine/bp/TestBPWriteReadADIOS2.cpp
For Get(variable, datum), check that variable shape is Global or Local Value, pass launch mode.  Modify test to cover the situation.
=> Checks and changes in Get(variable, datum)

bindings/CXX11/adios2/cxx11/Engine.h, source/adios2/core/VariableBase.cpp
Since we set the memory space after we set all the variable shapes and selections, the memory selection needs to be updated together with the variable shape.
```c++
const adios2::Dims shape{static_cast<size_t>(Nx * mpiSize), Ny};
const adios2::Dims start{static_cast<size_t>(Nx * mpiRank), 0};
const adios2::Dims count{Nx, Ny};
auto var = io.DefineVariable<float>("r32", shape, start, count);
const adios2::Dims memoryStart = {ghostCells, ghostCells};
const adios2::Dims memoryCount = {totalNx, totalNy};
var.SetMemorySelection({memoryStart, memoryCount});
var.SetMemorySpace(adios2::MemorySpace::GPU);
```
The `SetMemorySpace` call was updating the shape, start and count but not the memory selection.
@franzpoeschel this is why your code was writing the wrong data for your 2D array. Could you …
=> Update the memory selection layout when there is a layout mismatch

source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/helper/adiosMemory.cpp, source/adios2/helper/adiosMemory.h, source/adios2/helper/adiosMemory.inl, source/adios2/helper/kokkos/adiosKokkos.cpp
NdCopy is used to copy data for Spans during write. However, NdCopy is also used by the reader to bring data to the user buffer. For buffers allocated on the CPU this is not a problem since the direction is not important. For the GPU backend however the copy needs to happen from the Host to the Device or from the Device to the Host depending on what operation is being done.
This PR add an extra argument to NdCopy that reads true if the function is called by the writer and false if called by the reader. 
The Kokkos backend did not have this problem because Kokkos::deep_copy internally detects the correct memory spaces and so it copies the data correctly. CudaMemcpy cannot do this. 
Part of this PR I also updated the Kokkos code to use explicit the correct memory space so we don't rely on …
=> Fix the code that copies wrongly from host to device GPU buffers instead of device to host

.gitlab/gitlab-ci-frontier.yml
The update to Core/24.07 does not provide the packages: libffi and zstd.
=> ci(frontier): revert to use Core/24.00

.gitlab/gitlab-ci-frontier.yml, testing/adios2/CMakeLists.txt, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPWriteReadKokkos.cpp, testing/adios2/gpu-backend/CMakeLists.txt, testing/adios2/gpu-backend/TestBPWriteReadKokkos.cpp
Reopening #4358 (closing it was a mistake)
If hipcc is used as the CXX compiler there is no error, but the CI is using g++ so we need to manually set the CXX compiler to whatever was used to build Kokkos.
The rocm version had to be updated to rocm/5.7.1 in the frontier CI due to an incompatibility between the g++ version in PrgEnv-gnu/8.5.0 and the hipcc version in rocm/5.4.3
The Kokkos version had to be updated to > 4.0.0 due to a warning with 3.7.01 and newer rocm compilers.
@vicentebolea thank you for catching the mistake.
=> Fix the Kokkos testing compilation error on Frontier

.gitlab/gitlab-ci-frontier.yml
The frontier cray CI was failing:
```
Lmod has detected the following error: The following module(s) are unknown:
"zstd" "libffi"
```
They both require the Core/24.00 module that is not compatible with DefApps
@vicentebolea please let me know if you think another fix will be better.
=> Replacing DefApps with Core/24.00 for the frontier-cray CI

testing/adios2/gpu-backend/TestBPWriteReadKokkos.cpp
Adding a test that writes and reads a 2D array of particles.
```
struct particle
{
double a;
int b[2];
};
Kokkos::View<particle **, Kokkos::DefaultExecutionSpace::memory_space> myParticles("inBuffer", DIM1, DIM2);
```
Test passes on HIP/CUDA/CPU backends. We only test writing and reading on the same memory space.
=> Add testing for structs using Kokkos Views

source/adios2/helper/adiosMemory.cpp, source/adios2/helper/adiosMemory.h
I am not sure how to add this only in the release and not master. I don't think we want this in 2.11
Required so that we can include #4359 in the 2.10 release without breaking the ABI.
=> Overload NdCopy instead of adding a new argument for the 2.10 release

docs/user_guide/source/engines/bp5.rst, source/adios2/CMakeLists.txt, source/adios2/engine/bp5/BP5Engine.h, source/adios2/engine/bp5/BP5Writer.cpp, source/adios2/engine/bp5/BP5Writer.h, source/adios2/toolkit/format/bp5/BP5Helper.cpp, source/adios2/toolkit/format/bp5/BP5Helper.h, source/adios2/toolkit/format/bp5/BP5Serializer.cpp, source/adios2/toolkit/profiling/iochrono/IOChrono.cpp, testing/adios2/performance/metadata/PerfMetaData.cpp
Still a little tentative, want to make sure it doesn't break at high scales (on machines where gatherv breaks at high scales), but would like to merge at this point to get it into master.
=> Add New SelectiveMetadatAggregation method

source/adios2/engine/bp5/BP5Writer.cpp, testing/adios2/derived/TestBPDerivedCorrectness.cpp
We were checking if a variable was defined before allowing the derived variables to be defined but we were not checking correctly if there is data written in a given step for all the variables needed by the derived expression. Before this fix the code was seg faulting.
I added a test for what happens when we try to define a derived variable before we define the component variables and what happens when there's no data to compute the derived variable.
=> [Bug fix] SegFault when a variable that is part of a derived expression doesn't have data

source/adios2/core/Engine.h
When I try to bpls on an aca file (in Norbert's branch) I am getting seg fault
```
$ ./bin/bpls -l run-488.aca --show-derived
double   ckpt.bp/U      {8, 66, 66, 66} = 0.0964156 / 1
Segmentation fault: 11
```
This is because bpls checks the length of the expression string to decide if a variable is derived or not:
```
std::string ExprStr = fp->VariableExprStr(*variable);
if (ExprStr.size() > 0)
// do stuff
```
Normally we return an empty string so this is fine in most cases:
```c++
std::string BP5Reader::VariableExprStr(const VariableBase &Var)
{
// check if this is a derived variable and return the correct string, else
std::string noDerive("");
return noDerive;
}
```
However, for some reason `aca` files use the default implementation in Engine.h which is wrongly returning a NULL pointer.
=> [Bug fix] Change the default expression string for derived variables

testing/adios2/derived/CMakeLists.txt, testing/adios2/derived/TestBPDerivedCorrectness.cpp, testing/adios2/derived/TestBPDerivedCorrectnessMPI.cpp
The vector operations (cross and magnitude), curl and magnitude of curl are left as serial tests.
The scalar and trig derived expressions are tested both serial and with MPI. Each test writes using MPI processes (with X ranks) and reads all the data on rank 0 where correctness is checked.
=> Separate the derived variable testing in MPI and not MPI functions

source/adios2/engine/campaign/CampaignReader.cpp, source/adios2/engine/campaign/CampaignReader.h
so that bpls can show the derived expression when applied to `aca` files.
With this PR:
```
$ ./bin/bpls -l gray-scott-derived-run1.aca --show-derived
double   gs-derived.bp/U              200*{128, 128, 128} = 0.0813067 / 1
double   gs-derived.bp/V              200*{128, 128, 128} = 0 / 0.674805
double   gs-derived.bp/derived/sumUV  200*{128, 128, 128} = 0.306159 / 1
Derived variable with expression: ADD({U},{V})
int32_t  gs-derived.bp/step           200*scalar = 10 / 2000
```
Before this PR:
```
$ ./bin/bpls -l gray-scott-derived-run1.aca --show-derived
double   gs-derived.bp/U              200*{128, 128, 128} = 0.0813067 / 1
double   gs-derived.bp/V              200*{128, 128, 128} = 0 / 0.674805
double   gs-derived.bp/derived/sumUV  200*{128, 128, 128} = 0.306159 / 1
int32_t …
```
=> Add the VariableExprStr function in the CampaignReader

source/adios2/core/Variable.h, source/adios2/toolkit/query/BlockIndex.h, source/adios2/toolkit/shm/TokenChain.h
Required by C++20 standard.
How to test: in CMakeLists.txt:109 change CMAKE_CXX_STANDARD to 20 or 23 from 11
Fixes #4414
=> Remove <T> from constructor/destructor declarations. 

testing/adios2/python/TestDerivedVariable.py
The current testing only included derived variables that store values.
=> Testing the python API for derived variables (Stats and Expression)

thirdparty/KWSys/adios2sys/CMakeLists.txt, thirdparty/KWSys/adios2sys/CONTRIBUTING.rst, thirdparty/KWSys/adios2sys/CommandLineArguments.cxx, thirdparty/KWSys/adios2sys/Configure.hxx.in, thirdparty/KWSys/adios2sys/Directory.cxx, thirdparty/KWSys/adios2sys/Glob.cxx, thirdparty/KWSys/adios2sys/MD5.c, thirdparty/KWSys/adios2sys/ProcessUNIX.c, thirdparty/KWSys/adios2sys/ProcessWin32.c, thirdparty/KWSys/adios2sys/RegularExpression.cxx, thirdparty/KWSys/adios2sys/RegularExpression.hxx.in, thirdparty/KWSys/adios2sys/SystemInformation.cxx, thirdparty/KWSys/adios2sys/SystemTools.cxx, thirdparty/KWSys/adios2sys/SystemTools.hxx.in, thirdparty/KWSys/adios2sys/Terminal.c, thirdparty/KWSys/adios2sys/testConsoleBuf.cxx, thirdparty/KWSys/adios2sys/testSystemTools.cxx
Fixes: #4419 
We need to update clang since no current fedora support clang9. Our sanitizer builds have many failures at the test phase but it is not reported if we cannot find any sanitizer issue. This was the case before this update, and now. 
After finishing this I will move these builds to the Spack CI
=> thirdparty: Update kwsys

source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/toolkit/remote/XrootdRemote.cpp, source/adios2/toolkit/remote/XrootdRemote.h
The test (!m_Remote) was intended as a test to see if the objected pointed to by the m_Remote pointer was valid, but that syntax should have been (!(*m_Remote)).  Fixing this, and maybe this will get a better error for the Remote test failures we sometimes see in CI.
=> Remote server test fix

.github/workflows/everything.yml
Github is phasing out ubuntu 20.04 machines
=> ci: set ubuntu host to be ubuntu22.04

source/adios2/engine/bp5/BP5Engine.h, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/campaign/CampaignData.cpp, source/adios2/engine/campaign/CampaignData.h, source/adios2/engine/campaign/CampaignReader.cpp, source/adios2/toolkit/kvcache/KVCacheCommon.cpp, source/adios2/toolkit/kvcache/KVCacheCommon.h
- Cached data is saved in under the locally opened BP folder, instead of pushing into the KV store. Store the reference to the file as KV value instead.
- Use UUID of each dataset in campaign in kv-cache keys and in the cache filenames. Requires ACA >= 0.3 campaign files.
- Organize cache folders with XXX/XXXYYYYY, using first three letters of UUID to create a subfolder, to avoid creating too many folders in the root directory.
=> Cache data blocks larger than 1MB in files.

bindings/Python/py11Engine.cpp, bindings/Python/py11Engine.h, bindings/Python/py11Variable.cpp, bindings/Python/py11Variable.h, bindings/Python/py11glue.cpp, examples/hello/bpStepsWriteReadCuda/bpStepsWriteReadCuda.py
**Allow python to feed GPU pointers to ADIOS.**
Writer side will have to provide the pointer to the cupy array in the call to Put.
Reader side can call Shape(adios2.MemorySpace.GPU) to receive the dimensions correctly for the GPU then will have to SetSelection to this shape and allocate memory on the GPU using these dimensions.
Example in  `examples/hello/bpStepsWriteReadCuda/bpStepsWriteReadCuda.py`
Running the examples:
```
$ python examples/hello/bpStepsWriteReadCuda/bpStepsWriteReadCuda.py
Array allocation:  <CUDA Device 0>
Bytes required to store the gpu array 24
Bytes allocated on the device memory pool 512
Bytes used on the device memory pool 512
Blocks allocated on the pinned memory pool (The allocated pinned memory is released just after the transfer is complete) 1
Write to file …
```
=> Bindings for cuPy pointers

source/adios2/core/VariableDerived.cpp, source/adios2/toolkit/derived/Expression.cpp, source/adios2/toolkit/derived/Expression.h, source/adios2/toolkit/derived/Function.cpp, testing/adios2/derived/TestBPDerivedCorrectness.cpp
Setting the type and dimensions of a variable is currently done in two places using two different logics. One in the math expressions (the return `DerivedData` object has the dimensions set by the math function) and the second in the derived variable class (when defining the variable). This PR removes the logic inside the math function so we have consistent dimensions and types.
Before this PR if you defined a derived variable:
```
bpIO.DefineDerivedVariable("derived/myderived",
"x = U \n"
"sqrt(pow(x))",
adios2::DerivedVarType::StatsOnly);
```
The result your error with the following message:
```
"x = U\n sqrt(pow(x))" -> <Derived> <Function> <SqrtFunc> : Invalid variable types
```
**I tested this with the derived variables on and the CI passes**
=> [BugFix] Set the correct dimensions and type for a derived expression

cmake/DetectOptions.cmake, thirdparty/enet/enet/CMakeLists.txt
Only try to find Caliper if DAOS is found, because it's not used by non-DAOS code.  Pull in new version of enet with increased minimum CMake version to avoid warnings.
=> Cleanup CMake a bit

.gitlab/gitlab-ci-frontier.yml
HDF5 is not needed since HDF5 adios2 support is already disabled at both: `scripts/ci/cmake/ci-frontier-cray.cmake` and `scripts/ci/cmake/ci-frontier-kokkos-hip.cmake`
=> ci,frontier: do not load hdf5

source/adios2/core/VariableBase.cpp
ADIOS' intent was always for variables to have a fixed dimension count (I.E. 2D, 3D, 4D, etc.) with possibly changing dimensions.  But we didn't check for changing dimension count.  This PR adds that check in SetShape.
Closes #4474
=> Catch Shape.size() change

.github/workflows/stale.yml
Add daily check that goes through opened issues and set them as stale if open and inactive for over a year.
For issues that are stale, they will be closed a month later if still inactive. Re-opening the issue resets the timers.
=> issues: stale issues that have been open been inactive

testing/adios2/engine/bp/kill_xrootd.sh, testing/adios2/engine/bp/start_xrootd.sh
Nothing exciting, just adding an exit 0 to the xrootd server start/stop scripts so that they never fail to CI (as they seem to do randomly).
=> Kill heisen failures on xrootd start

examples/hello/bpStepsWriteReadCuda/bpStepsWriteReadCupy-bindings.py, examples/hello/bpStepsWriteReadCuda/bpStepsWriteReadCupy.py, examples/hello/bpStepsWriteReadCuda/bpStepsWriteReadTorch-bindings.py, examples/hello/bpStepsWriteReadCuda/bpStepsWriteReadTorch.py, python/adios2/engine.py, python/adios2/stream.py, testing/adios2/python/TestBPWriteReadArrays.py
On the **write** side:
```python
cuda0 = torch.device('cuda:0')
gpuArray = torch.tensor([[0, 1.0, 2.0], [3.0, 4.0, 5.0]], dtype=torch.float32, device=cuda0)
gpuArray = cupy.array([[0, 1.0, 2.0], [3.0, 4.0, 5.0]], dtype=np.float32)
stream.write("gpuArray", gpuArray, gpuArray.shape, [0] * len(gpuArray.shape), gpuArray.shape)
```
On the **read** side, I added a function for receiving a pre-allocated buffer for the data
```python
cpuBuffer = numpy.zeros(cpuShape, dtype=np.float32)
gpuBuffer = cupy.zeros(gpuShape, dtype=np.float32)
tensorBuffer = torch.zeros(tensorShape, dtype=torch.float32, device=cuda0)
stream.read_in_buffer("cpuArray", cpuBuffer)
stream.read_in_buffer("gpuArray", gpuBuffer)
stream.read_in_buffer("tensorArray", tensorBuffer)
```
Testing was added for the new function.
=> Python API support for CuPy.arrays and torch.Tensor

examples/hello/deferredRead/deferred_timing_test.py, python/adios2/stream.py
Add `defer_read=bool` option to `Stream.read()` and `Stream.read_in_buffer()` functions. Need to use `Stream.read_complete()` to make sure data is read into the numpy/etc arrays. Timing test added to `examples/hello/deferredRead`
```
$ python3 ./deferred_timing_test.py
Write 1000 arrays of [100, 1000] shape
Time of writing: 1.082126s
Incoming nx, ny, nvars = 100, 1000, 1000
Time of reading one by one (Sync mode): 0.306817s
Incoming nx, ny, nvars = 100, 1000, 1000
Time of reading at once (Deferred mode): 0.067873s
```
=> Python API: Support Deferred mode for read

examples/hello/bpStepsWriteReadCuda/CMakeLists.txt, examples/hello/bpStepsWriteReadCuda/bpStepsWriteReadCBindings.cu, examples/hello/bpStepsWriteReadCuda/bpStepsWriteReadCuda.cu, examples/hello/bpStepsWriteReadKokkos/bpStepsWriteReadKokkos.F90, examples/hello/bpStepsWriteReadKokkos/view-f.f90
Fortran example using Kokkos and Fortran on Frontier (clang format messed the example so this PR fixes it):
```
$ ./bin/adios2_hello_bpStepsWriteReadKokkos_f
1       2       3
1       2       3
1       2       3
1       2       3
$ ./bin/bpls BPFortranKokkos.bp/ -d -n 3
int16_t  bpFloats  {4, 3}
(0,0)    1 2 3
(1,0)    1 2 3
(2,0)    1 2 3
(3,0)    1 2 3
```
For the C bindings, I added an example uses CUDA on Perlmutter:
```
$ ./bin/adios2_hello_bpStepsWriteReadCuda_c
$ ./bin/bpls -d BPStepsWriteReadCBindings.bp/
float    bpFloats  2*{3}
(0,0)    0 0 0 10 10 10
```
There was a memory leak in the C++ CUDA example that is fixed now.
=> Fixing the GPU examples for the Fortran and C bindings

source/adios2/toolkit/sst/dp/ucx_dp.c
A success/non-error message should not end up in stderr, and in my case made some test scripts fail.
=> init_fabric: use Trace verbosity instead of Critical for success message

source/adios2/toolkit/aggregator/mpi/MPIChain.cpp, testing/adios2/engine/bp/CMakeLists.txt, testing/adios2/engine/bp/TestBPNewFileAppendMode.cpp
If NumAggregators was set to 0 (to default to one file per node), a segfault would occur because `BP5Writer::m_NumAggregators` was never updated to the number of files. If opening a file with append mode and the file didn't already exist, `BP5Writer::m_AppendDataPos` had a size of 0 and would cause a segfault in `BP5Writer::InitBPBuffer`. 
I also added a simple test for it, and test it with both TLS and EWS. Even though it wasn't an issue in TLS, I figured maybe it would be good to test it to be sure it wouldn't break in the future.
=> Fix segfault in BP5 writer when using append mode, everyone writes serial, and num aggregators not set

examples/campaign/campaign_many_files.py, examples/campaign/campaign_many_files.sh, source/adios2/engine/bp5/BP5Reader.cpp, source/adios2/engine/bp5/BP5Reader.h, source/adios2/toolkit/remote/EVPathRemote.cpp, source/adios2/toolkit/remote/EVPathRemote.h
Use a single socket connection to a remote server from all engines accessing (different) files from the same host. This eliminates creating too many connections and tunnels to the same host when processing a campaign with lots of files.
=> Shared remote connection

scripts/ci/gh-actions/conda-env-win.yml, scripts/ci/gh-actions/windows-setup.ps1, scripts/ci/setup-run/ci-Windows.sh
The fix for the conda error in win2022 is not to update the base env before installing the adios2 env :shrug:
=> ci: fix conda windows error

source/utils/CMakeLists.txt, source/utils/bpcmp/CMakeLists.txt, source/utils/bpcmp/bpcmp.cmake.gen.in, source/utils/bpls/bpls.cmake.gen.in
Closes #4333 
The changes requested in the issue were:
1. Use `CMAKE_CURRENT_BINARY_DIR` instead of `PROJECT_BINARY_DIR`
2. Add quotes for all paths
3. Use the `maybe_xyz` convention in all cases when something might be generated or not
I made the changes everywhere relevant in the utils folder.
In a hierarchical project with subdirectories, when CMake processes a CMakeLists.txt file within a subdirectory, `CMAKE_CURRENT_BINARY_DIR` will reflect the specific build output directory for that subdirectory. `PROJECT_BINARY_DIR` refers to the build directory associated with the most recently encountered project() command. 
This means, in some places it's better to use `PROJECT_BINARY_DIR`.
Example, if I change it from `PROJECT_BINARY_DIR` to `CMAKE_CURRENT_BINARY_DIR` in …
=> Changes to the build system for the bpcmp utility

source/adios2/toolkit/derived/Function.cpp, testing/adios2/derived/TestBPDerivedCorrectness.cpp
This is needed by the WarpX derived variable that computes the `curl(cross(E,B))`
Curl currently requires three 3D arrays `curl(Ex, Ey, Ez)` while cross returns an array with all three vectors merged into a single N+1 dimension array. After this PR curl can be applied as `curl(E)` with Ex, Ey, Ex concatenated one after another into a 4D array (E) similar to how cross creates it.
=> CURL derived variable applied on an aggregated array
